export const SEED_USER_DOMAIN_EXPERTISE_ROWS = [
  {
    userKey: 'owner',
    techStackFrequency: {
      AdonisJS: 1,
      Browser: 1,
      Redis: 1,
      PostgreSQL: 2,
      Svelte: 2,
      TypeScript: 1,
    },
    domainFrequency: {
      edtech: 1,
      internal_tooling: 1,
      saas: 1,
      navigation: 1,
      marketplace: 1,
      subscription: 1,
      admin: 1,
      seed: 1,
      session: 1,
    },
    problemCategoryFrequency: {
      automation: 1,
      maintainability: 1,
      new_capability: 1,
      compliance: 1,
    },
    topSkills: [
      { skill_name: 'Leadership', weighted_score: 1, review_mentions: 1 },
      { skill_name: 'Code Review', weighted_score: 1, review_mentions: 1 },
      { skill_name: 'Testing & QA', weighted_score: 1, review_mentions: 1 },
      { skill_name: 'Communication', weighted_score: 1, review_mentions: 1 },
      { skill_name: 'PostgreSQL', weighted_score: 1, review_mentions: 1 },
    ],
  },
  {
    userKey: 'member',
    techStackFrequency: {
      Svelte: 3,
      Redis: 1,
      AdonisJS: 1,
      PostgreSQL: 2,
      Documentation: 1,
    },
    domainFrequency: {
      qa: 1,
      rbac: 1,
      saas: 2,
      admin: 1,
      proof: 1,
      review: 1,
      profile: 1,
      redirect: 1,
      navigation: 1,
      organization: 1,
      internal_tooling: 1,
    },
    problemCategoryFrequency: {
      new_capability: 2,
      maintainability: 1,
    },
    topSkills: [
      { skill_name: 'Testing & QA', weighted_score: 1, review_mentions: 2 },
      { skill_name: 'Communication', weighted_score: 1, review_mentions: 2 },
      { skill_name: 'TypeScript', weighted_score: 1, review_mentions: 1 },
      { skill_name: 'PostgreSQL', weighted_score: 1, review_mentions: 1 },
      { skill_name: 'Problem Solving', weighted_score: 1, review_mentions: 1 },
    ],
  },
] as const
