export const SEED_USER_DOMAIN_EXPERTISE_ROWS = [
  {
    userKey: 'owner',
    techStackFrequency: {
      AdonisJS: 6,
      API: 4,
      Redis: 3,
      PostgreSQL: 7,
      Svelte: 4,
      TypeScript: 8,
      Observability: 3,
    },
    domainFrequency: {
      edtech: 1,
      internal_tooling: 3,
      saas: 5,
      data_platform: 2,
      competency_review: 6,
      evidence_governance: 5,
      marketplace: 2,
      release_governance: 3,
      impact_analytics: 2,
    },
    problemCategoryFrequency: {
      automation: 3,
      maintainability: 2,
      new_capability: 4,
      compliance: 2,
      performance: 1,
    },
    topSkills: [
      { skill_name: 'System Design', weighted_score: 0.93, review_mentions: 3 },
      { skill_name: 'API Design', weighted_score: 0.92, review_mentions: 3 },
      { skill_name: 'Leadership', weighted_score: 0.91, review_mentions: 4 },
      { skill_name: 'TypeScript', weighted_score: 0.9, review_mentions: 4 },
      { skill_name: 'PostgreSQL', weighted_score: 0.9, review_mentions: 4 },
      { skill_name: 'Release Management', weighted_score: 0.89, review_mentions: 3 },
    ],
  },
  {
    userKey: 'member',
    techStackFrequency: {
      Svelte: 3,
      Redis: 1,
      AdonisJS: 1,
      PostgreSQL: 2,
      Documentation: 1,
    },
    domainFrequency: {
      qa: 1,
      rbac: 1,
      saas: 2,
      admin: 1,
      proof: 1,
      review: 1,
      profile: 1,
      redirect: 1,
      navigation: 1,
      organization: 1,
      internal_tooling: 1,
    },
    problemCategoryFrequency: {
      new_capability: 2,
      maintainability: 1,
    },
    topSkills: [
      { skill_name: 'Testing & QA', weighted_score: 1, review_mentions: 2 },
      { skill_name: 'Communication', weighted_score: 1, review_mentions: 2 },
      { skill_name: 'TypeScript', weighted_score: 1, review_mentions: 1 },
      { skill_name: 'PostgreSQL', weighted_score: 1, review_mentions: 1 },
      { skill_name: 'Problem Solving', weighted_score: 1, review_mentions: 1 },
    ],
  },
  {
    userKey: 'orgAdmin',
    techStackFrequency: { Svelte: 4, TypeScript: 5, PostgreSQL: 3, Analytics: 4 },
    domainFrequency: { product_operations: 8, quality_governance: 6, saas: 5 },
    problemCategoryFrequency: { ux_improvement: 4, automation: 3, compliance: 2 },
    topSkills: [
      { skill_name: 'Planning', weighted_score: 0.91, review_mentions: 5 },
      { skill_name: 'Leadership', weighted_score: 0.89, review_mentions: 4 },
      { skill_name: 'Risk Tracking', weighted_score: 0.87, review_mentions: 4 },
    ],
  },
  {
    userKey: 'peerReviewer',
    techStackFrequency: { Testing: 8, PostgreSQL: 3, Observability: 4 },
    domainFrequency: { quality_assurance: 9, competency_review: 7, marketplace: 3 },
    problemCategoryFrequency: { maintainability: 5, compliance: 4, automation: 2 },
    topSkills: [
      { skill_name: 'Testing & QA', weighted_score: 0.94, review_mentions: 8 },
      { skill_name: 'Code Review', weighted_score: 0.92, review_mentions: 7 },
      { skill_name: 'Communication', weighted_score: 0.88, review_mentions: 6 },
    ],
  },
  {
    userKey: 'orgBOwner',
    techStackFrequency: { Documentation: 9, Svelte: 2, Analytics: 3 },
    domainFrequency: { edtech: 12, curriculum_design: 10, employer_partnership: 5 },
    problemCategoryFrequency: { new_capability: 6, ux_improvement: 3, automation: 2 },
    topSkills: [
      { skill_name: 'Leadership', weighted_score: 0.9, review_mentions: 5 },
      { skill_name: 'Documentation', weighted_score: 0.89, review_mentions: 6 },
      { skill_name: 'Planning', weighted_score: 0.87, review_mentions: 5 },
    ],
  },
  {
    userKey: 'externalContributorOne',
    techStackFrequency: { Svelte: 3, Content: 12, Analytics: 3 },
    domainFrequency: { brand_storytelling: 11, talent_showcase: 9, marketplace: 5 },
    problemCategoryFrequency: { ux_improvement: 7, new_capability: 4, maintainability: 2 },
    topSkills: [
      { skill_name: 'Communication', weighted_score: 0.94, review_mentions: 7 },
      { skill_name: 'Documentation', weighted_score: 0.92, review_mentions: 6 },
      { skill_name: 'Design System', weighted_score: 0.86, review_mentions: 4 },
    ],
  },
  {
    userKey: 'externalContributorTwo',
    techStackFrequency: { PostgreSQL: 10, TypeScript: 6, Redis: 5, Observability: 6 },
    domainFrequency: { data_platform: 12, data_quality: 10, impact_analytics: 7 },
    problemCategoryFrequency: { automation: 7, performance: 5, compliance: 4 },
    topSkills: [
      { skill_name: 'PostgreSQL', weighted_score: 0.93, review_mentions: 7 },
      { skill_name: 'System Design', weighted_score: 0.9, review_mentions: 5 },
      { skill_name: 'Problem Solving', weighted_score: 0.89, review_mentions: 6 },
    ],
  },
  {
    userKey: 'superadmin',
    techStackFrequency: { Governance: 12, Audit: 10, Security: 8 },
    domainFrequency: { platform_governance: 12, dispute_resolution: 9, compliance: 8 },
    problemCategoryFrequency: { compliance: 8, security: 5, maintainability: 3 },
    topSkills: [
      { skill_name: 'Leadership', weighted_score: 0.95, review_mentions: 9 },
      { skill_name: 'Risk Tracking', weighted_score: 0.94, review_mentions: 8 },
      { skill_name: 'Communication', weighted_score: 0.92, review_mentions: 8 },
    ],
  },
] as const
