export const SEED_USER_PERFORMANCE_STATS_ROWS = [
  {
    userKey: 'owner',
    totalTasksCompleted: 9,
    totalHoursWorked: 157,
    avgQualityScore: 4.67,
    onTimeDeliveryRate: 88.89,
    avgDaysEarlyOrLate: 0.89,
    tasksByType: {
      feature_development: 5,
      qa_testing: 1,
      technical_writing: 2,
      devops_deployment: 1,
    },
    tasksByDifficulty: { medium: 2, hard: 6, expert: 1 },
    tasksByDomain: { edtech: 1, internal_tooling: 3, saas: 4, data_platform: 1 },
    tasksAsLead: 4,
    tasksAsSoleContributor: 2,
    tasksMentoringOthers: 2,
    longestOnTimeStreak: 7,
    currentOnTimeStreak: 4,
    selfAssessmentAccuracy: 91.2,
    performanceScore: 92.4,
  },
  {
    userKey: 'member',
    totalTasksCompleted: 3,
    totalHoursWorked: 49,
    avgQualityScore: 4.67,
    onTimeDeliveryRate: 0,
    avgDaysEarlyOrLate: 1.67,
    tasksByType: { technical_writing: 1, feature_development: 2 },
    tasksByDifficulty: { hard: 1, medium: 2 },
    tasksByDomain: { saas: 2, internal_tooling: 1 },
    tasksAsLead: 0,
    tasksAsSoleContributor: 0,
    tasksMentoringOthers: 0,
    longestOnTimeStreak: 0,
    currentOnTimeStreak: 0,
    selfAssessmentAccuracy: 91.67,
    performanceScore: 81.75,
  },
  {
    userKey: 'orgAdmin',
    totalTasksCompleted: 8, totalHoursWorked: 126, avgQualityScore: 4.55,
    onTimeDeliveryRate: 87.5, avgDaysEarlyOrLate: 0.6,
    tasksByType: { ui_ux_design: 3, qa_testing: 3, feature_development: 2 },
    tasksByDifficulty: { medium: 3, hard: 4, expert: 1 },
    tasksByDomain: { saas: 5, internal_tooling: 3 },
    tasksAsLead: 5, tasksAsSoleContributor: 1, tasksMentoringOthers: 3,
    longestOnTimeStreak: 5, currentOnTimeStreak: 3,
    selfAssessmentAccuracy: 89.4, performanceScore: 89.1,
  },
  {
    userKey: 'peerReviewer',
    totalTasksCompleted: 11, totalHoursWorked: 142, avgQualityScore: 4.72,
    onTimeDeliveryRate: 90.91, avgDaysEarlyOrLate: 1.1,
    tasksByType: { qa_testing: 6, code_review: 4, technical_writing: 1 },
    tasksByDifficulty: { medium: 4, hard: 6, expert: 1 },
    tasksByDomain: { saas: 5, internal_tooling: 4, data_platform: 2 },
    tasksAsLead: 3, tasksAsSoleContributor: 2, tasksMentoringOthers: 4,
    longestOnTimeStreak: 8, currentOnTimeStreak: 5,
    selfAssessmentAccuracy: 94.1, performanceScore: 93.2,
  },
  {
    userKey: 'orgBOwner',
    totalTasksCompleted: 10, totalHoursWorked: 168, avgQualityScore: 4.64,
    onTimeDeliveryRate: 90, avgDaysEarlyOrLate: 0.9,
    tasksByType: { technical_writing: 5, feature_development: 2, qa_testing: 3 },
    tasksByDifficulty: { medium: 4, hard: 5, expert: 1 },
    tasksByDomain: { edtech: 10 },
    tasksAsLead: 7, tasksAsSoleContributor: 1, tasksMentoringOthers: 5,
    longestOnTimeStreak: 7, currentOnTimeStreak: 4,
    selfAssessmentAccuracy: 90.8, performanceScore: 91.3,
  },
  {
    userKey: 'externalContributorOne',
    totalTasksCompleted: 14, totalHoursWorked: 176, avgQualityScore: 4.81,
    onTimeDeliveryRate: 92.86, avgDaysEarlyOrLate: 1.4,
    tasksByType: { technical_writing: 7, ui_ux_design: 5, feature_development: 2 },
    tasksByDifficulty: { medium: 6, hard: 7, expert: 1 },
    tasksByDomain: { saas: 9, edtech: 3, internal_tooling: 2 },
    tasksAsLead: 6, tasksAsSoleContributor: 5, tasksMentoringOthers: 2,
    longestOnTimeStreak: 9, currentOnTimeStreak: 6,
    selfAssessmentAccuracy: 92.7, performanceScore: 94.2,
  },
  {
    userKey: 'externalContributorTwo',
    totalTasksCompleted: 12, totalHoursWorked: 194, avgQualityScore: 4.7,
    onTimeDeliveryRate: 91.67, avgDaysEarlyOrLate: 0.8,
    tasksByType: { feature_development: 5, qa_testing: 3, devops_deployment: 4 },
    tasksByDifficulty: { medium: 3, hard: 7, expert: 2 },
    tasksByDomain: { data_platform: 10, saas: 2 },
    tasksAsLead: 5, tasksAsSoleContributor: 3, tasksMentoringOthers: 2,
    longestOnTimeStreak: 8, currentOnTimeStreak: 5,
    selfAssessmentAccuracy: 91.9, performanceScore: 92.8,
  },
  {
    userKey: 'superadmin',
    totalTasksCompleted: 7, totalHoursWorked: 98, avgQualityScore: 4.76,
    onTimeDeliveryRate: 100, avgDaysEarlyOrLate: 1.3,
    tasksByType: { code_review: 3, qa_testing: 2, technical_writing: 2 },
    tasksByDifficulty: { hard: 5, expert: 2 },
    tasksByDomain: { internal_tooling: 4, security: 3 },
    tasksAsLead: 6, tasksAsSoleContributor: 1, tasksMentoringOthers: 3,
    longestOnTimeStreak: 7, currentOnTimeStreak: 7,
    selfAssessmentAccuracy: 95.5, performanceScore: 95.1,
  },
] as const
