export const SEED_USER_PERFORMANCE_STATS_ROWS = [
  {
    userKey: 'owner',
    totalTasksCompleted: 3,
    totalHoursWorked: 35,
    avgQualityScore: 4,
    onTimeDeliveryRate: 66.67,
    avgDaysEarlyOrLate: -0.33,
    tasksByType: { feature_development: 2, qa_testing: 1 },
    tasksByDifficulty: { medium: 2, hard: 1 },
    tasksByDomain: { edtech: 1, internal_tooling: 1, saas: 1 },
    tasksAsLead: 1,
    tasksAsSoleContributor: 0,
    tasksMentoringOthers: 0,
    longestOnTimeStreak: 2,
    currentOnTimeStreak: 0,
    selfAssessmentAccuracy: 86.33,
    performanceScore: 86.5,
  },
  {
    userKey: 'member',
    totalTasksCompleted: 3,
    totalHoursWorked: 49,
    avgQualityScore: 4.67,
    onTimeDeliveryRate: 0,
    avgDaysEarlyOrLate: 1.67,
    tasksByType: { technical_writing: 1, feature_development: 2 },
    tasksByDifficulty: { hard: 1, medium: 2 },
    tasksByDomain: { saas: 2, internal_tooling: 1 },
    tasksAsLead: 0,
    tasksAsSoleContributor: 0,
    tasksMentoringOthers: 0,
    longestOnTimeStreak: 0,
    currentOnTimeStreak: 0,
    selfAssessmentAccuracy: 91.67,
    performanceScore: 81.75,
  },
] as const
