import { chmodSync, existsSync, mkdirSync, statSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

import db from '@adonisjs/lucid/services/db'

interface BackupLogger {
  info(message: string): void
  warning(message: string): void
}

interface BackupOptions {
  logger: BackupLogger
}

interface BackupAttempt {
  ok: boolean
  detail: string
}

interface TableReference {
  schema: string
  table: string
}

interface RawRowsResult<T> {
  rows: T[]
}

const SENSITIVE_BACKUP_COLUMN_PATTERN =
  /(password|token|secret|api[_-]?key|authorization|cookie|session|credential|private[_-]?key)/i

/**
 * Backups created before a local seed reset must never persist reusable credentials.
 * The record remains restorable, but its credential needs to be reissued afterwards.
 */
export function redactBackupValue(column: string, value: unknown): unknown {
  return SENSITIVE_BACKUP_COLUMN_PATTERN.test(column) ? null : value
}

function timestampForFilename(): string {
  return new Date().toISOString().replace(/[-:]/g, '').replace(/\..+$/, '').replace('T', '-')
}

function quoteIdentifier(value: string): string {
  return `"${value.replace(/"/g, '""')}"`
}

function quoteQualifiedTable(table: TableReference): string {
  return `${quoteIdentifier(table.schema)}.${quoteIdentifier(table.table)}`
}

function quoteLiteral(value: unknown): string {
  if (value === null || value === undefined) {
    return 'NULL'
  }

  if (typeof value === 'number') {
    return Number.isFinite(value) ? String(value) : 'NULL'
  }

  if (typeof value === 'bigint') {
    return value.toString()
  }

  if (typeof value === 'boolean') {
    return value ? 'TRUE' : 'FALSE'
  }

  if (value instanceof Date) {
    return `'${value.toISOString().replace(/'/g, "''")}'`
  }

  if (Buffer.isBuffer(value)) {
    return `E'\\\\x${value.toString('hex')}'`
  }

  const text = stringifyBackupValue(value)
  return `'${text.replace(/'/g, "''")}'`
}

function stringifyBackupValue(value: unknown): string {
  if (typeof value === 'string') {
    return value
  }

  if (typeof value === 'symbol') {
    return value.description ?? value.toString()
  }

  if (typeof value === 'function') {
    return '[function]'
  }

  if (typeof value === 'object') {
    const serialized = JSON.stringify(value) as string | undefined
    return serialized ?? ''
  }

  if (typeof value === 'number' || typeof value === 'bigint' || typeof value === 'boolean') {
    return value.toString()
  }

  if (value === undefined) {
    return ''
  }

  return ''
}

function isRawRowsResult<T>(value: unknown): value is RawRowsResult<T> {
  return (
    typeof value === 'object' &&
    value !== null &&
    'rows' in value &&
    Array.isArray(value.rows)
  )
}

function readRawRows<T>(value: unknown): T[] {
  return isRawRowsResult<T>(value) ? value.rows : []
}

function ensureBackupFile(path: string): BackupAttempt {
  if (!existsSync(path)) {
    return { ok: false, detail: 'backup file was not created' }
  }

  const stats = statSync(path)
  if (stats.size <= 0) {
    return { ok: false, detail: 'backup file is empty' }
  }

  return { ok: true, detail: path }
}

async function createDataOnlySqlBackup(targetPath: string): Promise<BackupAttempt> {
  const tableRows = (await db
    .from('information_schema.tables')
    .select('table_schema', 'table_name')
    .where('table_type', 'BASE TABLE')
    .whereIn('table_schema', ['public'])
    .orderBy('table_schema')
    .orderBy('table_name')) as { table_schema: string; table_name: string }[]

  const tables = tableRows.map<TableReference>((row) => ({
    schema: row.table_schema,
    table: row.table_name,
  }))

  const lines: string[] = [
    '-- Sanitized data-only backup generated by seed:data before destructive reset.',
    '-- Credential columns are replaced with NULL and must be reissued after restore.',
    '-- Restore with psql while connected as a role allowed to disable FK triggers.',
    'BEGIN;',
    'SET session_replication_role = replica;',
  ]

  if (tables.length > 0) {
    lines.push(
      `TRUNCATE TABLE ${tables.map(quoteQualifiedTable).join(', ')} RESTART IDENTITY CASCADE;`
    )
  }

  for (const table of tables) {
    const result = (await db.rawQuery(`SELECT * FROM ${quoteQualifiedTable(table)}`)) as unknown
    const rows = readRawRows<Record<string, unknown>>(result)
    if (rows.length === 0) {
      continue
    }

    const columns = Object.keys(rows[0] ?? {})
    if (columns.length === 0) {
      continue
    }

    const columnSql = columns.map(quoteIdentifier).join(', ')
    for (const row of rows) {
      const valuesSql = columns
        .map((column) => quoteLiteral(redactBackupValue(column, row[column])))
        .join(', ')
      lines.push(`INSERT INTO ${quoteQualifiedTable(table)} (${columnSql}) VALUES (${valuesSql});`)
    }
  }

  lines.push('SET session_replication_role = origin;', 'COMMIT;', '')
  writeFileSync(targetPath, lines.join('\n'), { encoding: 'utf8', mode: 0o600 })
  chmodSync(targetPath, 0o600)

  return ensureBackupFile(targetPath)
}

export async function createPostgresBackup(options: BackupOptions): Promise<string> {
  const database = process.env['PG_DATABASE'] ?? 'suar'
  const backupDir = resolve(process.cwd(), 'tmp', 'db-backups')
  mkdirSync(backupDir, { recursive: true, mode: 0o700 })
  chmodSync(backupDir, 0o700)

  const targetPath = join(backupDir, `${database}-before-reset-${timestampForFilename()}.sql`)

  options.logger.info('Creating sanitized data-only PostgreSQL backup before reset...')
  const backupAttempt = await createDataOnlySqlBackup(targetPath)
  if (backupAttempt.ok) {
    return targetPath
  }

  throw new Error(`Unable to create PostgreSQL backup before reset: ${backupAttempt.detail}`)
}
