export const SEED_REVIEW_SESSION_SPECS = [
  {
    key: 'member-org-switch',
    sessionStatus: 'completed',
    confirmationAction: 'confirmed',
    requiredPeerReviews: 1,
    overall: 5,
    delivery: 'on_time',
    requirement: 5,
    communication: 4,
    codeQuality: 5,
    proactive: 4,
    strengths:
      'Nắm rất nhanh logic quyền theo organization và chủ động đề xuất checklist test.',
    improvements: 'Có thể bổ sung thêm automation coverage cho đường dẫn redirect.',
    selfSatisfaction: 4,
    skills: [
      {
        reviewer: 'orgAdmin',
        reviewerType: 'manager',
        skill: 'typescript',
        level: 'senior',
        comment: 'Xử lý state và typing tốt, không để lọt case role mismatch.',
      },
      {
        reviewer: 'owner',
        reviewerType: 'peer',
        skill: 'communication',
        level: 'middle',
        comment: 'Trao đổi rõ các case edge và báo tiến độ đều.',
      },
    ],
  },
  {
    key: 'member-profile-proof',
    sessionStatus: 'completed',
    confirmationAction: 'confirmed',
    requiredPeerReviews: 2,
    overall: 5,
    delivery: 'slightly_late',
    requirement: 5,
    communication: 5,
    codeQuality: 4,
    proactive: 5,
    strengths:
      'Kết nối tốt dữ liệu từ review sang profile snapshot và tổng hợp đúng các proof cần hiển thị.',
    improvements: 'Cần tinh gọn thêm luồng invalidate cache profile.',
    selfSatisfaction: 5,
    skills: [
      {
        reviewer: 'orgAdmin',
        reviewerType: 'manager',
        skill: 'postgresql',
        level: 'middle',
        comment: 'Dựng dữ liệu profile aggregate chắc tay, nắm rõ bảng review và snapshot.',
      },
      {
        reviewer: 'peerReviewer',
        reviewerType: 'peer',
        skill: 'problem_solving',
        level: 'senior',
        comment: 'Biết lần theo dependency dữ liệu khi UI hiển thị tĩnh.',
      },
      {
        reviewer: 'peerReviewer',
        reviewerType: 'peer',
        skill: 'testing',
        level: 'middle',
        comment: 'Có checklist verify profile proof và share link.',
      },
    ],
  },
  {
    key: 'member-admin-regression',
    sessionStatus: 'completed',
    confirmationAction: 'confirmed',
    requiredPeerReviews: 1,
    overall: 4,
    delivery: 'on_time',
    requirement: 4,
    communication: 5,
    codeQuality: 4,
    proactive: 4,
    strengths: 'Tài liệu kiểm thử rõ ràng, dễ dùng cho admin redirect regression.',
    improvements: 'Nên thêm một case cho current_organization_id null.',
    selfSatisfaction: 4,
    skills: [
      {
        reviewer: 'orgAdmin',
        reviewerType: 'manager',
        skill: 'testing',
        level: 'middle',
        comment: 'Checklist hợp lý và bám sát bug report.',
      },
      {
        reviewer: 'peerReviewer',
        reviewerType: 'peer',
        skill: 'communication',
        level: 'senior',
        comment: 'Tài liệu rõ và có giải thích được tình huống back button.',
      },
    ],
  },
  {
    key: 'orgc-marketplace-ranking',
    sessionStatus: 'disputed',
    confirmationAction: 'disputed',
    requiredPeerReviews: 1,
    disputeReason:
      'Chưa thống nhất cách chấm trọng số package adoption metrics giữa reviewer peer và manager.',
    overall: 4,
    delivery: 'slightly_late',
    requirement: 4,
    communication: 4,
    codeQuality: 4,
    proactive: 5,
    strengths:
      'So sánh package và marketplace analytics khá tốt, tạo được dữ liệu đúng nhu cầu admin dashboard.',
    improvements: 'Cần chốt rubric review cho phần subscription analytics trước khi confirm.',
    selfSatisfaction: 4,
    skills: [
      {
        reviewer: 'peerReviewer',
        reviewerType: 'manager',
        skill: 'postgresql',
        level: 'senior',
        comment:
          'Thiết kế truy vấn package adoption tốt nhưng đang còn tranh luận về độ tối ưu cuối cùng.',
      },
      {
        reviewer: 'orgAdmin',
        reviewerType: 'peer',
        skill: 'problem_solving',
        level: 'senior',
        comment:
          'Giải quyết đúng bài toán so sánh package, nhưng reviewer cần thêm tiêu chí thống nhất.',
      },
    ],
  },
  {
    key: 'owner-profile-scoring-loop',
    sessionStatus: 'completed',
    confirmationAction: 'confirmed',
    requiredPeerReviews: 1,
    overall: 5,
    delivery: 'on_time',
    requirement: 5,
    communication: 5,
    codeQuality: 5,
    proactive: 4,
    strengths:
      'Đóng vòng đầy đủ review-confirmed -> aggregate refresh -> snapshot update cho owner profile.',
    improvements: 'Cần thêm monitor cho cache miss spikes khi traffic tăng.',
    selfSatisfaction: 5,
    skills: [
      {
        reviewer: 'orgAdmin',
        reviewerType: 'manager',
        skill: 'postgresql',
        level: 'senior',
        comment: 'Thiết kế truy vấn aggregate ổn định và giữ đúng transaction boundary.',
      },
      {
        reviewer: 'peerReviewer',
        reviewerType: 'peer',
        skill: 'problem_solving',
        level: 'senior',
        comment: 'Bóc tách nguyên nhân chậm score refresh rõ ràng và có hướng xử lý cụ thể.',
      },
    ],
  },
  {
    key: 'owner-seed-governance',
    sessionStatus: 'completed',
    confirmationAction: 'confirmed',
    requiredPeerReviews: 1,
    overall: 4,
    delivery: 'on_time',
    requirement: 4,
    communication: 4,
    codeQuality: 4,
    proactive: 4,
    strengths: 'Điều phối tốt nhiều luồng seed khác nhau.',
    improvements: 'Cần thêm dữ liệu analytics cho admin sau này.',
    selfSatisfaction: 4,
    skills: [
      {
        reviewer: 'orgAdmin',
        reviewerType: 'manager',
        skill: 'leadership',
        level: 'lead',
        comment: 'Quản lý tốt phạm vi seed đa vai trò.',
      },
      {
        reviewer: 'peerReviewer',
        reviewerType: 'peer',
        skill: 'code_review',
        level: 'middle',
        comment: 'Có checklist review seed command rõ ràng.',
      },
    ],
  },
  {
    key: 'owner-review-dispute-case',
    sessionStatus: 'disputed',
    confirmationAction: 'disputed',
    requiredPeerReviews: 2,
    disputeReason:
      'Manager và peer reviewer chưa thống nhất level vì scope task vừa là QA vừa là profile scoring.',
    overall: 3,
    delivery: 'slightly_late',
    requirement: 3,
    communication: 4,
    codeQuality: 3,
    proactive: 4,
    strengths: 'Có đủ evidence để truy vết tranh chấp và kiểm tra lại rubric.',
    improvements: 'Cần chuẩn hóa rubric scoring trước khi xác nhận review.',
    selfSatisfaction: 3,
    skills: [
      {
        reviewer: 'orgAdmin',
        reviewerType: 'manager',
        skill: 'testing',
        level: 'middle',
        comment: 'Checklist đầy đủ nhưng còn tranh luận về mức độ bao phủ edge cases.',
      },
      {
        reviewer: 'peerReviewer',
        reviewerType: 'peer',
        skill: 'communication',
        level: 'middle',
        comment: 'Trao đổi rõ, nhưng chưa thống nhất kỳ vọng scoring với reviewer.',
      },
      {
        reviewer: 'peerReviewer',
        reviewerType: 'peer',
        skill: 'problem_solving',
        level: 'senior',
        comment: 'Phân tích nguyên nhân dispute tốt và có hướng follow-up.',
      },
    ],
  },
  {
    key: 'orga-review-dispute-detail',
    sessionStatus: 'disputed',
    confirmationAction: 'disputed',
    requiredPeerReviews: 1,
    disputeReason:
      'Reviewer và manager chưa thống nhất về mức assigned level cho nhóm kỹ năng moderation.',
    overall: 3,
    delivery: 'slightly_late',
    requirement: 3,
    communication: 4,
    codeQuality: 3,
    proactive: 3,
    strengths: 'Có tổng hợp đủ evidence để admin kiểm tra nguồn tranh chấp.',
    improvements: 'Cần làm rõ tiêu chí scoring cho reviewer trước khi xác nhận phiên review.',
    selfSatisfaction: 3,
    skills: [
      {
        reviewer: 'orgAdmin',
        reviewerType: 'manager',
        skill: 'testing',
        level: 'middle',
        comment: 'Đã có checklist moderation nhưng tiêu chí đánh giá chưa thống nhất.',
      },
      {
        reviewer: 'peerReviewer',
        reviewerType: 'peer',
        skill: 'communication',
        level: 'middle',
        comment: 'Thông tin dispute đầy đủ nhưng cần chốt chuẩn rating giữa các reviewer.',
      },
    ],
  },
] as const
