import { CanonicalProficiencyLevelCode } from '#modules/skills/public_contracts/proficiency_level_constants'

export const SEED_REVIEW_SESSION_SPECS = [
  {
    key: 'member-org-switch',
    sessionStatus: 'completed',
    confirmationAction: 'confirmed',
    requiredPeerReviews: 1,
    overall: 5,
    delivery: 'on_time',
    requirement: 5,
    communication: 4,
    codeQuality: 5,
    proactive: 4,
    strengths: 'Nắm nhanh mô hình phân quyền đa tổ chức và chủ động đề xuất ma trận kiểm định.',
    improvements: 'Có thể bổ sung giám sát tự động cho các nhánh điều hướng quan trọng.',
    selfSatisfaction: 4,
    skills: [
      {
        reviewer: 'orgAdmin',
        reviewerType: 'manager',
        skill: 'typescript',
        level: CanonicalProficiencyLevelCode.L10,
        comment: 'Xử lý state và typing tốt, không để lọt case role mismatch.',
      },
      {
        reviewer: 'owner',
        reviewerType: 'peer',
        skill: 'communication',
        level: CanonicalProficiencyLevelCode.L7,
        comment: 'Trao đổi rõ các case edge và báo tiến độ đều.',
      },
    ],
  },
  {
    key: 'member-profile-proof',
    sessionStatus: 'completed',
    confirmationAction: 'confirmed',
    requiredPeerReviews: 2,
    overall: 5,
    delivery: 'slightly_late',
    requirement: 5,
    communication: 5,
    codeQuality: 4,
    proactive: 5,
    strengths:
      'Kết nối tốt dữ liệu từ review sang profile snapshot và tổng hợp đúng các proof cần hiển thị.',
    improvements: 'Cần tinh gọn thêm luồng invalidate cache profile.',
    selfSatisfaction: 5,
    skills: [
      {
        reviewer: 'orgAdmin',
        reviewerType: 'manager',
        skill: 'postgresql',
        level: CanonicalProficiencyLevelCode.L7,
        comment: 'Dựng dữ liệu profile aggregate chắc tay, nắm rõ bảng review và snapshot.',
      },
      {
        reviewer: 'peerReviewer',
        reviewerType: 'peer',
        skill: 'problem_solving',
        level: CanonicalProficiencyLevelCode.L10,
        comment: 'Biết lần theo dependency dữ liệu khi UI hiển thị tĩnh.',
      },
      {
        reviewer: 'peerReviewer',
        reviewerType: 'peer',
        skill: 'testing',
        level: CanonicalProficiencyLevelCode.L7,
        comment: 'Có ma trận nghiệm thu đầy đủ cho hồ sơ năng lực và liên kết chia sẻ.',
      },
    ],
  },
  {
    key: 'member-admin-regression',
    sessionStatus: 'completed',
    confirmationAction: 'confirmed',
    requiredPeerReviews: 1,
    overall: 4,
    delivery: 'on_time',
    requirement: 4,
    communication: 5,
    codeQuality: 4,
    proactive: 4,
    strengths: 'Tài liệu nghiệm thu rõ ràng, dễ sử dụng cho các thay đổi điều hướng quản trị.',
    improvements: 'Nên bổ sung tình huống người dùng chưa chọn tổ chức mặc định.',
    selfSatisfaction: 4,
    skills: [
      {
        reviewer: 'orgAdmin',
        reviewerType: 'manager',
        skill: 'testing',
        level: CanonicalProficiencyLevelCode.L7,
        comment: 'Checklist hợp lý và bám sát bug report.',
      },
      {
        reviewer: 'peerReviewer',
        reviewerType: 'peer',
        skill: 'communication',
        level: CanonicalProficiencyLevelCode.L10,
        comment: 'Tài liệu rõ và có giải thích được tình huống back button.',
      },
    ],
  },
  {
    key: 'orgc-marketplace-ranking',
    sessionStatus: 'disputed',
    confirmationAction: 'disputed',
    requiredPeerReviews: 1,
    disputeReason:
      'Chưa thống nhất cách chấm trọng số package adoption metrics giữa reviewer peer và manager.',
    overall: 4,
    delivery: 'slightly_late',
    requirement: 4,
    communication: 4,
    codeQuality: 4,
    proactive: 5,
    strengths:
      'Phân tích tốt độ phù hợp giữa hồ sơ năng lực và yêu cầu dự án, giúp làm rõ logic xếp hạng.',
    improvements: 'Cần thống nhất trọng số giữa chất lượng chứng cứ và kinh nghiệm theo lĩnh vực.',
    selfSatisfaction: 4,
    skills: [
      {
        reviewer: 'peerReviewer',
        reviewerType: 'manager',
        skill: 'postgresql',
        level: CanonicalProficiencyLevelCode.L10,
        comment:
          'Thiết kế truy vấn xếp hạng tốt nhưng cần thêm số liệu để hiệu chỉnh trọng số cuối cùng.',
      },
      {
        reviewer: 'orgAdmin',
        reviewerType: 'peer',
        skill: 'problem_solving',
        level: CanonicalProficiencyLevelCode.L10,
        comment:
          'Giải quyết đúng bài toán ghép nối năng lực, nhưng nhóm đánh giá cần thống nhất thêm tiêu chí.',
      },
    ],
  },
  {
    key: 'owner-profile-scoring-loop',
    sessionStatus: 'completed',
    confirmationAction: 'confirmed',
    requiredPeerReviews: 1,
    overall: 5,
    delivery: 'on_time',
    requirement: 5,
    communication: 5,
    codeQuality: 5,
    proactive: 4,
    strengths:
      'Hoàn thiện đầy đủ vòng xác nhận đánh giá, cập nhật chỉ số tổng hợp và xuất bản hồ sơ năng lực.',
    improvements: 'Cần thêm monitor cho cache miss spikes khi traffic tăng.',
    selfSatisfaction: 5,
    skills: [
      {
        reviewer: 'orgAdmin',
        reviewerType: 'manager',
        skill: 'postgresql',
        level: CanonicalProficiencyLevelCode.L10,
        comment: 'Thiết kế truy vấn aggregate ổn định và giữ đúng transaction boundary.',
      },
      {
        reviewer: 'peerReviewer',
        reviewerType: 'peer',
        skill: 'problem_solving',
        level: CanonicalProficiencyLevelCode.L10,
        comment: 'Bóc tách nguyên nhân chậm score refresh rõ ràng và có hướng xử lý cụ thể.',
      },
    ],
  },
  {
    key: 'owner-data-governance',
    sessionStatus: 'completed',
    confirmationAction: 'confirmed',
    requiredPeerReviews: 1,
    overall: 4,
    delivery: 'on_time',
    requirement: 4,
    communication: 4,
    codeQuality: 4,
    proactive: 4,
    strengths: 'Điều phối tốt nhiều luồng dữ liệu vận hành khác nhau.',
    improvements: 'Cần bổ sung thêm tín hiệu analytics cho admin sau này.',
    selfSatisfaction: 4,
    skills: [
      {
        reviewer: 'orgAdmin',
        reviewerType: 'manager',
        skill: 'leadership',
        level: CanonicalProficiencyLevelCode.L12,
        comment: 'Quản lý tốt phạm vi dữ liệu vận hành đa vai trò.',
      },
      {
        reviewer: 'peerReviewer',
        reviewerType: 'peer',
        skill: 'code_review',
        level: CanonicalProficiencyLevelCode.L7,
        comment: 'Có checklist review dữ liệu quản trị rõ ràng.',
      },
    ],
  },
  {
    key: 'owner-evidence-architecture',
    sessionStatus: 'completed',
    confirmationAction: 'confirmed',
    requiredPeerReviews: 1,
    overall: 5,
    delivery: 'on_time',
    requirement: 5,
    communication: 5,
    codeQuality: 5,
    proactive: 5,
    strengths:
      'Thiết kế được chuỗi chứng cứ xuyên suốt mà vẫn giữ ranh giới rõ giữa dữ liệu vận hành và dữ liệu hồ sơ.',
    improvements: 'Có thể bổ sung thêm sơ đồ lineage tự động cho các lần thay đổi schema.',
    selfSatisfaction: 5,
    skills: [
      {
        reviewer: 'orgAdmin',
        reviewerType: 'manager',
        skill: 'system_design',
        level: CanonicalProficiencyLevelCode.L12,
        comment: 'Kiến trúc rõ ràng, có khả năng mở rộng và truy vết tốt qua nhiều mô-đun.',
      },
      {
        reviewer: 'peerReviewer',
        reviewerType: 'peer',
        skill: 'leadership',
        level: CanonicalProficiencyLevelCode.L10,
        comment: 'Điều phối hiệu quả giữa nhóm sản phẩm, dữ liệu và đảm bảo chất lượng.',
      },
    ],
  },
  {
    key: 'owner-release-governance',
    sessionStatus: 'completed',
    confirmationAction: 'confirmed',
    requiredPeerReviews: 1,
    overall: 5,
    delivery: 'on_time',
    requirement: 5,
    communication: 5,
    codeQuality: 4,
    proactive: 5,
    strengths:
      'Thiết lập cổng phát hành có tiêu chí định lượng, chủ sở hữu rõ ràng và phương án xử lý rủi ro.',
    improvements: 'Nên tự động hóa thêm bước tổng hợp tín hiệu sau phát hành.',
    selfSatisfaction: 5,
    skills: [
      {
        reviewer: 'orgAdmin',
        reviewerType: 'manager',
        skill: 'risk_tracking',
        level: CanonicalProficiencyLevelCode.L10,
        comment: 'Ma trận rủi ro thực tế và liên kết tốt với quyết định go/no-go.',
      },
      {
        reviewer: 'peerReviewer',
        reviewerType: 'peer',
        skill: 'release_management',
        level: CanonicalProficiencyLevelCode.L10,
        comment:
          'Quy trình phát hành cân bằng tốt giữa tốc độ, chất lượng và trách nhiệm giải trình.',
      },
    ],
  },
  {
    key: 'owner-impact-analytics',
    sessionStatus: 'completed',
    confirmationAction: 'confirmed',
    requiredPeerReviews: 1,
    overall: 5,
    delivery: 'on_time',
    requirement: 5,
    communication: 4,
    codeQuality: 5,
    proactive: 4,
    strengths:
      'Chuyển các tín hiệu rời rạc thành bộ chỉ số có định nghĩa, nguồn dữ liệu và ngữ cảnh ra quyết định rõ ràng.',
    improvements: 'Có thể bổ sung dải tin cậy cho các chỉ số có mẫu quan sát nhỏ.',
    selfSatisfaction: 5,
    skills: [
      {
        reviewer: 'orgAdmin',
        reviewerType: 'manager',
        skill: 'postgresql',
        level: CanonicalProficiencyLevelCode.L12,
        comment: 'Mô hình tổng hợp tối ưu, dễ kiểm toán và giữ được nguồn gốc chỉ số.',
      },
      {
        reviewer: 'peerReviewer',
        reviewerType: 'peer',
        skill: 'problem_solving',
        level: CanonicalProficiencyLevelCode.L10,
        comment: 'Chọn đúng chỉ số để phản ánh tác động thay vì chỉ mô tả hoạt động.',
      },
    ],
  },
  {
    key: 'owner-profile-api-contract',
    sessionStatus: 'completed',
    confirmationAction: 'confirmed',
    requiredPeerReviews: 1,
    overall: 5,
    delivery: 'on_time',
    requirement: 5,
    communication: 5,
    codeQuality: 5,
    proactive: 4,
    strengths:
      'Hợp đồng API rõ ràng, bảo vệ dữ liệu riêng tư và có chiến lược tương thích phiên bản thuyết phục.',
    improvements: 'Có thể bổ sung thêm ví dụ tích hợp cho đối tác sử dụng webhook.',
    selfSatisfaction: 5,
    skills: [
      {
        reviewer: 'orgAdmin',
        reviewerType: 'manager',
        skill: 'api_design',
        level: CanonicalProficiencyLevelCode.L12,
        comment: 'Thiết kế API nhất quán, có phân quyền và thông báo deprecation rõ ràng.',
      },
      {
        reviewer: 'peerReviewer',
        reviewerType: 'peer',
        skill: 'documentation',
        level: CanonicalProficiencyLevelCode.L10,
        comment: 'Tài liệu giúp đội tích hợp hiểu nhanh mô hình dữ liệu và các trường hợp lỗi.',
      },
    ],
  },
  {
    key: 'owner-review-dispute-case',
    sessionStatus: 'disputed',
    confirmationAction: 'disputed',
    requiredPeerReviews: 2,
    disputeReason:
      'Quản lý và reviewer ngang hàng chưa thống nhất mức đánh giá vì phạm vi công việc bao gồm cả kiểm định chất lượng lẫn chấm điểm hồ sơ năng lực.',
    overall: 3,
    delivery: 'slightly_late',
    requirement: 3,
    communication: 4,
    codeQuality: 3,
    proactive: 4,
    strengths: 'Có đủ evidence để truy vết tranh chấp và kiểm tra lại rubric.',
    improvements: 'Cần chuẩn hóa rubric scoring trước khi xác nhận review.',
    selfSatisfaction: 3,
    skills: [
      {
        reviewer: 'orgAdmin',
        reviewerType: 'manager',
        skill: 'testing',
        level: CanonicalProficiencyLevelCode.L7,
        comment: 'Checklist đầy đủ nhưng còn tranh luận về mức độ bao phủ edge cases.',
      },
      {
        reviewer: 'peerReviewer',
        reviewerType: 'peer',
        skill: 'communication',
        level: CanonicalProficiencyLevelCode.L7,
        comment: 'Trao đổi rõ, nhưng chưa thống nhất kỳ vọng scoring với reviewer.',
      },
      {
        reviewer: 'peerReviewer',
        reviewerType: 'peer',
        skill: 'problem_solving',
        level: CanonicalProficiencyLevelCode.L10,
        comment: 'Phân tích nguyên nhân dispute tốt và có hướng follow-up.',
      },
    ],
  },
  {
    key: 'orga-review-dispute-detail',
    sessionStatus: 'disputed',
    confirmationAction: 'disputed',
    requiredPeerReviews: 1,
    disputeReason:
      'Reviewer và manager chưa thống nhất về mức assigned level cho nhóm kỹ năng moderation.',
    overall: 3,
    delivery: 'slightly_late',
    requirement: 3,
    communication: 4,
    codeQuality: 3,
    proactive: 3,
    strengths: 'Có tổng hợp đủ evidence để admin kiểm tra nguồn tranh chấp.',
    improvements: 'Cần làm rõ tiêu chí scoring cho reviewer trước khi xác nhận phiên review.',
    selfSatisfaction: 3,
    skills: [
      {
        reviewer: 'orgAdmin',
        reviewerType: 'manager',
        skill: 'testing',
        level: CanonicalProficiencyLevelCode.L7,
        comment: 'Đã có checklist moderation nhưng tiêu chí đánh giá chưa thống nhất.',
      },
      {
        reviewer: 'peerReviewer',
        reviewerType: 'peer',
        skill: 'communication',
        level: CanonicalProficiencyLevelCode.L7,
        comment: 'Thông tin dispute đầy đủ nhưng cần chốt chuẩn rating giữa các reviewer.',
      },
    ],
  },
] as const
