import type { UserKey } from './types.js'

export interface UserSpec {
  username: string
  email: string
  system_role: 'superadmin' | 'registered_user'
  auth_method: 'google' | 'github'
  bio: string
  is_external_contributor: boolean
  rating: number | null
  completedTasks: number
  headline: string
  preferredJobTypes: string[]
  skillProfile: string[]
}

export const PRESERVED_MAIN_USER_EMAILS = ['tranngocduyet31@gmail.com'] as const

export const SEED_USERS_SPECS: Record<UserKey, UserSpec> = {
  owner: {
    username: 'Trần Ngọc Duyệt',
    email: 'tranngocduyet31@gmail.com',
    system_role: 'registered_user',
    auth_method: 'github',
    bio: 'Nhà sáng lập sản phẩm phụ trách chiến lược, vận hành chất lượng và cơ chế đánh giá năng lực dựa trên chứng cứ.',
    is_external_contributor: true,
    rating: 4.9,
    completedTasks: 9,
    headline: 'Product Owner · Nền tảng đánh giá năng lực và cộng tác số',
    preferredJobTypes: ['full-time', 'project-based', 'freelance'],
    skillProfile: ['typescript', 'postgresql', 'system_design', 'leadership', 'planning'],
  },
  superadmin: {
    username: 'Hội đồng Quản trị Suar',
    email: 'td6622i@gre.ac.uk',
    system_role: 'superadmin',
    auth_method: 'google',
    bio: 'Đơn vị quản trị nền tảng chịu trách nhiệm kiểm duyệt đánh giá, xử lý tranh chấp và bảo đảm tính minh bạch của hệ thống.',
    is_external_contributor: false,
    rating: null,
    completedTasks: 0,
    headline: 'Quản trị hệ thống · Kiểm duyệt và giải quyết tranh chấp',
    preferredJobTypes: ['admin'],
    skillProfile: ['risk_tracking', 'system_design', 'communication', 'leadership'],
  },
  member: {
    username: 'Lại Thế Duyệt',
    email: 'duyetlaaithe@gmail.com',
    system_role: 'registered_user',
    auth_method: 'github',
    bio: 'Kỹ sư phần mềm toàn diện, có hồ sơ năng lực được xác thực qua các sản phẩm đã bàn giao và đánh giá đồng cấp.',
    is_external_contributor: true,
    rating: 4.5,
    completedTasks: 3,
    headline: 'Full-stack Engineer · Hệ thống sản phẩm và trải nghiệm người dùng',
    preferredJobTypes: ['contract', 'part-time'],
    skillProfile: ['typescript', 'postgresql', 'testing', 'communication', 'planning'],
  },
  orgAdmin: {
    username: 'Phạm Khánh Linh',
    email: 'linh.pham@team.suar.vn',
    system_role: 'registered_user',
    auth_method: 'google',
    bio: 'Quản lý vận hành sản phẩm, điều phối nguồn lực, tiến độ bàn giao và các cổng kiểm soát chất lượng theo sprint.',
    is_external_contributor: false,
    rating: 4.6,
    completedTasks: 1,
    headline: 'Product Operations Manager · Điều phối chất lượng và nguồn lực',
    preferredJobTypes: ['full-time'],
    skillProfile: ['testing', 'leadership', 'planning', 'risk_tracking'],
  },
  peerReviewer: {
    username: 'Nguyễn Thu Hà',
    email: 'ha.nguyen@team.suar.vn',
    system_role: 'registered_user',
    auth_method: 'google',
    bio: 'Chuyên gia đảm bảo chất lượng, phụ trách hiệu chỉnh rubric và đánh giá đồng cấp dựa trên chứng cứ bàn giao.',
    is_external_contributor: false,
    rating: 4.2,
    completedTasks: 1,
    headline: 'Quality Lead · Hiệu chỉnh tiêu chí và đánh giá đồng cấp',
    preferredJobTypes: ['full-time'],
    skillProfile: ['testing', 'code_review', 'communication', 'problem_solving'],
  },
  orgBOwner: {
    username: 'Trần Minh Quân',
    email: 'quan.tran@openlearning.vn',
    system_role: 'registered_user',
    auth_method: 'google',
    bio: 'Giám đốc chương trình giáo dục, xây dựng khung năng lực số và mô hình hợp tác đào tạo với doanh nghiệp công nghệ.',
    is_external_contributor: false,
    rating: 4.4,
    completedTasks: 1,
    headline: 'Education Program Director · Khung năng lực và học tập số',
    preferredJobTypes: ['full-time'],
    skillProfile: ['documentation', 'planning', 'leadership', 'communication'],
  },
  externalContributorOne: {
    username: 'Hoàng Ngọc Mai',
    email: 'mai.hoang@creativehub.vn',
    system_role: 'registered_user',
    auth_method: 'github',
    bio: 'Chuyên gia nội dung độc lập, xây dựng câu chuyện sản phẩm và hồ sơ năng lực cho các đội ngũ đổi mới sáng tạo.',
    is_external_contributor: true,
    rating: 4.8,
    completedTasks: 6,
    headline: 'Content Strategist · Câu chuyện sản phẩm và thương hiệu số',
    preferredJobTypes: ['freelance', 'contract'],
    skillProfile: ['documentation', 'design_system', 'communication', 'planning'],
  },
  externalContributorTwo: {
    username: 'Phan Hoài Nam',
    email: 'nam.phan@datatrust.vn',
    system_role: 'registered_user',
    auth_method: 'github',
    bio: 'Kỹ sư dữ liệu phụ trách kiểm soát chất lượng, truy vết nguồn gốc và vận hành các pipeline phân tích.',
    is_external_contributor: true,
    rating: 4.3,
    completedTasks: 4,
    headline: 'Data Engineer · Chất lượng dữ liệu và phân tích vận hành',
    preferredJobTypes: ['freelance'],
    skillProfile: ['postgresql', 'system_design', 'problem_solving', 'release_management'],
  },
  securityOwner: {
    username: 'Lê Minh Anh',
    email: 'minh.anh@software-safety.vn',
    system_role: 'registered_user',
    auth_method: 'github',
    bio: 'Lãnh đạo chương trình an toàn phần mềm, kết nối quản trị rủi ro, phản ứng sự cố và bằng chứng kiểm soát trong từng lần phát hành.',
    is_external_contributor: false,
    rating: 4.8,
    completedTasks: 18,
    headline: 'Security Program Lead · An toàn phát hành và quản trị rủi ro',
    preferredJobTypes: ['full-time', 'advisory'],
    skillProfile: ['devops', 'system_design', 'risk_tracking', 'leadership', 'documentation'],
  },
  securityEngineer: {
    username: 'Đỗ Quốc Bảo',
    email: 'bao.do@software-safety.vn',
    system_role: 'registered_user',
    auth_method: 'github',
    bio: 'Kỹ sư bảo mật ứng dụng chuyên phân tích dependency, threat model và thiết kế kiểm soát có thể kiểm chứng trong pipeline.',
    is_external_contributor: true,
    rating: 4.7,
    completedTasks: 14,
    headline: 'Application Security Engineer · Threat modeling và dependency governance',
    preferredJobTypes: ['project-based', 'contract'],
    skillProfile: ['typescript', 'system_design', 'testing', 'problem_solving', 'risk_tracking'],
  },
  productResearcher: {
    username: 'Vũ Thanh Hương',
    email: 'huong.vu@service-design.vn',
    system_role: 'registered_user',
    auth_method: 'google',
    bio: 'Nhà nghiên cứu sản phẩm chuyển phản hồi định tính thành yêu cầu có thể kiểm chứng và ưu tiên cải tiến dựa trên tác động người dùng.',
    is_external_contributor: true,
    rating: 4.6,
    completedTasks: 11,
    headline: 'Product Researcher · Nghiên cứu nhu cầu và chất lượng yêu cầu',
    preferredJobTypes: ['contract', 'project-based'],
    skillProfile: ['postgresql', 'documentation', 'communication', 'problem_solving', 'planning'],
  },
  frontendSpecialist: {
    username: 'Ngô Đức Long',
    email: 'long.ngo@open-product.vn',
    system_role: 'registered_user',
    auth_method: 'github',
    bio: 'Kỹ sư giao diện tập trung vào hiệu năng, accessibility và hệ thống component có bằng chứng kiểm thử trên nhiều thiết bị.',
    is_external_contributor: true,
    rating: 4.7,
    completedTasks: 16,
    headline: 'Frontend Specialist · Accessibility và trải nghiệm sản phẩm',
    preferredJobTypes: ['full-time', 'freelance'],
    skillProfile: ['svelte', 'design_system', 'testing', 'communication', 'planning'],
  },
  backendSpecialist: {
    username: 'Bùi Gia Huy',
    email: 'huy.bui@open-product.vn',
    system_role: 'registered_user',
    auth_method: 'github',
    bio: 'Kỹ sư backend phụ trách API, dữ liệu và khả năng vận hành; ưu tiên contract rõ ràng, review nhỏ và rollback có thể diễn tập.',
    is_external_contributor: true,
    rating: 4.8,
    completedTasks: 21,
    headline: 'Backend Platform Engineer · API, dữ liệu và độ tin cậy',
    preferredJobTypes: ['full-time', 'project-based'],
    skillProfile: ['nodejs', 'postgresql', 'api_design', 'problem_solving', 'release_management'],
  },
  mobileEngineer: {
    username: 'Nguyễn Hải Yến',
    email: 'yen.nguyen@agritech-coop.vn',
    system_role: 'registered_user',
    auth_method: 'github',
    bio: 'Kỹ sư mobile xây dựng trải nghiệm làm việc ngoài hiện trường, chịu được mạng yếu và đồng bộ dữ liệu có thể truy vết.',
    is_external_contributor: true,
    rating: 4.5,
    completedTasks: 12,
    headline: 'Mobile Engineer · Ứng dụng hiện trường và offline-first',
    preferredJobTypes: ['contract', 'full-time'],
    skillProfile: ['typescript', 'api_design', 'testing', 'communication', 'planning'],
  },
  dataAnalyst: {
    username: 'Trần Mai Phương',
    email: 'phuong.tran@evidence-analytics.vn',
    system_role: 'registered_user',
    auth_method: 'google',
    bio: 'Chuyên viên phân tích dữ liệu thiết kế chỉ số có provenance, giải thích giới hạn diễn giải và đối soát tín hiệu trước khi ra quyết định.',
    is_external_contributor: true,
    rating: 4.6,
    completedTasks: 15,
    headline: 'Data Analyst · Chỉ số tác động và provenance',
    preferredJobTypes: ['project-based', 'part-time'],
    skillProfile: ['postgresql', 'testing', 'problem_solving', 'communication', 'documentation'],
  },
  mlEngineer: {
    username: 'Phạm Quốc Việt',
    email: 'viet.pham@evidence-analytics.vn',
    system_role: 'registered_user',
    auth_method: 'github',
    bio: 'Kỹ sư machine learning xây dựng pipeline đánh giá, theo dõi drift và giữ ranh giới rõ giữa gợi ý mô hình với quyết định của con người.',
    is_external_contributor: true,
    rating: 4.7,
    completedTasks: 17,
    headline: 'ML Engineer · Đánh giá mô hình và human-in-the-loop',
    preferredJobTypes: ['full-time', 'advisory'],
    skillProfile: ['postgresql', 'system_design', 'testing', 'problem_solving', 'risk_tracking'],
  },
  devopsEngineer: {
    username: 'Hoàng Anh Tuấn',
    email: 'tuan.hoang@open-product.vn',
    system_role: 'registered_user',
    auth_method: 'github',
    bio: 'Kỹ sư DevOps chuẩn hóa CI/CD, quan sát vận hành và diễn tập phục hồi bằng các tín hiệu có chủ sở hữu và ngưỡng hành động.',
    is_external_contributor: true,
    rating: 4.8,
    completedTasks: 20,
    headline: 'DevOps Engineer · CI/CD, observability và phục hồi',
    preferredJobTypes: ['full-time', 'contract'],
    skillProfile: ['devops', 'system_design', 'testing', 'communication', 'release_management'],
  },
  uxDesigner: {
    username: 'Lý Thu Trang',
    email: 'trang.ly@service-design.vn',
    system_role: 'registered_user',
    auth_method: 'google',
    bio: 'Nhà thiết kế trải nghiệm biến quy trình phức tạp thành hành trình rõ ràng, ưu tiên accessibility và kiểm chứng với người dùng thật.',
    is_external_contributor: true,
    rating: 4.7,
    completedTasks: 13,
    headline: 'UX Designer · Dịch vụ số dễ tiếp cận',
    preferredJobTypes: ['freelance', 'project-based'],
    skillProfile: ['svelte', 'design_system', 'testing', 'communication', 'documentation'],
  },
  qaAutomation: {
    username: 'Đặng Minh Khoa',
    email: 'khoa.dang@open-product.vn',
    system_role: 'registered_user',
    auth_method: 'github',
    bio: 'Kỹ sư QA automation xây dựng chiến lược kiểm thử theo rủi ro, theo dõi flaky test và gắn báo cáo kiểm chứng vào mỗi lần bàn giao.',
    is_external_contributor: true,
    rating: 4.6,
    completedTasks: 19,
    headline: 'QA Automation Engineer · Kiểm thử theo rủi ro',
    preferredJobTypes: ['full-time', 'contract'],
    skillProfile: ['typescript', 'testing', 'code_review', 'problem_solving', 'planning'],
  },
  technicalWriter: {
    username: 'Đinh Ngọc Lan',
    email: 'lan.dinh@knowledge-works.vn',
    system_role: 'registered_user',
    auth_method: 'google',
    bio: 'Chuyên gia tài liệu kỹ thuật chuẩn hóa yêu cầu, decision record và hướng dẫn vận hành để kiến thức có phiên bản và người chịu trách nhiệm.',
    is_external_contributor: true,
    rating: 4.8,
    completedTasks: 18,
    headline: 'Technical Writer · Yêu cầu, runbook và tri thức sản phẩm',
    preferredJobTypes: ['freelance', 'contract'],
    skillProfile: ['typescript', 'api_design', 'documentation', 'communication', 'planning'],
  },
  communityManager: {
    username: 'Tạ Khánh An',
    email: 'an.ta@sustainable-commerce.vn',
    system_role: 'registered_user',
    auth_method: 'google',
    bio: 'Quản lý cộng đồng điều phối creator, đối tác và phản hồi khách hàng theo cam kết công khai, timeline rõ ràng và bằng chứng tác động.',
    is_external_contributor: true,
    rating: 4.5,
    completedTasks: 12,
    headline: 'Community Manager · Creator operations và quan hệ đối tác',
    preferredJobTypes: ['full-time', 'project-based'],
    skillProfile: ['postgresql', 'documentation', 'communication', 'leadership', 'planning'],
  },
  agriProductOwner: {
    username: 'Nguyễn Văn Sơn',
    email: 'son.nguyen@agritech-coop.vn',
    system_role: 'registered_user',
    auth_method: 'google',
    bio: 'Chủ sản phẩm nông nghiệp số kết nối nhu cầu hợp tác xã, vận hành hiện trường và dữ liệu cảm biến thành lộ trình có thể nghiệm thu.',
    is_external_contributor: false,
    rating: 4.6,
    completedTasks: 15,
    headline: 'AgriTech Product Owner · Vận hành hợp tác xã và dữ liệu hiện trường',
    preferredJobTypes: ['full-time'],
    skillProfile: ['postgresql', 'system_design', 'communication', 'leadership', 'planning'],
  },
  civicServiceLead: {
    username: 'Phan Quỳnh Như',
    email: 'nhu.phan@civic-digital.vn',
    system_role: 'registered_user',
    auth_method: 'google',
    bio: 'Lãnh đạo dịch vụ công số phụ trách trải nghiệm người dân, xử lý phản hồi và đo chất lượng phục vụ với quy trình minh bạch.',
    is_external_contributor: false,
    rating: 4.7,
    completedTasks: 17,
    headline: 'Civic Service Lead · Dịch vụ công lấy người dân làm trung tâm',
    preferredJobTypes: ['full-time', 'advisory'],
    skillProfile: ['postgresql', 'design_system', 'communication', 'leadership', 'risk_tracking'],
  },
  commerceOwner: {
    username: 'Lương Gia Bảo',
    email: 'bao.luong@sustainable-commerce.vn',
    system_role: 'registered_user',
    auth_method: 'google',
    bio: 'Chủ sản phẩm thương mại bền vững xây dựng marketplace minh bạch, đo tác động đối tác và bảo vệ trải nghiệm khách hàng.',
    is_external_contributor: false,
    rating: 4.7,
    completedTasks: 16,
    headline: 'Commerce Product Owner · Marketplace và tác động bền vững',
    preferredJobTypes: ['full-time'],
    skillProfile: ['postgresql', 'api_design', 'communication', 'leadership', 'planning'],
  },
}
