import { indexEntities } from '@adonisjs/core'
import { defineConfig } from '@adonisjs/core/app'

export default defineConfig({
  commands: [() => import('@adonisjs/core/commands'), () => import('@adonisjs/lucid/commands')],
  providers: [
    () => import('@adonisjs/core/providers/app_provider'),
    () => import('#composition/events/runtime/events_runtime_provider'),
    () => import('#composition/observability/runtime/observability_runtime_provider'),
    () => import('#composition/observability/platform/logger_provider'),
    () => import('#composition/cache/invalidation-outbox/cache_store_provider'),
    () => import('#composition/admin/audit/audit_log_writer_provider'),
    () => import('#composition/reviews/review-core/review_consumer_ports_provider'),
    () => import('#composition/reviews/review-core/review_action_factory_provider'),
    () => import('#composition/admin/administration/admin_feature_consumer_ports_provider'),
    () => import('#composition/admin/audit/admin_audit_consumer_ports_provider'),
    () => import('#composition/projects/project-membership/project_consumer_ports_provider'),
    () => import('#composition/projects/project-application/project_application_provider'),
    () => import('#composition/organizations/administration/organization_consumer_ports_provider'),
    () => import('#composition/users/user-application/user_application_provider'),
    () => import('#composition/settings/settings-runtime/settings_consumer_ports_provider'),
    () => import('#composition/tasks/task-application/task_application_provider'),
    () => import('#composition/accomplishments/publication/accomplishment_application_provider'),
    () => import('#composition/sprints/sprint-application/sprint_application_provider'),
    () => import('#composition/auth/identity/identity_consumer_ports_provider'),
    () => import('#composition/http/identity/http_identity_queries_provider'),
    () => import('#composition/http/actions/http_feature_actions_provider'),
    () => import('#composition/filtering/filter-runtime/filtering_application_provider'),
    () => import('#composition/taxonomy/taxonomy-governance/taxonomy_governance_application_provider'),
    () => import('#composition/notifications/notification-feed/notification_action_factory_provider'),
    () => import('#composition/marketplace/marketplace-application/marketplace_action_factory_provider'),
    () => import('#composition/skills/skill-catalog/skills_catalog_provider'),
    () => import('#composition/errors/runtime/error_required_organization_provider'),
    () => import('@adonisjs/core/providers/hash_provider'),
    {
      file: () => import('@adonisjs/core/providers/repl_provider'),
      environment: ['repl'],
    },
    () => import('@adonisjs/core/providers/vinejs_provider'),
    () => import('@adonisjs/core/providers/edge_provider'),
    () => import('@adonisjs/session/session_provider'),
    () => import('@adonisjs/vite/vite_provider'),
    () => import('@adonisjs/shield/shield_provider'),
    () => import('@adonisjs/static/static_provider'),
    () => import('@adonisjs/cors/cors_provider'),
    () => import('@adonisjs/lucid/database_provider'),
    () => import('#composition/errors/runtime/error_reporting_lifecycle_provider'),
    () => import('@adonisjs/auth/auth_provider'),
    () => import('@adonisjs/inertia/inertia_provider'),
    () => import('@adonisjs/redis/redis_provider'),
    () => import('@adonisjs/limiter/limiter_provider'),
    () => import('@adonisjs/ally/ally_provider'),
    () => import('@adonisjs/i18n/i18n_provider'),
    () => import('@adonisjs/transmit/transmit_provider'),
    () => import('@adonisjs/lock/lock_provider'),
    () => import('@adonisjs/drive/drive_provider'),
  ],
  preloads: [
    () => import('#start/transmit'),
    () => import('#start/routes'),
    () => import('#start/kernel'),
    () => import('#start/events'),
  ],
  metaFiles: [
    {
      pattern: 'resources/views/**/*.edge',
      reloadServer: false,
    },
    {
      pattern: 'public/**',
      reloadServer: false,
    },
    {
      pattern: 'resources/lang/**/*.{json,yaml,yml}',
      reloadServer: false,
    },
  ],

  hooks: {
    init: [indexEntities()],
    buildStarting: [() => import('@adonisjs/vite/build_hook')],
  },
})
