import { indexEntities } from '@adonisjs/core'
import { defineConfig } from '@adonisjs/core/app'

export default defineConfig({
  commands: [() => import('@adonisjs/core/commands'), () => import('@adonisjs/lucid/commands')],
  providers: [
    () => import('@adonisjs/core/providers/app_provider'),
    () => import('#composition/events_runtime_provider'),
    () => import('#composition/observability_runtime_provider'),
    () => import('#composition/logger_provider'),
    () => import('#composition/cache_store_provider'),
    () => import('#composition/audit_log_writer_provider'),
    () => import('#composition/review_consumer_ports_provider'),
    () => import('#composition/review_action_factory_provider'),
    () => import('#composition/admin_feature_consumer_ports_provider'),
    () => import('#composition/admin_audit_consumer_ports_provider'),
    () => import('#composition/project_consumer_ports_provider'),
    () => import('#composition/project_application_provider'),
    () => import('#composition/organization_consumer_ports_provider'),
    () => import('#composition/user_application_provider'),
    () => import('#composition/settings_consumer_ports_provider'),
    () => import('#composition/task_application_provider'),
    () => import('#composition/sprint_application_provider'),
    () => import('#composition/identity_consumer_ports_provider'),
    () => import('#composition/http_identity_queries_provider'),
    () => import('#composition/http_feature_actions_provider'),
    () => import('#composition/notification_action_factory_provider'),
    () => import('#composition/marketplace_action_factory_provider'),
    () => import('#composition/skills_catalog_provider'),
    () => import('#composition/error_required_organization_provider'),
    () => import('@adonisjs/core/providers/hash_provider'),
    {
      file: () => import('@adonisjs/core/providers/repl_provider'),
      environment: ['repl'],
    },
    () => import('@adonisjs/core/providers/vinejs_provider'),
    () => import('@adonisjs/core/providers/edge_provider'),
    () => import('@adonisjs/session/session_provider'),
    () => import('@adonisjs/vite/vite_provider'),
    () => import('@adonisjs/shield/shield_provider'),
    () => import('@adonisjs/static/static_provider'),
    () => import('@adonisjs/cors/cors_provider'),
    () => import('@adonisjs/lucid/database_provider'),
    () => import('#composition/error_reporting_lifecycle_provider'),
    () => import('@adonisjs/auth/auth_provider'),
    () => import('@adonisjs/inertia/inertia_provider'),
    () => import('@adonisjs/redis/redis_provider'),
    () => import('@adonisjs/limiter/limiter_provider'),
    () => import('@adonisjs/ally/ally_provider'),
    () => import('@adonisjs/i18n/i18n_provider'),
    () => import('@adonisjs/transmit/transmit_provider'),
    () => import('@adonisjs/lock/lock_provider'),
    () => import('@adonisjs/drive/drive_provider'),
  ],
  preloads: [
    () => import('#start/transmit'),
    () => import('#start/routes'),
    () => import('#start/kernel'),
    () => import('#start/events'),
  ],
  metaFiles: [
    {
      pattern: 'resources/views/**/*.edge',
      reloadServer: false,
    },
    {
      pattern: 'public/**',
      reloadServer: false,
    },
    {
      pattern: 'resources/lang/**/*.{json,yaml,yml}',
      reloadServer: false,
    },
  ],

  hooks: {
    init: [indexEntities()],
    buildStarting: [() => import('@adonisjs/vite/build_hook')],
  },
})
