// @ts-check
import { configApp } from '@adonisjs/eslint-config'
import tseslint from 'typescript-eslint'
import importXPlugin from 'eslint-plugin-import-x'
import sveltePlugin from 'eslint-plugin-svelte'
import svelteParser from 'svelte-eslint-parser'
import * as svelteConfig from 'eslint-plugin-svelte'

const generatedAndFixtureIgnores = [
  '**/node_modules/**',
  '.adonisjs/**',
  'public/**',
  'build/**',
  'resources/**',
  'tmp/**',
  'storage/**',
  // Generated by `node ace migration:run`; currently emits `any`-heavy model snapshots.
  'database/schema.ts',
  // Visual fixture wrappers exist only to mount isolated UI atoms in tests/storybook-like contexts.
  'inertia/tests/ui/testWrappers/**/*.fixture.svelte',
]

export default configApp(
  // Keep these ignores inside configApp so Adonis base config sees same generated paths.
  {
    ignores: generatedAndFixtureIgnores,
  },

  // Flat config still needs a standalone global ignore entry for traversal-level excludes.
  {
    ignores: generatedAndFixtureIgnores,
  },

  // Config chính cho toàn bộ TypeScript (backend + root level)
  {
    files: ['**/*.ts', '**/*.d.ts'],
    languageOptions: {
      parserOptions: {
        project: ['./tsconfig.json', './tsconfig.eslint.json'],
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      'import-x': importXPlugin,
    },

    rules: {
      // 🚨 CỨNG RẮN - Không dùng any/unknown
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-non-null-assertion': 'error',
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],

      // 🚨 UNSAFE OPERATIONS - Nâng lên ERROR để bắt buộc dùng đúng type
      '@typescript-eslint/no-unsafe-assignment': 'error',
      '@typescript-eslint/no-unsafe-member-access': 'error',
      '@typescript-eslint/no-unsafe-call': 'error',
      '@typescript-eslint/no-unsafe-return': 'error',
      '@typescript-eslint/no-unsafe-argument': 'error',

      // 🚨 PROMISE HANDLING - Quan trọng cho stability
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
      '@typescript-eslint/await-thenable': 'error',
      '@typescript-eslint/require-await': 'error',

      // 🚨 STRICT TYPE ASSERTIONS
      '@typescript-eslint/consistent-type-assertions': [
        'error',
        {
          assertionStyle: 'as',
          objectLiteralTypeAssertions: 'never',
        },
      ],

      // 🚨 EMPTY TYPES - Không cho phép interface rỗng
      '@typescript-eslint/no-empty-object-type': 'error',

      // 🚨 BASE TO STRING - Đảm bảo objects có đúng string representation
      '@typescript-eslint/no-base-to-string': 'error',

      // 🚨 RESTRICT TEMPLATE EXPRESSIONS - Kiểm soát chặt template strings
      // Cho phép number và boolean vì đây là use case an toàn và phổ biến
      '@typescript-eslint/restrict-template-expressions': [
        'error',
        {
          allowNumber: true,
          allowBoolean: true,
          allowNullish: false,
          allowAny: false,
        },
      ],

      // ⚠️ DEPRECATED APIs - Warning để có thời gian migrate
      '@typescript-eslint/no-deprecated': 'warn',

      // 🚨 PROBE RULE - Disable because of crash in current version
      '@typescript-eslint/no-useless-default-assignment': 'off',

      // ✅ VÔ HIỆU HÓA - Không cần thiết
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      'prettier/prettier': 'off',
      'no-console': ['warn', { allow: ['warn', 'error'] }],

      // ✅ THÊM - Rules hữu ích cho refactor
      '@typescript-eslint/consistent-type-imports': 'error',
      '@typescript-eslint/unbound-method': 'error',
      '@typescript-eslint/no-unnecessary-condition': 'error',
      '@typescript-eslint/no-unnecessary-type-assertion': 'error',
      'prefer-const': 'error',
      'no-shadow': 'off',
      '@typescript-eslint/no-shadow': 'error',
      '@typescript-eslint/switch-exhaustiveness-check': 'error',
      '@typescript-eslint/naming-convention': [
        'error',
        {
          selector: 'variable',
          format: ['camelCase', 'UPPER_CASE', 'PascalCase'],
          leadingUnderscore: 'allow',
        },
        {
          selector: 'function',
          format: ['camelCase', 'PascalCase'],
          leadingUnderscore: 'allow',
        },
        {
          selector: 'typeLike',
          format: ['PascalCase'],
        },
        {
          selector: 'enumMember',
          format: ['UPPER_CASE', 'PascalCase'],
        },
      ],
      'import-x/order': [
        'error',
        {
          groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index'],
          'newlines-between': 'always',
          alphabetize: {
            order: 'asc',
            caseInsensitive: true,
          },
          pathGroups: [
            { pattern: '#**', group: 'internal', position: 'before' },
            { pattern: '@/**', group: 'internal', position: 'before' },
            { pattern: '$lib/**', group: 'internal', position: 'before' },
            { pattern: '~/**', group: 'internal', position: 'before' },
          ],
          pathGroupsExcludedImportTypes: ['builtin'],
        },
      ],
      'import-x/no-duplicates': 'error',
      // Boundary follow-up: add no-restricted-imports patterns here when the
      // module docs are approved, especially to block cross-module */support/*
      // imports such as app/actions/organizations -> app/actions/tasks/support.
      'import-x/no-cycle': [
        'warn',
        {
          ignoreExternal: true,
          maxDepth: 1,
        },
      ],
    },
  },

  // Override cho inertia TypeScript — dùng inertia/tsconfig.json thay vì root
  {
    files: ['inertia/**/*.ts', 'inertia/types/**/*.d.ts', '.storybook/**/*.ts'],
    languageOptions: {
      parserOptions: {
        project: ['./inertia/tsconfig.lint.json', './tsconfig.inertia.json'],
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },

  {
    files: ['inertia/apps/**/tests/**/*.ts'],
    rules: {
      '@adonisjs/no-backend-import-in-frontend': [
        'error',
        {
          allowed: [
            '../../../../../../tests/shared/auth_session_cache.js',
            '../../../../../../tests/shared/auth_token_cache.js',
          ],
        },
      ],
    },
  },

  // 📁 OVERRIDE cho folder config/ - AdonisJS module augmentation pattern
  {
    files: ['config/**/*.ts'],
    rules: {
      // AdonisJS sử dụng empty interfaces để mở rộng types (module augmentation)
      '@typescript-eslint/no-empty-object-type': 'off',
    },
  },

  {
    files: ['types/**/*.d.ts'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },

  {
    files: ['scripts/**/*.mjs'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      parserOptions: {
        project: false,
      },
    },
    rules: {
      'no-console': ['warn', { allow: ['warn', 'error', 'log'] }],
    },
  },

  {
    files: ['*.js', '*.cjs', '*.mjs'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      parserOptions: {
        project: false,
      },
    },
  },

  // 📁 OVERRIDE cho BACKEND - Relax một số rules phức tạp
  {
    files: ['app/**/*.ts', 'bin/**/*.ts', 'start/**/*.ts'],
    rules: {
      // Allow enum comparison với string (common pattern in AdonisJS)
      '@typescript-eslint/no-unsafe-enum-comparison': 'warn',
      // Relax catch variable type - có thể dùng Error thay vì unknown
      '@typescript-eslint/use-unknown-in-catch-callback-variable': 'error',
      // Allow String() conversion khi cần stringify
      '@typescript-eslint/no-unnecessary-type-conversion': 'warn',
      // Deprecated warnings OK cho backend
      '@typescript-eslint/no-deprecated': 'warn',
    },
  },

  {
    files: ['tests/**/*.ts', 'app/modules/**/tests/**/*.ts', 'inertia/tests/**/*.ts'],
    languageOptions: {
      parserOptions: {
        project: [
          './tsconfig.json',
          './tsconfig.eslint.json',
          './inertia/tsconfig.lint.json',
          './tsconfig.inertia.json',
        ],
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      'no-console': 'off',
    },
  },

  // 📁 OVERRIDE cho .svelte files - Svelte 5 specific với strict checking
  // ✅ Thu hẹp glob từ `**/*.svelte` xuống `inertia/**/*.svelte` — quan trọng!
  // Glob `**/*.svelte` quá rộng, có thể match file trong node_modules nếu
  // global ignores chưa được xử lý trước. `inertia/**` chính xác và an toàn hơn.
  {
    files: ['inertia/**/*.svelte'],
    languageOptions: {
      parser: svelteParser,
      parserOptions: {
        parser: tseslint.parser,
        extraFileExtensions: ['.svelte'],
        // ✅ FIX CHÍNH — khai báo đúng tsconfig cho svelte files
        // Nếu không có dòng này, ESLint kế thừa project từ block cha phía trên
        // (cái block đang trỏ vào ./tsconfig.json), và root tsconfig không include
        // các file .svelte nên TypeScript từ chối parse → gây ra hàng trăm lỗi
        // "TSConfig does not include this file"
        project: ['./inertia/tsconfig.lint.json'],
        tsconfigRootDir: import.meta.dirname,
        svelteFeatures: {
          experimentalGenerics: true, // Svelte 5 generics
        },
      },
    },
    plugins: {
      svelte: sveltePlugin,
    },
    rules: {
      // Svelte plugin recommended rules
      ...svelteConfig.configs.recommended.rules,

      // Svelte-specific rules - STRICT
      'svelte/no-at-html-tags': 'error',
      'svelte/no-dom-manipulating': 'error',
      'svelte/no-dupe-else-if-blocks': 'error',
      'svelte/no-dupe-style-properties': 'error',
      'svelte/no-dupe-use-directives': 'error',
      'svelte/no-dynamic-slot-name': 'error',
      'svelte/no-export-load-in-svelte-module-in-kit-pages': 'error',
      'svelte/no-inner-declarations': 'error',
      'svelte/no-not-function-handler': 'error',
      'svelte/no-object-in-text-mustaches': 'error',
      'svelte/no-reactive-reassign': 'error',
      'svelte/no-shorthand-style-property-overrides': 'error',
      'svelte/no-store-async': 'error',
      'svelte/no-unknown-style-directive-property': 'error',
      'svelte/no-unused-class-name': 'off',
      'svelte/no-unused-svelte-ignore': 'error',
      'svelte/no-useless-mustaches': 'warn',
      'svelte/require-store-callbacks-use-set-param': 'error',
      'svelte/require-store-reactive-access': 'error',
      'svelte/valid-compile': 'error',

      // TypeScript rules for Svelte - KEEP STRICT
      '@typescript-eslint/no-unsafe-assignment': 'error',
      '@typescript-eslint/no-unsafe-member-access': 'error',
      '@typescript-eslint/no-unsafe-call': 'error',
      '@typescript-eslint/no-unsafe-return': 'error',
      '@typescript-eslint/no-unsafe-argument': 'error',
      '@typescript-eslint/no-explicit-any': 'error',

      // Svelte 5 runes - allow let for props
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_|^\\$props$|^\\$state$|^\\$derived$|^\\$effect$',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
    },
  },

  {
    files: [
      'inertia/components/confirm_dialog.svelte',
      'inertia/components/ui/dialog.svelte',
      'inertia/components/ui/alert_dialog.svelte',
      'inertia/components/ui/sheet.svelte',
      'inertia/components/ui/select.svelte',
      'inertia/components/ui/skill_search_combobox.svelte',
      'inertia/components/ui/checkbox.svelte',
      'inertia/components/ui/collapsible.svelte',
      'inertia/components/ui/dropdown_menu.svelte',
      'inertia/components/ui/radio_group.svelte',
      'inertia/components/ui/switch.svelte',
      'inertia/components/ui/input.svelte',
      'inertia/components/ui/popover.svelte',
      'inertia/components/ui/command_input.svelte',
      'inertia/components/ui/textarea.svelte',
      'inertia/components/ui/level_range_selector.svelte',
      'inertia/components/layout/control_sidebar.svelte',
      'inertia/pages/tasks/components/modals/task_status_management_dialogs.svelte',
      'inertia/tests/component/ui/checkbox.test.svelte',
      'inertia/tests/component/ui/dialog.test.svelte',
      'inertia/tests/component/ui/input.test.svelte',
      'inertia/tests/component/ui/select.test.svelte',
      'inertia/tests/component/ui/switch.test.svelte',
    ],
    rules: {
      'prefer-const': 'off',
    },
  },

  // 📁 OVERRIDE cho .svelte.ts files - Svelte 5 module context
  {
    files: ['inertia/**/*.svelte.ts', 'inertia/**/*.svelte.js'],
    languageOptions: {
      parserOptions: {
        project: ['./inertia/tsconfig.json', './tsconfig.json'],
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // These are module context files, apply normal TS rules
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-unsafe-assignment': 'error',
      '@typescript-eslint/no-unsafe-member-access': 'error',
      '@typescript-eslint/no-unsafe-call': 'error',
      '@typescript-eslint/no-unsafe-return': 'error',
      '@typescript-eslint/no-unsafe-argument': 'error',
    },
  }
)
