import type { GeneratedProjectTaskSeedConfig, ProjectKey } from '../types.js'

export const GENERATED_PROJECT_TASK_CONFIG: Record<ProjectKey, GeneratedProjectTaskSeedConfig> = {
  orgAPlatform: {
    organization: 'orgA',
    targetTaskCount: 8,
    creators: ['owner', 'orgAdmin'],
    assignees: ['owner', 'member', 'orgAdmin', 'peerReviewer'],
    titlePrefix: 'Năng lực số và hồ sơ chứng cứ',
    businessDomain: 'saas',
    problemCategories: ['new_capability', 'maintainability', 'automation', 'ux_improvement'],
    techStack: ['AdonisJS', 'Svelte', 'PostgreSQL', 'Redis'],
    requiredSkills: ['typescript', 'api_design', 'postgresql', 'communication', 'planning'],
  },
  orgAOperations: {
    organization: 'orgA',
    targetTaskCount: 4,
    creators: ['owner', 'orgAdmin'],
    assignees: ['owner', 'member', 'orgAdmin'],
    titlePrefix: 'Quản trị chất lượng và tranh chấp',
    businessDomain: 'internal_tooling',
    problemCategories: ['maintainability', 'automation', 'new_capability', 'ux_improvement'],
    techStack: ['AdonisJS', 'PostgreSQL', 'Redis'],
    requiredSkills: ['testing', 'code_review', 'communication', 'risk_tracking', 'postgresql'],
  },
  orgADesignSystem: {
    organization: 'orgA',
    targetTaskCount: 3,
    creators: ['owner', 'orgAdmin'],
    assignees: ['orgAdmin', 'member'],
    titlePrefix: 'Thành phần trải nghiệm Suar',
    businessDomain: 'saas',
    problemCategories: ['ux_improvement', 'new_capability', 'maintainability'],
    techStack: ['Svelte', 'TypeScript', 'Design System'],
    requiredSkills: ['svelte', 'design_system', 'communication', 'documentation'],
  },
  orgAAnalytics: {
    organization: 'orgA',
    targetTaskCount: 5,
    creators: ['owner', 'orgAdmin'],
    assignees: ['owner', 'peerReviewer', 'orgAdmin'],
    titlePrefix: 'Chỉ số chất lượng sản phẩm',
    businessDomain: 'saas',
    problemCategories: ['automation', 'new_capability', 'performance', 'maintainability'],
    techStack: ['PostgreSQL', 'Redis', 'AdonisJS', 'Charts'],
    requiredSkills: ['postgresql', 'system_design', 'problem_solving', 'risk_tracking'],
  },
  orgBKnowledgeBase: {
    organization: 'orgB',
    targetTaskCount: 10,
    creators: ['orgBOwner'],
    assignees: ['owner', 'member', 'orgBOwner'],
    titlePrefix: 'Thư viện năng lực số',
    businessDomain: 'edtech',
    problemCategories: ['maintainability', 'automation', 'ux_improvement', 'new_capability'],
    techStack: ['Documentation', 'Svelte', 'PostgreSQL'],
    requiredSkills: ['svelte', 'design_system', 'communication', 'documentation'],
  },
  orgBCurriculumOps: {
    organization: 'orgB',
    targetTaskCount: 10,
    creators: ['orgBOwner'],
    assignees: ['owner', 'member', 'orgBOwner'],
    titlePrefix: 'Chương trình học theo dự án',
    businessDomain: 'edtech',
    problemCategories: ['automation', 'maintainability', 'new_capability', 'ux_improvement'],
    techStack: ['Documentation', 'PostgreSQL', 'Svelte'],
    requiredSkills: ['postgresql', 'system_design', 'communication', 'documentation'],
  },
  orgCMarketplaceLab: {
    organization: 'orgC',
    targetTaskCount: 20,
    creators: ['peerReviewer', 'orgAdmin'],
    assignees: ['peerReviewer', 'orgAdmin'],
    titlePrefix: 'Dự án sáng tạo cộng đồng',
    businessDomain: 'saas',
    problemCategories: ['automation', 'new_capability', 'maintainability', 'performance'],
    techStack: ['AdonisJS', 'Charts', 'PostgreSQL', 'Redis'],
    requiredSkills: ['postgresql', 'api_design', 'communication', 'planning'],
  },
  orgDTalentShowcase: {
    organization: 'orgD',
    targetTaskCount: 20,
    creators: ['externalContributorOne'],
    assignees: ['externalContributorOne', 'externalContributorTwo'],
    titlePrefix: 'Hồ sơ và cơ hội chuyên gia',
    businessDomain: 'saas',
    problemCategories: ['new_capability', 'ux_improvement', 'automation', 'technical_debt'],
    techStack: ['Svelte', 'TypeScript', 'PostgreSQL'],
    requiredSkills: ['svelte', 'design_system', 'communication', 'documentation'],
  },
  orgEDataOps: {
    organization: 'orgE',
    targetTaskCount: 10,
    creators: ['externalContributorTwo', 'orgAdmin'],
    assignees: ['member', 'orgAdmin', 'externalContributorTwo'],
    titlePrefix: 'Quy trình chất lượng dữ liệu',
    businessDomain: 'data_platform',
    problemCategories: ['automation', 'new_capability', 'performance', 'maintainability'],
    techStack: ['PostgreSQL', 'Redis', 'AdonisJS', 'TypeScript'],
    requiredSkills: ['postgresql', 'system_design', 'problem_solving', 'risk_tracking'],
  },
  orgEInsightEngine: {
    organization: 'orgE',
    targetTaskCount: 10,
    creators: ['externalContributorTwo', 'orgAdmin'],
    assignees: ['member', 'orgAdmin', 'externalContributorTwo'],
    titlePrefix: 'Phân tích tác động chương trình',
    businessDomain: 'data_platform',
    problemCategories: ['automation', 'new_capability', 'performance', 'maintainability'],
    techStack: ['PostgreSQL', 'Redis', 'AdonisJS', 'TypeScript'],
    requiredSkills: ['postgresql', 'api_design', 'communication', 'release_management'],
  },
  orgFReviewOps: {
    organization: 'orgF',
    targetTaskCount: 13,
    creators: ['backendSpecialist', 'qaAutomation'],
    assignees: [
      'qaAutomation',
      'backendSpecialist',
      'technicalWriter',
      'frontendSpecialist',
      'securityEngineer',
    ],
    titlePrefix: 'Chất lượng pull request dựa trên bằng chứng',
    businessDomain: 'saas',
    problemCategories: ['maintainability', 'automation', 'performance', 'new_capability'],
    techStack: ['GitHub', 'TypeScript', 'PostgreSQL', 'CI'],
    requiredSkills: ['typescript', 'code_review', 'communication', 'planning'],
  },
  orgFDeveloperExperience: {
    organization: 'orgF',
    targetTaskCount: 13,
    creators: ['frontendSpecialist', 'productResearcher'],
    assignees: [
      'frontendSpecialist',
      'productResearcher',
      'backendSpecialist',
      'qaAutomation',
      'technicalWriter',
    ],
    titlePrefix: 'Trải nghiệm nhà phát triển và contributor',
    businessDomain: 'internal_tooling',
    problemCategories: ['ux_improvement', 'maintainability', 'automation', 'new_capability'],
    techStack: ['Svelte', 'TypeScript', 'Documentation', 'CI'],
    requiredSkills: ['typescript', 'design_system', 'communication', 'documentation'],
  },
  orgFReleaseReliability: {
    organization: 'orgF',
    targetTaskCount: 13,
    creators: ['devopsEngineer', 'qaAutomation'],
    assignees: [
      'devopsEngineer',
      'qaAutomation',
      'securityEngineer',
      'backendSpecialist',
      'technicalWriter',
    ],
    titlePrefix: 'Phát hành tin cậy và khả năng phục hồi',
    businessDomain: 'internal_tooling',
    problemCategories: ['automation', 'performance', 'compliance', 'maintainability'],
    techStack: ['CI/CD', 'PostgreSQL', 'Redis', 'Observability'],
    requiredSkills: ['devops', 'testing', 'communication', 'release_management'],
  },
  orgGCitizenPortal: {
    organization: 'orgG',
    targetTaskCount: 13,
    creators: ['civicServiceLead', 'uxDesigner'],
    assignees: [
      'civicServiceLead',
      'uxDesigner',
      'technicalWriter',
      'qaAutomation',
      'productResearcher',
    ],
    titlePrefix: 'Hành trình dịch vụ công lấy người dân làm trung tâm',
    businessDomain: 'internal_tooling',
    problemCategories: ['ux_improvement', 'new_capability', 'maintainability', 'automation'],
    techStack: ['Svelte', 'TypeScript', 'PostgreSQL', 'Design System'],
    requiredSkills: ['svelte', 'design_system', 'communication', 'documentation'],
  },
  orgGComplaintResolution: {
    organization: 'orgG',
    targetTaskCount: 13,
    creators: ['civicServiceLead', 'productResearcher'],
    assignees: [
      'communityManager',
      'productResearcher',
      'civicServiceLead',
      'dataAnalyst',
      'technicalWriter',
    ],
    titlePrefix: 'Điều phối phản hồi và khắc phục dịch vụ',
    businessDomain: 'internal_tooling',
    problemCategories: ['automation', 'compliance', 'maintainability', 'ux_improvement'],
    techStack: ['AdonisJS', 'PostgreSQL', 'Analytics', 'Documentation'],
    requiredSkills: ['postgresql', 'system_design', 'communication', 'risk_tracking'],
  },
  orgGAccessibilityAnalytics: {
    organization: 'orgG',
    targetTaskCount: 13,
    creators: ['dataAnalyst', 'uxDesigner'],
    assignees: [
      'dataAnalyst',
      'uxDesigner',
      'qaAutomation',
      'productResearcher',
      'civicServiceLead',
    ],
    titlePrefix: 'Chỉ số accessibility và chất lượng hành trình',
    businessDomain: 'data_platform',
    problemCategories: ['automation', 'ux_improvement', 'performance', 'maintainability'],
    techStack: ['PostgreSQL', 'Charts', 'Svelte', 'Accessibility'],
    requiredSkills: ['postgresql', 'testing', 'problem_solving', 'documentation'],
  },
  orgHFarmOperations: {
    organization: 'orgH',
    targetTaskCount: 13,
    creators: ['agriProductOwner', 'productResearcher'],
    assignees: [
      'agriProductOwner',
      'productResearcher',
      'mobileEngineer',
      'dataAnalyst',
      'technicalWriter',
    ],
    titlePrefix: 'Điều phối mùa vụ và công việc hiện trường',
    businessDomain: 'data_platform',
    problemCategories: ['new_capability', 'automation', 'ux_improvement', 'maintainability'],
    techStack: ['Mobile', 'PostgreSQL', 'Svelte', 'Offline Sync'],
    requiredSkills: ['postgresql', 'system_design', 'communication', 'planning'],
  },
  orgHIotFieldMonitoring: {
    organization: 'orgH',
    targetTaskCount: 13,
    creators: ['mobileEngineer', 'devopsEngineer'],
    assignees: [
      'mobileEngineer',
      'devopsEngineer',
      'dataAnalyst',
      'agriProductOwner',
      'productResearcher',
    ],
    titlePrefix: 'Giám sát cảm biến và vận hành offline-first',
    businessDomain: 'data_platform',
    problemCategories: ['performance', 'automation', 'new_capability', 'maintainability'],
    techStack: ['IoT', 'Mobile', 'PostgreSQL', 'Observability'],
    requiredSkills: ['typescript', 'testing', 'problem_solving', 'release_management'],
  },
  orgHKnowledgeHub: {
    organization: 'orgH',
    targetTaskCount: 13,
    creators: ['agriProductOwner', 'technicalWriter'],
    assignees: [
      'technicalWriter',
      'agriProductOwner',
      'productResearcher',
      'mobileEngineer',
      'dataAnalyst',
    ],
    titlePrefix: 'Tri thức thực hành và học tập theo mùa vụ',
    businessDomain: 'edtech',
    problemCategories: ['maintainability', 'new_capability', 'automation', 'ux_improvement'],
    techStack: ['Documentation', 'Svelte', 'PostgreSQL', 'Mobile'],
    requiredSkills: ['svelte', 'design_system', 'communication', 'documentation'],
  },
  orgISecureDelivery: {
    organization: 'orgI',
    targetTaskCount: 13,
    creators: ['securityOwner', 'securityEngineer'],
    assignees: [
      'securityEngineer',
      'securityOwner',
      'backendSpecialist',
      'qaAutomation',
      'devopsEngineer',
    ],
    titlePrefix: 'Secure delivery và bằng chứng kiểm soát',
    businessDomain: 'security',
    problemCategories: ['security', 'compliance', 'automation', 'maintainability'],
    techStack: ['TypeScript', 'PostgreSQL', 'CI/CD', 'Audit'],
    requiredSkills: ['typescript', 'system_design', 'problem_solving', 'risk_tracking'],
  },
  orgIIncidentReadiness: {
    organization: 'orgI',
    targetTaskCount: 13,
    creators: ['securityOwner', 'devopsEngineer'],
    assignees: [
      'securityOwner',
      'devopsEngineer',
      'qaAutomation',
      'securityEngineer',
      'technicalWriter',
    ],
    titlePrefix: 'Sẵn sàng sự cố và phục hồi dịch vụ',
    businessDomain: 'security',
    problemCategories: ['security', 'performance', 'automation', 'compliance'],
    techStack: ['Observability', 'Redis', 'PostgreSQL', 'Runbooks'],
    requiredSkills: ['devops', 'testing', 'communication', 'risk_tracking'],
  },
  orgIDependencyGovernance: {
    organization: 'orgI',
    targetTaskCount: 13,
    creators: ['securityEngineer', 'backendSpecialist'],
    assignees: [
      'mlEngineer',
      'securityEngineer',
      'backendSpecialist',
      'devopsEngineer',
      'securityOwner',
    ],
    titlePrefix: 'Dependency provenance và supply-chain governance',
    businessDomain: 'security',
    problemCategories: ['security', 'compliance', 'maintainability', 'automation'],
    techStack: ['SBOM', 'TypeScript', 'CI/CD', 'PostgreSQL'],
    requiredSkills: ['typescript', 'code_review', 'problem_solving', 'risk_tracking'],
  },
  orgJSustainableCommerce: {
    organization: 'orgJ',
    targetTaskCount: 13,
    creators: ['commerceOwner', 'communityManager'],
    assignees: [
      'commerceOwner',
      'communityManager',
      'uxDesigner',
      'frontendSpecialist',
      'dataAnalyst',
    ],
    titlePrefix: 'Marketplace bền vững và minh bạch đối tác',
    businessDomain: 'saas',
    problemCategories: ['new_capability', 'ux_improvement', 'compliance', 'automation'],
    techStack: ['Svelte', 'AdonisJS', 'PostgreSQL', 'Analytics'],
    requiredSkills: ['svelte', 'api_design', 'communication', 'planning'],
  },
  orgJCustomerInsight: {
    organization: 'orgJ',
    targetTaskCount: 13,
    creators: ['productResearcher', 'dataAnalyst'],
    assignees: [
      'productResearcher',
      'dataAnalyst',
      'uxDesigner',
      'communityManager',
      'commerceOwner',
    ],
    titlePrefix: 'Nghiên cứu khách hàng và quyết định có căn cứ',
    businessDomain: 'data_platform',
    problemCategories: ['automation', 'ux_improvement', 'new_capability', 'maintainability'],
    techStack: ['PostgreSQL', 'Analytics', 'Svelte', 'Research Repository'],
    requiredSkills: ['postgresql', 'testing', 'communication', 'documentation'],
  },
  orgJCreatorMarketplace: {
    organization: 'orgJ',
    targetTaskCount: 13,
    creators: ['communityManager', 'commerceOwner'],
    assignees: [
      'uxDesigner',
      'communityManager',
      'technicalWriter',
      'productResearcher',
      'commerceOwner',
    ],
    titlePrefix: 'Creator marketplace và cộng tác có bằng chứng',
    businessDomain: 'saas',
    problemCategories: ['new_capability', 'automation', 'ux_improvement', 'compliance'],
    techStack: ['Svelte', 'PostgreSQL', 'Marketplace', 'Content'],
    requiredSkills: ['svelte', 'design_system', 'communication', 'planning'],
  },
}
