import type { ProjectKey } from '../types.js'

/**
 * The dense demo pack is intentionally an explicit editorial catalogue.  The
 * generator below only supplies deterministic operational metadata; titles,
 * stories and evidence remain project-specific and reviewable here.
 */
export const PROJECT_NARRATIVE_TITLES: Record<ProjectKey, readonly string[]> = {
  orgAPlatform: [],
  orgAOperations: [],
  orgADesignSystem: [
    'Chuẩn hóa thẻ chứng cứ năng lực trên mobile',
    'Hoàn thiện trạng thái rỗng cho bảng đánh giá',
  ],
  orgAAnalytics: [
    'Đối soát tỷ lệ bàn giao đúng hạn theo quý',
    'Cảnh báo sai lệch điểm tự đánh giá',
    'Bảng nhiệt kỹ năng còn thiếu chứng cứ',
  ],
  orgBKnowledgeBase: [
    'Biên soạn playbook phỏng vấn dựa trên năng lực',
    'Chuẩn hóa rubric nghề Frontend Engineer',
    'Xây thư viện mẫu chứng cứ cho học viên',
    'Rà soát thuật ngữ kỹ năng song ngữ',
    'Thiết kế lộ trình học từ khoảng trống năng lực',
    'Xuất bản hướng dẫn phản hồi có tính xây dựng',
    'Kiểm định nguồn tài liệu về quản trị dữ liệu',
    'Gắn phiên bản rubric vào từng bài thực hành',
    'Thiết lập quy trình duyệt bài viết chuyên gia',
  ],
  orgBCurriculumOps: [
    'Thiết kế sprint mô phỏng phát hành sản phẩm',
    'Xây bài tập điều tra sự cố API',
    'Tổ chức phiên review chéo giữa các nhóm học viên',
    'Đo độ khó bài tập bằng dữ liệu hoàn thành',
    'Chuẩn hóa checklist bàn giao capstone',
    'Thiết kế bài học quản lý rủi ro dự án',
    'Thử nghiệm mentoring clinic hằng tuần',
    'Đồng bộ chuẩn đầu ra với rubric doanh nghiệp',
    'Tổng kết cohort bằng hồ sơ năng lực công khai',
  ],
  orgCMarketplaceLab: [
    'Khảo sát nhu cầu chuyên gia cho chiến dịch xanh',
    'Thiết kế brief nhận diện lễ hội sáng tạo',
    'Mở tuyển cộng tác viên dựng phim ngắn',
    'Chấm shortlist bằng bằng chứng năng lực',
    'Tổ chức phiên hỏi đáp công khai với ứng viên',
    'Xây landing page giới thiệu dự án cộng đồng',
    'Kiểm thử trải nghiệm ứng tuyển trên điện thoại',
    'Chuẩn hóa tiêu chí lựa chọn nhiếp ảnh gia',
    'Lập lịch bàn giao nội dung đa kênh',
    'Theo dõi ngân sách cộng tác viên theo mốc',
    'Thử nghiệm ghép ứng viên theo kỹ năng liền kề',
    'Rà soát quyền sử dụng tài sản sáng tạo',
    'Thiết kế dashboard sức khỏe chiến dịch',
    'Thu thập phản hồi đối tác sau nghiệm thu',
    'Xử lý hồ sơ ứng viên thiếu portfolio',
    'Xây bộ câu hỏi phỏng vấn content strategist',
    'Công bố minh bạch kết quả tuyển chọn',
    'Tổng kết tác động truyền thông của chiến dịch',
    'Lưu trữ bộ chứng cứ bàn giao cộng đồng',
  ],
  orgDTalentShowcase: [
    'Kể câu chuyện chuyển nghề của kỹ sư dữ liệu',
    'Thiết kế case study ra mắt sản phẩm giáo dục',
    'Biên tập portfolio cho chuyên gia UX độc lập',
    'Xác minh số liệu tác động trong hồ sơ năng lực',
    'Dựng video giới thiệu đội ngũ sáng lập',
    'Chuẩn hóa ảnh đại diện và bộ nhận diện cá nhân',
    'Viết bài phân tích một quyết định kiến trúc',
    'Tạo timeline chứng cứ cho dự án đã hoàn thành',
    'Thiết kế trang hồ sơ tối ưu cho nhà tuyển dụng',
    'Kiểm tra quyền riêng tư của liên kết chia sẻ',
    'Phỏng vấn khách hàng để xác thực lời chứng thực',
    'Chuyển review đồng cấp thành điểm nhấn portfolio',
    'Xây mẫu proposal cho dự án ngắn hạn',
    'Tối ưu nội dung hồ sơ bằng dữ liệu tìm kiếm',
    'Rà soát tính nhất quán giữa CV và chứng cứ',
    'Thiết kế bộ lọc cơ hội theo phong cách làm việc',
    'Thử nghiệm hồ sơ song ngữ cho thị trường khu vực',
    'Tổng kết chiến dịch giới thiệu chuyên gia',
  ],
  orgEDataOps: [
    'Lập data contract cho sự kiện hoàn thành nhiệm vụ',
    'Đối soát nguồn gốc điểm đánh giá kỹ năng',
    'Cảnh báo bản ghi notification mất outbox',
    'Kiểm tra drift giữa assignment và task assignee',
    'Xây bộ quy tắc phát hiện review trùng lặp',
    'Chuẩn hóa từ điển chỉ số hiệu suất',
    'Lập báo cáo chất lượng dữ liệu hằng ngày',
    'Diễn tập phục hồi projection hồ sơ năng lực',
    'Thiết kế checklist phê duyệt thay đổi schema',
  ],
  orgEInsightEngine: [
    'Phân tích kỹ năng tăng trưởng sau mỗi sprint',
    'Đo tác động mentoring lên chất lượng bàn giao',
    'So sánh độ tin cậy giữa tự đánh giá và review',
    'Phát hiện nhóm dự án có rủi ro trễ hạn',
    'Giải thích thành phần điểm ghép ứng viên',
    'Theo dõi tỷ lệ tranh chấp được giải quyết',
    'Xây cohort năng lực theo vai trò chuyên môn',
    'Đánh giá tác động của bằng chứng chất lượng cao',
    'Xuất báo cáo điều hành có provenance đầy đủ',
  ],
  orgFReviewOps: [
    'Chuẩn hóa template mô tả pull request có mục tiêu và phạm vi',
    'Thiết lập ngưỡng kích thước thay đổi để review hiệu quả',
    'Phân loại thay đổi theo ý định sửa lỗi tính năng và tài liệu',
    'Đo thời gian phản hồi đầu tiên của reviewer',
    'Rà soát chất lượng checklist kiểm thử trước khi gửi review',
    'Xây playbook xử lý pull request có nhiều vòng yêu cầu sửa',
    'Cảnh báo thay đổi lõi thiếu kế hoạch rollback',
    'Đối soát tỷ lệ merge theo kinh nghiệm tác giả',
    'Thiết kế rubric cho nhận xét review có tính hành động',
    'Theo dõi pull request chờ review quá ngưỡng',
    'Chuẩn hóa bằng chứng CI và kiểm thử trong gói bàn giao',
    'Phân tích mối liên hệ giữa code churn và độ trễ review',
    'Tổng kết chất lượng review theo repository và nhóm kỹ năng',
  ],
  orgFDeveloperExperience: [
    'Thiết kế issue template có bước tái hiện và kết quả mong đợi',
    'Chuẩn hóa môi trường tái hiện lỗi cho người đóng góp mới',
    'Rút gọn thời gian thiết lập workspace phát triển',
    'Xây hướng dẫn chọn label và mức ưu tiên cho issue',
    'Đo tỷ lệ issue thiếu thông tin phải hỏi lại',
    'Thiết kế hành trình contributor từ issue đầu tiên đến merge',
    'Chuẩn hóa decision record cho thay đổi kiến trúc',
    'Tạo catalogue lỗi thiết lập thường gặp theo tech stack',
    'Cải thiện thông báo thất bại của pipeline kiểm thử',
    'Đồng bộ tài liệu API với phiên bản đang phát hành',
    'Thiết kế dashboard ma sát trong vòng đời phát triển',
    'Tổ chức clinic hỗ trợ contributor theo tuần',
    'Đánh giá tác động của template mới lên chất lượng issue',
  ],
  orgFReleaseReliability: [
    'Thiết lập cổng phát hành dựa trên rủi ro thay đổi',
    'Chuẩn hóa bằng chứng smoke test trước khi triển khai',
    'Xây runbook rollback cho migration dữ liệu',
    'Đo tỷ lệ pipeline thất bại theo nguyên nhân',
    'Cảnh báo flaky test ảnh hưởng quyết định phát hành',
    'Diễn tập phục hồi dịch vụ sau lỗi cấu hình',
    'Thiết kế ma trận chủ sở hữu tín hiệu vận hành',
    'Theo dõi lead time từ merge đến production',
    'Chuẩn hóa release note theo tác động người dùng',
    'Đánh giá độ bao phủ quan sát cho luồng nghiệp vụ trọng yếu',
    'Xây checklist bàn giao trực vận hành',
    'Phân tích sự cố phát sinh sau phiên phát hành',
    'Tổng kết mức độ sẵn sàng của phiên bản theo bằng chứng',
  ],
  orgGCitizenPortal: [
    'Thiết kế trang theo dõi trạng thái hồ sơ của người dân',
    'Chuẩn hóa ngôn ngữ thông báo yêu cầu bổ sung giấy tờ',
    'Cải thiện hành trình nộp hồ sơ trên thiết bị di động',
    'Xây chế độ lưu nháp cho biểu mẫu nhiều bước',
    'Kiểm định khả năng dùng bàn phím trên cổng dịch vụ',
    'Thiết kế lịch hẹn và nhắc việc theo ngữ cảnh hồ sơ',
    'Giải thích thời hạn xử lý bằng timeline dễ hiểu',
    'Chuẩn hóa bằng chứng xác nhận đã tiếp nhận yêu cầu',
    'Thử nghiệm hướng dẫn điền biểu mẫu theo từng trường',
    'Đo tỷ lệ hoàn thành hành trình không cần hỗ trợ',
    'Thiết kế kênh phản hồi sau khi nhận kết quả',
    'Rà soát quyền riêng tư của tài liệu đính kèm',
    'Tổng kết điểm nghẽn trong hành trình dịch vụ công',
  ],
  orgGComplaintResolution: [
    'Phân loại phản hồi theo dịch vụ và mức độ ảnh hưởng',
    'Thiết lập SLA phản hồi đầu tiên cho từng nhóm vấn đề',
    'Chuẩn hóa lý do chuyển tuyến giữa các đơn vị xử lý',
    'Xây hồ sơ bằng chứng cho phản hồi có tranh chấp',
    'Phát hiện phản hồi trùng lặp từ nhiều kênh',
    'Thiết kế trạng thái chờ người dân bổ sung thông tin',
    'Theo dõi cam kết khắc phục và người chịu trách nhiệm',
    'Rà soát chất lượng câu trả lời trước khi đóng phản hồi',
    'Đo tỷ lệ mở lại sau khi thông báo đã giải quyết',
    'Xây playbook xử lý phản hồi có rủi ro cao',
    'Phân tích nguyên nhân gốc theo cụm phản hồi',
    'Chuẩn hóa khảo sát hài lòng sau xử lý',
    'Tổng kết tác động cải tiến từ phản hồi người dân',
  ],
  orgGAccessibilityAnalytics: [
    'Lập baseline accessibility cho các hành trình trọng yếu',
    'Đo tỷ lệ lỗi tương phản theo nhóm giao diện',
    'Theo dõi trường biểu mẫu thiếu nhãn hỗ trợ',
    'Phân tích điểm thoát của người dùng dùng thiết bị trợ năng',
    'Xây heatmap lỗi điều hướng bằng bàn phím',
    'Đối soát accessibility giữa mobile và desktop',
    'Thiết kế chỉ số thời gian hoàn thành theo nhóm nhu cầu',
    'Cảnh báo regression accessibility sau phát hành',
    'Chuẩn hóa cách ghi nhận bằng chứng kiểm định',
    'Phân tích phản hồi hỗ trợ liên quan khả năng tiếp cận',
    'Xây cohort cải tiến theo mức độ ảnh hưởng',
    'Đánh giá tác động của component chuẩn lên số lỗi',
    'Xuất báo cáo accessibility có provenance đầy đủ',
  ],
  orgHFarmOperations: [
    'Lập kế hoạch mùa vụ theo vùng canh tác',
    'Phân công kiểm tra đồng ruộng theo lịch',
    'Theo dõi bàn giao vật tư giữa các nhóm nông hộ',
    'Chuẩn hóa nhật ký chăm sóc cây trồng',
    'Cảnh báo công việc hiện trường trễ hạn',
    'Thiết kế quy trình xác nhận hoàn thành bằng ảnh',
    'Đối soát định mức vật tư với diện tích thực tế',
    'Xây bảng điều phối nhân lực theo thời tiết',
    'Ghi nhận sự cố mùa vụ và hành động khắc phục',
    'Theo dõi tỷ lệ hoàn thành checklist canh tác',
    'Thiết kế lịch nghiệm thu theo từng lô ruộng',
    'Tổng hợp bài học sau mỗi giai đoạn mùa vụ',
    'Đánh giá hiệu quả điều phối bằng dữ liệu bàn giao',
  ],
  orgHIotFieldMonitoring: [
    'Chuẩn hóa payload cảm biến độ ẩm hiện trường',
    'Thiết kế hàng đợi đồng bộ khi thiết bị mất mạng',
    'Cảnh báo cảm biến gửi dữ liệu ngoài ngưỡng',
    'Theo dõi chất lượng pin của thiết bị ngoài đồng',
    'Phát hiện chuỗi dữ liệu bị thiếu theo trạm',
    'Xây bản đồ trạng thái thiết bị theo khu vực',
    'Thiết kế xác nhận cảnh báo của người vận hành',
    'Đối soát thời gian thiết bị với thời gian máy chủ',
    'Kiểm thử ứng dụng hiện trường trong mạng yếu',
    'Chuẩn hóa runbook thay thế thiết bị lỗi',
    'Phân tích false alarm theo loại cảm biến',
    'Diễn tập phục hồi dữ liệu sau gián đoạn gateway',
    'Tổng kết độ tin cậy hệ thống giám sát hiện trường',
  ],
  orgHKnowledgeHub: [
    'Biên soạn quy trình kiểm tra đất trước mùa vụ',
    'Chuẩn hóa bài học nhận diện sâu bệnh bằng hình ảnh',
    'Xây rubric đánh giá thực hành tưới tiết kiệm',
    'Thiết kế glossary thuật ngữ nông nghiệp số',
    'Gắn phiên bản tài liệu với mùa vụ áp dụng',
    'Tổ chức review chéo giữa chuyên gia và nông hộ',
    'Xây thư viện bằng chứng thực hành đạt chuẩn',
    'Rà soát nguồn tham khảo cho hướng dẫn canh tác',
    'Thiết kế lộ trình học cho thành viên mới',
    'Chuyển bài học sự cố thành checklist phòng ngừa',
    'Đo mức độ sử dụng tài liệu tại hiện trường',
    'Chuẩn hóa quy trình duyệt nội dung chuyên gia',
    'Tổng kết tri thức được tái sử dụng giữa các mùa vụ',
  ],
  orgISecureDelivery: [
    'Xây threat model cho luồng đăng nhập liên kết',
    'Chuẩn hóa checklist bảo mật trước khi merge',
    'Thiết lập kiểm tra secret trong pipeline',
    'Rà soát quyền truy cập của service account',
    'Thiết kế bằng chứng kiểm thử authorization',
    'Xây cổng phê duyệt cho thay đổi nhạy cảm',
    'Đối soát audit event với hành động nghiệp vụ',
    'Kiểm định cách xử lý dữ liệu cá nhân trong log',
    'Diễn tập rollback khi policy mới gây gián đoạn',
    'Cảnh báo thay đổi bypass kiểm soát bảo mật',
    'Chuẩn hóa hồ sơ chấp nhận rủi ro tạm thời',
    'Đánh giá độ bao phủ threat scenario trọng yếu',
    'Tổng kết readiness bảo mật của phiên phát hành',
  ],
  orgIIncidentReadiness: [
    'Xây runbook xử lý lỗi kết nối cơ sở dữ liệu',
    'Thiết kế ma trận severity và kênh escalation',
    'Chuẩn hóa timeline sự cố từ tín hiệu đầu tiên',
    'Diễn tập mất Redis và chiến lược graceful degradation',
    'Kiểm thử phục hồi notification projection',
    'Xác định chủ sở hữu dashboard vận hành',
    'Thiết kế mẫu cập nhật tình hình cho stakeholder',
    'Đo thời gian phát hiện và khôi phục theo sự cố',
    'Rà soát alert thiếu hành động cụ thể',
    'Xây checklist thu thập bằng chứng sau sự cố',
    'Tổ chức game day cho lỗi dependency bên ngoài',
    'Chuyển postmortem thành hành động có người nhận',
    'Tổng kết năng lực sẵn sàng sự cố theo quý',
  ],
  orgIDependencyGovernance: [
    'Lập inventory dependency theo dịch vụ',
    'Đánh giá rủi ro phiên bản đã hết hỗ trợ',
    'Chuẩn hóa provenance của package nguồn mở',
    'Thiết kế SLA xử lý lỗ hổng theo severity',
    'Phát hiện dependency không còn được sử dụng',
    'Xây quy trình thử nghiệm bản nâng cấp lớn',
    'Đối soát lockfile với manifest phát hành',
    'Thiết kế hồ sơ ngoại lệ cho package chưa thể nâng cấp',
    'Cảnh báo thay đổi license ảnh hưởng sản phẩm',
    'Theo dõi tỷ lệ dependency có owner rõ ràng',
    'Diễn tập thu hồi package bị xâm phạm',
    'Đánh giá tác động supply-chain theo project',
    'Xuất báo cáo dependency governance có bằng chứng',
  ],
  orgJSustainableCommerce: [
    'Chuẩn hóa tiêu chí xác minh nhà cung cấp bền vững',
    'Thiết kế trang giải thích nguồn gốc sản phẩm',
    'Xây quy trình duyệt tuyên bố tác động môi trường',
    'Theo dõi cam kết giao hàng của đối tác',
    'Kiểm định trải nghiệm thanh toán trên mobile',
    'Thiết kế cơ chế phản hồi sau mỗi đơn hàng',
    'Phân loại khiếu nại theo nhà cung cấp và sản phẩm',
    'Xây dashboard tỷ lệ hoàn hàng có nguyên nhân',
    'Thử nghiệm bộ lọc sản phẩm theo giá trị bền vững',
    'Chuẩn hóa bằng chứng cho chiến dịch cộng đồng',
    'Đối soát nội dung marketing với hồ sơ sản phẩm',
    'Thiết kế playbook xử lý đối tác vi phạm cam kết',
    'Tổng kết tác động marketplace theo quý',
  ],
  orgJCustomerInsight: [
    'Phân nhóm phản hồi khách hàng theo hành trình',
    'Thiết kế phỏng vấn người mua quay lại',
    'Đo nguyên nhân bỏ giỏ theo thiết bị',
    'Xây taxonomy nhu cầu từ phản hồi đa kênh',
    'Đối soát sentiment với hành vi mua hàng',
    'Thiết kế thử nghiệm thông tin giao hàng',
    'Phân tích cohort khách hàng theo lần mua đầu',
    'Theo dõi tác động của cải tiến tìm kiếm',
    'Chuẩn hóa repository insight có bằng chứng gốc',
    'Xây scorecard chất lượng nghiên cứu',
    'Phát hiện kết luận vượt quá dữ liệu quan sát',
    'Chuyển insight thành yêu cầu có tiêu chí nghiệm thu',
    'Tổng kết quyết định sản phẩm dựa trên nghiên cứu',
  ],
  orgJCreatorMarketplace: [
    'Thiết kế brief tuyển creator theo năng lực',
    'Xây rubric chấm portfolio sáng tạo',
    'Tổ chức phiên hỏi đáp trước khi ứng tuyển',
    'Chuẩn hóa timeline onboarding cộng tác viên',
    'Theo dõi milestone bàn giao nội dung',
    'Thiết kế gói bằng chứng nghiệm thu chiến dịch',
    'Xử lý hồ sơ creator thiếu quyền sử dụng tài sản',
    'Đo chất lượng phản hồi giữa creator và nhãn hàng',
    'Xây cơ chế ghép creator theo phong cách làm việc',
    'Công bố kết quả tuyển chọn minh bạch',
    'Thiết kế quy trình giải quyết tranh chấp bàn giao',
    'Chuyển đánh giá dự án thành điểm nhấn hồ sơ',
    'Tổng kết hiệu quả mạng lưới creator theo quý',
  ],
}
