import type { TaskSpec } from '../types.js'

import { createScenarioTask } from './scenario_task_creator.js'
import { ensureFourCategoryRequiredSkills } from './task_skill_category_rules.js'

export const SCENARIO_TASK_SPECS: TaskSpec[] = [
  createScenarioTask({
    key: 'member-profile-proof',
    organization: 'orgA',
    project: 'orgAPlatform',
    creator: 'owner',
    assignee: 'member',
    seedGovernanceFixture: true,
    title: 'Xuất bản hồ sơ năng lực có chứng cứ',
    description:
      'Tổng hợp kết quả công việc, kỹ năng đã xác thực và chỉ số hiệu suất thành một hồ sơ năng lực có thể chia sẻ.',
    status: 'done',
    label: 'feature',
    priority: 'high',
    difficulty: 'hard',
    taskType: 'feature_development',
    problemCategory: 'new_capability',
    businessDomain: 'saas',
    acceptanceCriteria: [
      'Hồ sơ công khai hiển thị đúng kỹ năng đã xác thực, lịch sử bàn giao và chỉ số hiệu suất từ dữ liệu đánh giá',
      'Mỗi kỹ năng trên hồ sơ dẫn được về ít nhất một chứng cứ bàn giao đã nghiệm thu',
      'Liên kết chia sẻ hồ sơ hoạt động ở chế độ ẩn danh và không lộ dữ liệu nội bộ tổ chức',
    ],
    expectedDeliverables: [
      'Trang hồ sơ năng lực công khai kèm liên kết chia sẻ',
      'Bảng đối chiếu kỹ năng - chứng cứ - phiên đánh giá',
      'Ghi chú kiểm thử phân quyền khi xem hồ sơ từ ngoài tổ chức',
    ],
    contextBackground:
      'Hồ sơ năng lực là đầu ra trọng tâm của Suar: nhà tuyển dụng cần xem nhanh kỹ năng đã được xác thực qua chứng cứ thay vì tự khai.',
    complexityNotes:
      'Dữ liệu hồ sơ tổng hợp từ nhiều nguồn (đánh giá, bàn giao, kỹ năng) nên cần thống nhất thời điểm chốt số liệu trước khi xuất bản.',
    measurableOutcomes: [
      { metric: 'ty_le_ky_nang_co_chung_cu', target: '100%' },
      { metric: 'thoi_gian_tai_trang_ho_so', target: '<2s' },
    ],
    learningObjectives: ['Tổng hợp hồ sơ từ dữ liệu đánh giá', 'Kiểm soát quyền xem hồ sơ công khai'],
    domainTags: ['profile', 'evidence', 'trust-review'],
    requiredSkills: ['postgresql', 'testing', 'problem_solving'],
  }),
  createScenarioTask({
    key: 'member-admin-regression',
    organization: 'orgA',
    project: 'orgAOperations',
    creator: 'orgAdmin',
    assignee: 'member',
    title: 'Kiểm định điều hướng theo vai trò quản trị',
    description:
      'Hoàn thiện bộ tiêu chí nghiệm thu cho điều hướng quản trị, lịch sử trình duyệt và tổ chức đang hoạt động.',
    status: 'done',
    label: 'documentation',
    priority: 'medium',
    difficulty: 'medium',
    taskType: 'qa_testing',
    problemCategory: 'maintainability',
    businessDomain: 'internal_tooling',
    requiredSkills: ['testing', 'communication'],
  }),
  createScenarioTask({
    key: 'orgb-navigation-qa',
    organization: 'orgB',
    project: 'orgBKnowledgeBase',
    creator: 'orgBOwner',
    assignee: 'owner',
    title: 'Chuẩn hóa hành trình học viên giữa các học viện',
    description:
      'Bảo đảm cố vấn khi chuyển sang học viện đối tác chỉ sử dụng quyền thành viên và không kế thừa quyền điều hành từ Suar.',
    status: 'done',
    label: 'bug',
    priority: 'high',
    difficulty: 'medium',
    taskType: 'qa_testing',
    problemCategory: 'ux_improvement',
    businessDomain: 'edtech',
    requiredSkills: ['testing', 'communication'],
  }),
  createScenarioTask({
    key: 'owner-profile-scoring-loop',
    organization: 'orgA',
    project: 'orgAAnalytics',
    creator: 'owner',
    assignee: 'owner',
    title: 'Đồng bộ điểm năng lực sau phiên đánh giá',
    description:
      'Cập nhật chỉ số tổng hợp, mức độ tin cậy và hồ sơ năng lực ngay khi phiên đánh giá được xác nhận.',
    status: 'done',
    label: 'enhancement',
    priority: 'high',
    difficulty: 'hard',
    taskType: 'feature_development',
    problemCategory: 'automation',
    businessDomain: 'saas',
    requiredSkills: ['postgresql', 'problem_solving'],
  }),
  createScenarioTask({
    key: 'owner-data-governance',
    organization: 'orgA',
    project: 'orgAOperations',
    creator: 'owner',
    assignee: 'owner',
    title: 'Xây dựng quy chuẩn quản trị dữ liệu đánh giá',
    description:
      'Chuẩn hóa quyền sở hữu, nguồn gốc và quy trình đối soát dữ liệu đánh giá xuyên suốt vòng đời dự án.',
    status: 'done',
    label: 'enhancement',
    priority: 'medium',
    difficulty: 'medium',
    taskType: 'technical_writing',
    problemCategory: 'automation',
    businessDomain: 'internal_tooling',
    requiredSkills: ['leadership', 'code_review'],
  }),
  createScenarioTask({
    key: 'owner-evidence-architecture',
    organization: 'orgA',
    project: 'orgAPlatform',
    creator: 'orgAdmin',
    assignee: 'owner',
    seedGovernanceFixture: true,
    title: 'Thiết kế kiến trúc hồ sơ chứng cứ liên mô-đun',
    description:
      'Thiết kế mô hình liên kết công việc, bản bàn giao, tiêu chí nghiệm thu, đánh giá kỹ năng và lịch sử hồ sơ thành một chuỗi chứng cứ có thể truy vết.',
    status: 'done',
    label: 'feature',
    priority: 'high',
    difficulty: 'expert',
    dueDaysOffset: -10,
    assignmentCompletedDaysAgo: 11,
    assignmentEstimatedHours: 28,
    assignmentActualHours: 26,
    taskType: 'feature_development',
    problemCategory: 'new_capability',
    businessDomain: 'saas',
    roleInTask: 'architect',
    autonomyLevel: 'led_others',
    collaborationType: 'cross_team',
    requiredSkills: ['typescript', 'system_design', 'leadership', 'planning'],
  }),
  createScenarioTask({
    key: 'owner-release-governance',
    organization: 'orgA',
    project: 'orgAOperations',
    creator: 'orgAdmin',
    assignee: 'owner',
    title: 'Thiết lập cổng quản trị chất lượng cho phiên phát hành',
    description:
      'Xây dựng tiêu chí go/no-go, ma trận rủi ro và cơ chế phân công trách nhiệm cho mỗi phiên phát hành của nền tảng.',
    status: 'done',
    label: 'enhancement',
    priority: 'urgent',
    difficulty: 'hard',
    dueDaysOffset: -8,
    assignmentCompletedDaysAgo: 9,
    assignmentEstimatedHours: 22,
    assignmentActualHours: 21,
    taskType: 'devops_deployment',
    problemCategory: 'compliance',
    businessDomain: 'internal_tooling',
    roleInTask: 'lead',
    autonomyLevel: 'led_others',
    collaborationType: 'cross_team',
    requiredSkills: ['typescript', 'code_review', 'leadership', 'risk_tracking'],
  }),
  createScenarioTask({
    key: 'owner-impact-analytics',
    organization: 'orgA',
    project: 'orgAAnalytics',
    creator: 'owner',
    assignee: 'owner',
    title: 'Xây dựng bảng chỉ số tác động và độ tin cậy',
    description:
      'Tổng hợp chất lượng bàn giao, độ nhất quán đánh giá và tốc độ phản hồi thành bộ chỉ số phục vụ quyết định sản phẩm.',
    status: 'done',
    label: 'feature',
    priority: 'high',
    difficulty: 'hard',
    dueDaysOffset: -6,
    assignmentCompletedDaysAgo: 7,
    assignmentEstimatedHours: 24,
    assignmentActualHours: 23,
    taskType: 'feature_development',
    problemCategory: 'automation',
    businessDomain: 'data_platform',
    roleInTask: 'lead',
    autonomyLevel: 'autonomous',
    collaborationType: 'small_team',
    requiredSkills: ['postgresql', 'api_design', 'problem_solving', 'planning'],
  }),
  createScenarioTask({
    key: 'owner-profile-api-contract',
    organization: 'orgA',
    project: 'orgAPlatform',
    creator: 'orgAdmin',
    assignee: 'owner',
    title: 'Chuẩn hóa hợp đồng API cho hồ sơ năng lực',
    description:
      'Chuẩn hóa dữ liệu công khai, quyền riêng tư và khả năng tương thích phiên bản cho API hồ sơ năng lực.',
    status: 'done',
    label: 'enhancement',
    priority: 'high',
    difficulty: 'hard',
    dueDaysOffset: -4,
    assignmentCompletedDaysAgo: 5,
    assignmentEstimatedHours: 18,
    assignmentActualHours: 17,
    taskType: 'feature_development',
    problemCategory: 'maintainability',
    businessDomain: 'saas',
    roleInTask: 'architect',
    autonomyLevel: 'autonomous',
    collaborationType: 'small_team',
    requiredSkills: ['typescript', 'api_design', 'communication', 'documentation'],
  }),
  createScenarioTask({
    key: 'owner-active-platform-work',
    organization: 'orgA',
    project: 'orgAPlatform',
    creator: 'owner',
    assignee: 'owner',
    title: 'Hoàn thiện trung tâm theo dõi chất lượng phát hành',
    description:
      'Xây dựng góc nhìn tập trung về công việc đang triển khai, rủi ro chất lượng và các mốc bàn giao của phiên phát hành.',
    status: 'in_progress',
    label: 'enhancement',
    priority: 'medium',
    difficulty: 'medium',
    taskType: 'feature_development',
    problemCategory: 'new_capability',
    businessDomain: 'saas',
    requiredSkills: ['typescript', 'testing', 'communication'],
  }),
  createScenarioTask({
    key: 'owner-review-dispute-case',
    organization: 'orgA',
    project: 'orgAOperations',
    creator: 'orgAdmin',
    assignee: 'owner',
    seedGovernanceFixture: true,
    title: 'Đối soát bộ tiêu chí kiểm định chất lượng dữ liệu',
    description:
      'Đối chiếu kết quả kiểm định với chứng cứ bàn giao khi điểm đánh giá chưa phản ánh đầy đủ phạm vi và chất lượng thực hiện.',
    status: 'done',
    label: 'feature',
    priority: 'high',
    difficulty: 'hard',
    assignmentCompletedDaysAgo: 3,
    taskType: 'qa_testing',
    problemCategory: 'compliance',
    businessDomain: 'internal_tooling',
    acceptanceCriteria: [
      'Từng tiêu chí kiểm định được đối chiếu với chứng cứ bàn giao và ghi rõ đạt hay chưa đạt',
      'Điểm đánh giá cuối cùng có diễn giải căn cứ trên rubric đã thống nhất với người thực hiện',
      'Các điểm chưa thống nhất giữa reviewer và người thực hiện được ghi nhận kèm chứng cứ hai phía',
    ],
    expectedDeliverables: [
      'Biên bản đối soát tiêu chí kiểm định kèm liên kết chứng cứ',
      'Bảng chấm rubric có diễn giải theo từng tiêu chí',
      'Danh sách điểm tranh chấp cần hội đồng xem xét',
    ],
    contextBackground:
      'Phiên đánh giá chất lượng dữ liệu có điểm số thấp hơn kỳ vọng trong khi chứng cứ bàn giao cho thấy phạm vi đã hoàn thành; cần đối soát lại theo rubric trước khi chốt hồ sơ năng lực.',
    complexityNotes:
      'Tranh chấp liên quan tới trọng số tiêu chí giữa reviewer ngang hàng và quản lý, nên mọi kết luận phải dẫn được về chứng cứ và rubric gốc.',
    measurableOutcomes: [
      { metric: 'ty_le_tieu_chi_co_chung_cu', target: '100%' },
      { metric: 'so_diem_tranh_chap_ton_dong', target: 0 },
    ],
    learningObjectives: ['Đối soát đánh giá dựa trên rubric', 'Chuẩn hóa chứng cứ nghiệm thu'],
    domainTags: ['quality-audit', 'rubric', 'dispute-resolution'],
    requiredSkills: ensureFourCategoryRequiredSkills([
      'testing',
      'communication',
      'problem_solving',
    ]),
  }),
  createScenarioTask({
    key: 'orgc-marketplace-ranking',
    organization: 'orgC',
    project: 'orgCMarketplaceLab',
    creator: 'peerReviewer',
    assignee: 'orgAdmin',
    title: 'Xây dựng mô hình xếp hạng đề xuất cộng tác',
    description:
      'Phân tích mức độ phù hợp giữa hồ sơ năng lực, đề xuất chuyên môn và yêu cầu dự án để cải thiện thứ tự gợi ý cộng tác viên.',
    status: 'done',
    visibility: 'external',
    label: 'feature',
    priority: 'high',
    difficulty: 'hard',
    taskType: 'feature_development',
    problemCategory: 'performance',
    businessDomain: 'saas',
    requiredSkills: ['postgresql', 'problem_solving'],
  }),
  createScenarioTask({
    key: 'orga-review-dispute-detail',
    organization: 'orgA',
    project: 'orgAOperations',
    creator: 'orgAdmin',
    assignee: 'member',
    title: 'Hoàn thiện hồ sơ tranh chấp cho hội đồng kiểm duyệt',
    description:
      'Tập hợp rubric, nhận xét của các bên và chứng cứ bàn giao thành hồ sơ có thể kiểm tra và ra quyết định.',
    status: 'done',
    label: 'feature',
    priority: 'medium',
    difficulty: 'medium',
    taskType: 'qa_testing',
    problemCategory: 'new_capability',
    businessDomain: 'internal_tooling',
    requiredSkills: ['testing', 'communication'],
  }),
  createScenarioTask({
    key: 'marketplace-content-pass',
    organization: 'orgA',
    project: 'orgAPlatform',
    creator: 'owner',
    title: 'Nghiên cứu hành trình cộng tác viên trên marketplace',
    description:
      'Khảo sát và đề xuất nội dung cho hành trình khám phá dự án, gửi đề xuất và theo dõi phản hồi của cộng tác viên.',
    status: 'todo',
    label: 'documentation',
    priority: 'medium',
    difficulty: 'easy',
    visibility: 'all',
    taskType: 'technical_writing',
    problemCategory: 'new_capability',
    businessDomain: 'saas',
    requiredSkills: ['communication', 'testing'],
    applicationDeadlineDaysAhead: 6,
  }),
  createScenarioTask({
    key: 'owner-marketplace-pending',
    organization: 'orgD',
    project: 'orgDTalentShowcase',
    creator: 'externalContributorOne',
    title: 'Biên soạn câu chuyện hồ sơ chuyên gia',
    description:
      'Xây dựng nội dung giới thiệu năng lực và các dấu mốc nghề nghiệp cho cổng hồ sơ chuyên gia.',
    status: 'todo',
    label: 'documentation',
    priority: 'medium',
    difficulty: 'medium',
    visibility: 'external',
    taskType: 'technical_writing',
    problemCategory: 'new_capability',
    businessDomain: 'saas',
    requiredSkills: ['communication', 'testing'],
    applicationDeadlineDaysAhead: 8,
  }),
  createScenarioTask({
    key: 'owner-marketplace-approved',
    organization: 'orgE',
    project: 'orgEDataOps',
    creator: 'externalContributorTwo',
    title: 'Kiểm định pipeline chất lượng dữ liệu',
    description:
      'Rà soát quy tắc kiểm tra, khả năng truy vết và báo cáo sai lệch trong pipeline dữ liệu vận hành.',
    status: 'todo',
    label: 'feature',
    priority: 'high',
    difficulty: 'hard',
    visibility: 'external',
    taskType: 'qa_testing',
    problemCategory: 'automation',
    businessDomain: 'data_platform',
    requiredSkills: ['postgresql', 'testing', 'communication'],
    applicationDeadlineDaysAhead: 7,
  }),
  createScenarioTask({
    key: 'owner-marketplace-rejected',
    organization: 'orgD',
    project: 'orgDTalentShowcase',
    creator: 'externalContributorOne',
    title: 'Thiết kế bộ thẻ hồ sơ chuyên gia',
    description:
      'Thiết kế hệ thống thẻ trực quan giúp khách hàng đọc nhanh kỹ năng, kinh nghiệm và mức độ tin cậy của chuyên gia.',
    status: 'todo',
    label: 'enhancement',
    priority: 'medium',
    difficulty: 'medium',
    visibility: 'all',
    taskType: 'ui_ux_design',
    problemCategory: 'ux_improvement',
    businessDomain: 'saas',
    requiredSkills: ['svelte', 'communication'],
    applicationDeadlineDaysAhead: 9,
  }),
  createScenarioTask({
    key: 'owner-marketplace-withdrawn',
    organization: 'orgE',
    project: 'orgEInsightEngine',
    creator: 'externalContributorTwo',
    title: 'Biên soạn tài liệu chỉ số tác động',
    description:
      'Chuẩn hóa định nghĩa, nguồn dữ liệu và hướng dẫn diễn giải các chỉ số tác động của chương trình.',
    status: 'todo',
    label: 'documentation',
    priority: 'low',
    difficulty: 'easy',
    visibility: 'external',
    taskType: 'technical_writing',
    problemCategory: 'maintainability',
    businessDomain: 'data_platform',
    requiredSkills: ['communication', 'postgresql'],
    applicationDeadlineDaysAhead: 10,
  }),
  createScenarioTask({
    key: 'marketplace-qa-pipeline',
    organization: 'orgA',
    project: 'orgAPlatform',
    creator: 'owner',
    title: 'Xây dựng quy trình sàng lọc đề xuất cộng tác',
    description:
      'Xây dựng tiêu chí sàng lọc đề xuất, phân công người đánh giá và cơ chế phản hồi minh bạch cho ứng viên.',
    status: 'todo',
    label: 'feature',
    priority: 'medium',
    difficulty: 'medium',
    visibility: 'external',
    taskType: 'qa_testing',
    problemCategory: 'automation',
    businessDomain: 'saas',
    requiredSkills: ['testing', 'communication'],
    applicationDeadlineDaysAhead: 5,
  }),
  createScenarioTask({
    key: 'member-profile-live',
    organization: 'orgA',
    project: 'orgAPlatform',
    creator: 'owner',
    assignee: 'member',
    title: 'Cập nhật thẻ năng lực theo kết quả đánh giá',
    description:
      'Đồng bộ kỹ năng đã xác thực và điểm chất lượng mới nhất lên thẻ hồ sơ ngay sau phiên đánh giá.',
    status: 'in_review',
    label: 'feature',
    priority: 'medium',
    difficulty: 'medium',
    taskType: 'feature_development',
    problemCategory: 'ux_improvement',
    businessDomain: 'saas',
    requiredSkills: ['svelte', 'testing'],
  }),
  createScenarioTask({
    key: 'orga-design-refresh',
    organization: 'orgA',
    project: 'orgADesignSystem',
    creator: 'owner',
    assignee: 'orgAdmin',
    title: 'Chuẩn hóa trạng thái phân quyền trong hệ thống thiết kế',
    description:
      'Hoàn thiện thành phần giao diện cho các vai trò chủ sở hữu, quản trị viên, thành viên và cộng tác viên.',
    status: 'in_progress',
    label: 'enhancement',
    priority: 'medium',
    difficulty: 'medium',
    taskType: 'ui_ux_design',
    problemCategory: 'ux_improvement',
    businessDomain: 'saas',
    requiredSkills: ['svelte', 'communication'],
  }),
  {
    key: 'owner-orgb-curriculum-todo',
    organization: 'orgB',
    project: 'orgBCurriculumOps',
    creator: 'orgBOwner',
    assignee: 'owner',
    title: 'Hoàn thiện khung năng lực AI ứng dụng',
    description:
      'Phát triển chương trình học theo dự án về ứng dụng AI trong vận hành, phân tích và ra quyết định; mỗi năng lực đều có tiêu chí và minh chứng rõ ràng.',
    status: 'todo',
    taskStatus: 'todo',
    label: 'feature',
    priority: 'high',
    difficulty: 'medium',
    visibility: 'internal',
    dueDaysOffset: 7,
    taskType: 'feature_development',
    problemCategory: 'new_capability',
    businessDomain: 'edtech',
    requiredSkills: ['postgresql', 'testing', 'communication', 'planning'],
    acceptanceCriteria: [
      'Hoàn thiện đề cương 5 môn học cốt lõi',
      'Định nghĩa 10 chỉ số đánh giá năng lực học tập số',
      'Tạo tài liệu hướng dẫn giảng viên áp dụng AI trong chấm điểm',
    ],
    verificationMethod: 'code_review',
    expectedDeliverables: [
      'Curriculum proposal document',
      'Competency rubrics guide',
      'AI-assisted grading workflow specification',
    ],
    contextBackground:
      'Tổ chức đang mở rộng mô hình đào tạo trực tuyến kết hợp AI. Giáo trình này đóng vai trò quan trọng trong việc chuẩn hóa chất lượng và là cơ sở giải quyết các tranh chấp về kết quả học tập sau này.',
    impactScope: 'project',
    techStack: ['Svelte', 'TypeScript', 'PostgreSQL', 'AI Engine'],
    environment: 'production',
    collaborationType: 'small_team',
    complexityNotes:
      'Yêu cầu sự phối hợp chặt chẽ giữa chuyên gia thiết kế bài giảng và kỹ sư hệ thống để tích hợp tính năng tự động chấm điểm.',
    measurableOutcomes: [{ metric: 'curriculum_coverage', target: '95%' }],
    learningObjectives: [
      'EdTech design methodology',
      'AI application in education workflows',
      'Skill-based evaluation models',
    ],
    domainTags: ['education', 'curriculum', 'ai-assisted', 'edtech'],
    roleInTask: 'lead',
    autonomyLevel: 'autonomous',
    estimatedUsersAffected: 1200,
  },
]
