export const TASK_TYPE_OPTIONS = [
  { value: 'feature_development', label: 'Feature development' },
  { value: 'bug_fix', label: 'Bug fix' },
  { value: 'refactoring', label: 'Refactoring' },
  { value: 'architecture_design', label: 'Architecture design' },
  { value: 'code_review', label: 'Code review' },
  { value: 'system_integration', label: 'System integration' },
  { value: 'ui_ux_design', label: 'UI/UX design' },
  { value: 'prototype', label: 'Prototype' },
  { value: 'api_design', label: 'API design' },
  { value: 'qa_testing', label: 'QA testing' },
  { value: 'test_automation', label: 'Test automation' },
  { value: 'performance_testing', label: 'Performance testing' },
  { value: 'devops_deployment', label: 'DevOps / Deployment' },
  { value: 'infrastructure', label: 'Infrastructure' },
  { value: 'monitoring_setup', label: 'Monitoring setup' },
  { value: 'data_analysis', label: 'Data analysis' },
  { value: 'data_pipeline', label: 'Data pipeline' },
  { value: 'reporting', label: 'Reporting' },
  { value: 'technical_writing', label: 'Technical writing' },
  { value: 'documentation', label: 'Documentation' },
  { value: 'knowledge_transfer', label: 'Knowledge transfer' },
  { value: 'research_spike', label: 'Research spike' },
  { value: 'poc', label: 'POC' },
  { value: 'product_management', label: 'Product management' },
  { value: 'mentoring', label: 'Mentoring' },
] as const

export const BUSINESS_DOMAIN_OPTIONS = [
  { value: 'fintech', label: 'Fintech' },
  { value: 'ecommerce', label: 'E-commerce' },
  { value: 'saas', label: 'SaaS' },
  { value: 'edtech', label: 'EdTech' },
  { value: 'healthtech', label: 'HealthTech' },
  { value: 'logistics', label: 'Logistics' },
  { value: 'media', label: 'Media' },
  { value: 'gaming', label: 'Gaming' },
  { value: 'security', label: 'Security' },
  { value: 'data_platform', label: 'Data platform' },
  { value: 'internal_tooling', label: 'Internal tooling' },
  { value: 'infrastructure', label: 'Infrastructure' },
  { value: 'other', label: 'Other' },
] as const

export const PROBLEM_CATEGORY_OPTIONS = [
  { value: 'performance', label: 'Performance' },
  { value: 'scalability', label: 'Scalability' },
  { value: 'security', label: 'Security' },
  { value: 'reliability', label: 'Reliability' },
  { value: 'maintainability', label: 'Maintainability' },
  { value: 'ux_improvement', label: 'UX improvement' },
  { value: 'new_capability', label: 'New capability' },
  { value: 'cost_reduction', label: 'Cost reduction' },
  { value: 'compliance', label: 'Compliance' },
  { value: 'technical_debt', label: 'Technical debt' },
  { value: 'data_quality', label: 'Data quality' },
  { value: 'automation', label: 'Automation' },
] as const

export const ROLE_IN_TASK_OPTIONS = [
  { value: 'sole_contributor', label: 'Sole contributor' },
  { value: 'lead', label: 'Lead' },
  { value: 'contributor', label: 'Contributor' },
  { value: 'reviewer', label: 'Reviewer' },
  { value: 'architect', label: 'Architect' },
  { value: 'coordinator', label: 'Coordinator' },
  { value: 'mentor', label: 'Mentor' },
] as const
