/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-unsafe-return, @typescript-eslint/no-unsafe-enum-comparison */
import { BaseCommand, flags } from '@adonisjs/core/ace'
import type { CommandOptions } from '@adonisjs/core/types/ace'
import db from '@adonisjs/lucid/services/db'
import { randomUUID } from 'node:crypto'
import env from '#start/env'
import mongoose from 'mongoose'
import MongoNotification from '#models/mongo/notification'
import { MongoAuditLogModel } from '#models/mongo/audit_log'
import MongoUserActivityLog from '#models/mongo/user_activity_log'

type UserKey =
  | 'owner'
  | 'superadmin'
  | 'member'
  | 'orgAdmin'
  | 'peerReviewer'
  | 'orgBOwner'
  | 'freelancerOne'
  | 'freelancerTwo'

type OrgKey = 'orgA' | 'orgB' | 'orgC' | 'orgD'
type ProjectKey =
  | 'orgAPlatform'
  | 'orgAOperations'
  | 'orgADesignSystem'
  | 'orgAAnalytics'
  | 'orgBKnowledgeBase'
  | 'orgBCurriculumOps'
  | 'orgCMarketplaceLab'
  | 'orgDTalentShowcase'
type StatusSlug = 'todo' | 'in_progress' | 'in_review' | 'done' | 'cancelled'

type SeededUser = { id: string; username: string; email: string }
type SeededOrg = { id: string; name: string; slug: string }
type SeededProject = { id: string; name: string; organizationId: string }
type SeededTask = { id: string; title: string; organizationId: string; projectId: string | null }
type SeededAssignment = { id: string; taskId: string; assigneeId: string }

type SeedContext = {
  users: Record<UserKey, SeededUser>
  organizations: Record<OrgKey, SeededOrg>
  projects: Record<ProjectKey, SeededProject>
  skills: Record<string, string>
  tasks: Record<string, SeededTask>
  assignments: Record<string, SeededAssignment>
  snapshots: Record<string, string>
}

type TaskSpec = {
  key: string
  organization: OrgKey
  project: ProjectKey
  creator: UserKey
  assignee?: UserKey
  title: string
  description: string
  status: 'todo' | 'in_progress' | 'in_review' | 'done'
  taskStatus: StatusSlug
  label: 'bug' | 'feature' | 'enhancement' | 'documentation'
  priority: 'low' | 'medium' | 'high' | 'urgent'
  difficulty: 'easy' | 'medium' | 'hard' | 'expert'
  visibility: 'internal' | 'external' | 'all'
  dueDaysOffset: number
  assignmentCompletedDaysAgo?: number
  assignmentEstimatedHours?: number
  assignmentActualHours?: number
  taskType:
    | 'feature_development'
    | 'bug_fix'
    | 'documentation'
    | 'ui_ux_design'
    | 'qa_testing'
    | 'code_review'
    | 'devops_deployment'
    | 'technical_writing'
  acceptanceCriteria: string[]
  verificationMethod:
    | 'code_review'
    | 'manual_qa'
    | 'demo_presentation'
    | 'manager_approval'
    | 'documentation_review'
  expectedDeliverables: string[]
  contextBackground: string
  impactScope: 'team' | 'project' | 'organization' | 'end_users'
  techStack: string[]
  environment: 'development' | 'staging' | 'production' | 'mixed'
  collaborationType: 'solo' | 'small_team' | 'cross_team' | 'mentoring_junior' | 'pair_programming'
  complexityNotes: string
  measurableOutcomes: Array<Record<string, unknown>>
  learningObjectives: string[]
  domainTags: string[]
  roleInTask: 'lead' | 'contributor' | 'reviewer' | 'architect' | 'mentor'
  autonomyLevel: 'supervised' | 'autonomous' | 'led_others'
  problemCategory:
    | 'performance'
    | 'security'
    | 'maintainability'
    | 'new_capability'
    | 'automation'
    | 'technical_debt'
    | 'ux_improvement'
  businessDomain: 'saas' | 'edtech' | 'internal_tooling' | 'data_platform' | 'security'
  estimatedUsersAffected: number
  estimatedBudget: number
  applicationDeadlineDaysAhead?: number
  requiredSkills: string[]
}

const TASK_SPECS: TaskSpec[] = [
  {
    key: 'member-org-switch',
    organization: 'orgA',
    project: 'orgAPlatform',
    creator: 'owner',
    assignee: 'member',
    title: 'Hoàn thiện luồng chuyển organization theo role',
    description:
      'Kiểm tra khi user đang là org_owner ở tổ chức A nhưng chỉ là org_member ở tổ chức B thì layout, menu và redirect phải đổi đúng theo role hiện tại.',
    status: 'done',
    taskStatus: 'done',
    label: 'feature',
    priority: 'high',
    difficulty: 'medium',
    visibility: 'internal',
    dueDaysOffset: -14,
    assignmentCompletedDaysAgo: 12,
    assignmentEstimatedHours: 18,
    assignmentActualHours: 16,
    taskType: 'feature_development',
    acceptanceCriteria: [
      'Chuyển organization bằng team switcher không bị giữ quyền cũ',
      'Org member vào org B phải về workspace user thường thay vì org admin layout',
    ],
    verificationMethod: 'manual_qa',
    expectedDeliverables: ['Role-aware switch flow', 'Regression checklist', 'Screen capture demo'],
    contextBackground:
      'Task này được tạo để kiểm thử trực tiếp issue chuyển context khi đổi tổ chức trên cùng một tài khoản.',
    impactScope: 'organization',
    techStack: ['Svelte', 'AdonisJS', 'PostgreSQL'],
    environment: 'staging',
    collaborationType: 'small_team',
    complexityNotes: 'Luồng phụ thuộc session current_organization_id và membership role.',
    measurableOutcomes: [
      { metric: 'role_switch_pass_rate', target: '100%' },
      { metric: 'wrong_redirect_count', target: 0 },
    ],
    learningObjectives: ['Role-based navigation', 'Organization context resolution'],
    domainTags: ['organization', 'rbac', 'navigation'],
    roleInTask: 'contributor',
    autonomyLevel: 'autonomous',
    problemCategory: 'new_capability',
    businessDomain: 'saas',
    estimatedUsersAffected: 42,
    estimatedBudget: 12000000,
    requiredSkills: ['typescript', 'svelte', 'communication'],
  },
  {
    key: 'member-profile-proof',
    organization: 'orgA',
    project: 'orgAPlatform',
    creator: 'orgAdmin',
    assignee: 'member',
    title: 'Xuất profile proof và snapshot công khai',
    description:
      'Seed đủ dữ liệu review, work history và snapshot để màn profile không còn tĩnh và có thể share public.',
    status: 'done',
    taskStatus: 'done',
    label: 'feature',
    priority: 'high',
    difficulty: 'hard',
    visibility: 'internal',
    dueDaysOffset: -10,
    assignmentCompletedDaysAgo: 8,
    assignmentEstimatedHours: 22,
    assignmentActualHours: 24,
    taskType: 'feature_development',
    acceptanceCriteria: [
      'Profile hiển thị metrics, skills và featured reviews từ dữ liệu thật',
      'Có current snapshot và lịch sử snapshot để user kiểm tra share link',
    ],
    verificationMethod: 'demo_presentation',
    expectedDeliverables: [
      'Published profile snapshot',
      'Verified work history',
      'Review evidence links',
    ],
    contextBackground:
      'Task này phục vụ trực tiếp cho tài khoản user thường cần có hồ sơ đã hoàn thiện và đã được hệ thống tổng hợp.',
    impactScope: 'project',
    techStack: ['PostgreSQL', 'MongoDB', 'Svelte'],
    environment: 'staging',
    collaborationType: 'cross_team',
    complexityNotes:
      'Liên quan đồng thời đến review_sessions, skill_reviews, user_profile_snapshots.',
    measurableOutcomes: [
      { metric: 'profile_snapshot_versions', target: 1 },
      { metric: 'featured_reviews_visible', target: true },
    ],
    learningObjectives: ['Profile aggregation pipeline', 'Snapshot publication'],
    domainTags: ['profile', 'proof', 'review'],
    roleInTask: 'contributor',
    autonomyLevel: 'autonomous',
    problemCategory: 'new_capability',
    businessDomain: 'saas',
    estimatedUsersAffected: 18,
    estimatedBudget: 15000000,
    requiredSkills: ['postgresql', 'testing', 'problem_solving'],
  },
  {
    key: 'member-admin-regression',
    organization: 'orgA',
    project: 'orgAOperations',
    creator: 'owner',
    assignee: 'member',
    title: 'Chuẩn bị regression pack cho admin redirect',
    description:
      'Tạo checklist và tài liệu kiểm thử để xác minh superadmin luôn vào /admin thay vì rơi về organization workspace.',
    status: 'done',
    taskStatus: 'done',
    label: 'documentation',
    priority: 'medium',
    difficulty: 'medium',
    visibility: 'internal',
    dueDaysOffset: -7,
    assignmentCompletedDaysAgo: 6,
    assignmentEstimatedHours: 10,
    assignmentActualHours: 9,
    taskType: 'technical_writing',
    acceptanceCriteria: [
      'Có checklist login superadmin',
      'Có checklist browser back sau khi vào admin',
    ],
    verificationMethod: 'documentation_review',
    expectedDeliverables: ['Admin redirect checklist', 'Back navigation notes'],
    contextBackground:
      'Tài liệu dùng để kiểm tra các lỗi redirect không ổn định giữa admin và organization context.',
    impactScope: 'team',
    techStack: ['Documentation', 'Svelte'],
    environment: 'mixed',
    collaborationType: 'small_team',
    complexityNotes:
      'Phải mô tả rõ các case có current organization và không có current organization.',
    measurableOutcomes: [{ metric: 'regression_cases_documented', target: 8 }],
    learningObjectives: ['Regression planning', 'Navigation bug isolation'],
    domainTags: ['admin', 'redirect', 'qa'],
    roleInTask: 'reviewer',
    autonomyLevel: 'supervised',
    problemCategory: 'maintainability',
    businessDomain: 'internal_tooling',
    estimatedUsersAffected: 8,
    estimatedBudget: 5000000,
    requiredSkills: ['testing', 'communication'],
  },
  {
    key: 'member-profile-live',
    organization: 'orgA',
    project: 'orgAPlatform',
    creator: 'orgAdmin',
    assignee: 'member',
    title: 'Giữ profile user đồng bộ sau mỗi lần review',
    description:
      'Task đang làm dở để kiểm tra profile user còn hiển thị dynamic khi có công việc active và review chưa hoàn tất.',
    status: 'in_review',
    taskStatus: 'in_review',
    label: 'enhancement',
    priority: 'high',
    difficulty: 'medium',
    visibility: 'internal',
    dueDaysOffset: 4,
    assignmentEstimatedHours: 14,
    assignmentActualHours: 8,
    taskType: 'feature_development',
    acceptanceCriteria: [
      'Widget profile lấy số liệu active task mới nhất',
      'Snapshot history reload được ngay sau publish',
    ],
    verificationMethod: 'code_review',
    expectedDeliverables: ['Reactive profile widgets', 'Review-ready merge request'],
    contextBackground: 'Dùng để test trạng thái đang làm của user thường trên workspace profile.',
    impactScope: 'project',
    techStack: ['Svelte', 'Redis'],
    environment: 'development',
    collaborationType: 'pair_programming',
    complexityNotes: 'Cần invalidation cache đúng khi publish snapshot.',
    measurableOutcomes: [{ metric: 'profile_refresh_seconds', target: '< 2' }],
    learningObjectives: ['Cache invalidation', 'Profile UI state'],
    domainTags: ['profile', 'cache', 'reactivity'],
    roleInTask: 'contributor',
    autonomyLevel: 'autonomous',
    problemCategory: 'ux_improvement',
    businessDomain: 'saas',
    estimatedUsersAffected: 16,
    estimatedBudget: 9000000,
    requiredSkills: ['typescript', 'testing'],
  },
  {
    key: 'owner-admin-investigation',
    organization: 'orgA',
    project: 'orgAOperations',
    creator: 'owner',
    assignee: 'owner',
    title: 'Theo dõi lỗi redirect của superadmin sau social login',
    description:
      'Task dành cho tài khoản chủ tổ chức để kiểm thử dữ liệu dashboard, log điều hướng và các case back/forward của giao diện admin.',
    status: 'in_progress',
    taskStatus: 'in_progress',
    label: 'bug',
    priority: 'urgent',
    difficulty: 'hard',
    visibility: 'internal',
    dueDaysOffset: 2,
    assignmentEstimatedHours: 20,
    assignmentActualHours: 11,
    taskType: 'bug_fix',
    acceptanceCriteria: [
      'Superadmin luôn redirect vào /admin sau callback',
      'Không phát sinh redirect ngoài ý muốn về organization khi chưa tắt admin mode',
    ],
    verificationMethod: 'manager_approval',
    expectedDeliverables: ['Issue triage notes', 'Redirect trace', 'Session state summary'],
    contextBackground:
      'Task này gắn trực tiếp với việc kiểm tra hành vi của tài khoản DuyetTN3112(edu).',
    impactScope: 'organization',
    techStack: ['AdonisJS', 'PostgreSQL', 'MongoDB'],
    environment: 'staging',
    collaborationType: 'cross_team',
    complexityNotes: 'Đụng tới auth callback, session và admin mode toggle.',
    measurableOutcomes: [{ metric: 'admin_redirect_failures', target: 0 }],
    learningObjectives: ['Auth redirect tracing', 'Admin mode state'],
    domainTags: ['admin', 'auth', 'session'],
    roleInTask: 'lead',
    autonomyLevel: 'led_others',
    problemCategory: 'maintainability',
    businessDomain: 'internal_tooling',
    estimatedUsersAffected: 6,
    estimatedBudget: 18000000,
    requiredSkills: ['leadership', 'communication', 'postgresql'],
  },
  {
    key: 'owner-seed-governance',
    organization: 'orgA',
    project: 'orgAOperations',
    creator: 'owner',
    assignee: 'orgAdmin',
    title: 'Điều phối seed data đa vai trò cho demo local',
    description:
      'Seed dữ liệu đủ cho ba giao diện: system admin, organization admin/owner và user thường.',
    status: 'done',
    taskStatus: 'done',
    label: 'enhancement',
    priority: 'medium',
    difficulty: 'medium',
    visibility: 'internal',
    dueDaysOffset: -5,
    assignmentCompletedDaysAgo: 3,
    assignmentEstimatedHours: 12,
    assignmentActualHours: 12,
    taskType: 'feature_development',
    acceptanceCriteria: [
      'Có ít nhất hai organization với role khác nhau cho cùng một user',
      'Có review data và audit log cho admin kiểm tra',
    ],
    verificationMethod: 'manager_approval',
    expectedDeliverables: ['Reusable seed command', 'Role coverage matrix'],
    contextBackground: 'Task này tạo dữ liệu nền cho toàn bộ môi trường test local.',
    impactScope: 'organization',
    techStack: ['TypeScript', 'PostgreSQL', 'MongoDB'],
    environment: 'development',
    collaborationType: 'small_team',
    complexityNotes: 'Phải đồng bộ cả PostgreSQL lẫn MongoDB.',
    measurableOutcomes: [{ metric: 'seed_command_success', target: true }],
    learningObjectives: ['Cross-database seeding'],
    domainTags: ['seed', 'local-dev', 'roles'],
    roleInTask: 'lead',
    autonomyLevel: 'led_others',
    problemCategory: 'automation',
    businessDomain: 'internal_tooling',
    estimatedUsersAffected: 10,
    estimatedBudget: 11000000,
    requiredSkills: ['typescript', 'devops', 'problem_solving'],
  },
  {
    key: 'marketplace-content-pass',
    organization: 'orgA',
    project: 'orgAPlatform',
    creator: 'owner',
    title: 'Viết lại nội dung public task cho marketplace',
    description:
      'Task public để test luồng ứng tuyển của freelancer và số liệu external applications trên board.',
    status: 'todo',
    taskStatus: 'todo',
    label: 'documentation',
    priority: 'medium',
    difficulty: 'easy',
    visibility: 'all',
    dueDaysOffset: 9,
    taskType: 'technical_writing',
    acceptanceCriteria: [
      'Mô tả task rõ ràng cho external contributor',
      'Có application deadline và danh sách deliverables',
    ],
    verificationMethod: 'documentation_review',
    expectedDeliverables: ['Marketplace task brief', 'Ready-to-apply scope'],
    contextBackground: 'Dùng để seed marketplace data cho giao diện task applications.',
    impactScope: 'end_users',
    techStack: ['Documentation'],
    environment: 'development',
    collaborationType: 'solo',
    complexityNotes: 'Task không assign sẵn để freelancer có thể apply.',
    measurableOutcomes: [{ metric: 'applications_expected', target: 2 }],
    learningObjectives: ['Marketplace copywriting'],
    domainTags: ['marketplace', 'copy', 'external'],
    roleInTask: 'architect',
    autonomyLevel: 'autonomous',
    problemCategory: 'new_capability',
    businessDomain: 'saas',
    estimatedUsersAffected: 120,
    estimatedBudget: 7000000,
    applicationDeadlineDaysAhead: 5,
    requiredSkills: ['communication', 'code_review'],
  },
  {
    key: 'marketplace-qa-pipeline',
    organization: 'orgA',
    project: 'orgAPlatform',
    creator: 'orgAdmin',
    title: 'Thiết lập checklist QA cho contributor ngoài hệ thống',
    description:
      'Một task open khác để kiểm tra số liệu ứng tuyển, approval và notification liên quan.',
    status: 'todo',
    taskStatus: 'todo',
    label: 'feature',
    priority: 'high',
    difficulty: 'medium',
    visibility: 'external',
    dueDaysOffset: 12,
    taskType: 'qa_testing',
    acceptanceCriteria: [
      'Có checklist xác minh deliverables từ freelancer',
      'Notification gửi về owner khi có ứng viên mới',
    ],
    verificationMethod: 'manual_qa',
    expectedDeliverables: ['QA checklist', 'Approval flow note'],
    contextBackground: 'Task phục vụ kiểm thử application flow và notification dropdown.',
    impactScope: 'project',
    techStack: ['Testing', 'MongoDB'],
    environment: 'staging',
    collaborationType: 'small_team',
    complexityNotes: 'Task public nhưng vẫn cần role owner xem application list.',
    measurableOutcomes: [{ metric: 'new_application_notifications', target: 2 }],
    learningObjectives: ['Freelancer intake flow'],
    domainTags: ['marketplace', 'qa', 'notification'],
    roleInTask: 'reviewer',
    autonomyLevel: 'supervised',
    problemCategory: 'automation',
    businessDomain: 'saas',
    estimatedUsersAffected: 60,
    estimatedBudget: 13000000,
    applicationDeadlineDaysAhead: 7,
    requiredSkills: ['testing', 'communication'],
  },
  {
    key: 'orgb-onboarding',
    organization: 'orgB',
    project: 'orgBKnowledgeBase',
    creator: 'orgBOwner',
    assignee: 'owner',
    title: 'Chuẩn hóa handbook onboarding cho org B',
    description:
      'Task ở organization B để tài khoản tranngocduyet31@gmail.com có thể test khi chuyển sang org mà chỉ là member thường.',
    status: 'in_progress',
    taskStatus: 'in_progress',
    label: 'documentation',
    priority: 'medium',
    difficulty: 'medium',
    visibility: 'internal',
    dueDaysOffset: 6,
    assignmentEstimatedHours: 12,
    assignmentActualHours: 5,
    taskType: 'technical_writing',
    acceptanceCriteria: [
      'Tài khoản owner của org A vẫn xem được task ở org B với role member',
      'Không hiện menu quản trị org khi đang ở org B',
    ],
    verificationMethod: 'documentation_review',
    expectedDeliverables: ['Org B onboarding handbook draft'],
    contextBackground:
      'Task này dùng để test chính xác case chuyển từ org_owner ở A sang org_member ở B.',
    impactScope: 'team',
    techStack: ['Documentation', 'Svelte'],
    environment: 'development',
    collaborationType: 'small_team',
    complexityNotes: 'Tập trung vào UI context của organization switcher.',
    measurableOutcomes: [{ metric: 'org_b_layout_correct', target: true }],
    learningObjectives: ['Context switching'],
    domainTags: ['organization', 'member-view'],
    roleInTask: 'contributor',
    autonomyLevel: 'supervised',
    problemCategory: 'ux_improvement',
    businessDomain: 'edtech',
    estimatedUsersAffected: 14,
    estimatedBudget: 6000000,
    requiredSkills: ['communication'],
  },
]

const EXTRA_TASK_SPECS: TaskSpec[] = [
  {
    key: 'orga-design-refresh',
    organization: 'orgA',
    project: 'orgADesignSystem',
    creator: 'owner',
    assignee: 'orgAdmin',
    title: 'Refactor design tokens cho dashboard đa vai trò',
    description:
      'Mở rộng token và component states để owner/admin/member nhìn khác nhau rõ ràng trên cùng một shell.',
    status: 'in_progress',
    taskStatus: 'in_progress',
    label: 'feature',
    priority: 'high',
    difficulty: 'medium',
    visibility: 'internal',
    dueDaysOffset: 6,
    assignmentEstimatedHours: 18,
    assignmentActualHours: 7,
    taskType: 'ui_ux_design',
    acceptanceCriteria: [
      'Role badge hiển thị rõ trên sidebar và header',
      'State member không còn hiện quick action của owner',
    ],
    verificationMethod: 'code_review',
    expectedDeliverables: ['Updated design tokens', 'Role-aware layout states'],
    contextBackground: 'Task dùng để test sự khác biệt thị giác giữa org owner và org member.',
    impactScope: 'organization',
    techStack: ['Svelte', 'TypeScript', 'Design System'],
    environment: 'development',
    collaborationType: 'small_team',
    complexityNotes: 'Cần đồng bộ component shared giữa app layout, org layout và admin layout.',
    measurableOutcomes: [{ metric: 'role_visual_regressions', target: 0 }],
    learningObjectives: ['Role-aware interface patterns'],
    domainTags: ['design-system', 'rbac', 'layout'],
    roleInTask: 'lead',
    autonomyLevel: 'autonomous',
    problemCategory: 'ux_improvement',
    businessDomain: 'saas',
    estimatedUsersAffected: 80,
    estimatedBudget: 14000000,
    requiredSkills: ['svelte', 'typescript', 'communication'],
  },
  {
    key: 'orga-admin-dashboard-metrics',
    organization: 'orgA',
    project: 'orgAAnalytics',
    creator: 'owner',
    assignee: 'owner',
    title: 'Mở rộng dashboard hệ thống với package và moderation metrics',
    description:
      'Task phục vụ dựng dashboard admin nhiều lát cắt hơn: subscription, flagged reviews, audit activity và adoption.',
    status: 'in_review',
    taskStatus: 'in_review',
    label: 'feature',
    priority: 'urgent',
    difficulty: 'hard',
    visibility: 'internal',
    dueDaysOffset: 3,
    assignmentEstimatedHours: 24,
    assignmentActualHours: 19,
    taskType: 'feature_development',
    acceptanceCriteria: [
      'Dashboard có thêm card package usage và moderation backlog',
      'Admin nhìn được top organizations và top users theo usage',
    ],
    verificationMethod: 'manager_approval',
    expectedDeliverables: ['Admin metric widgets', 'Dashboard drilldown spec'],
    contextBackground: 'Task này dùng để test trực tiếp các màn dashboard của system admin.',
    impactScope: 'organization',
    techStack: ['AdonisJS', 'PostgreSQL', 'MongoDB'],
    environment: 'staging',
    collaborationType: 'cross_team',
    complexityNotes: 'Phải ghép dữ liệu từ PostgreSQL subscriptions và Mongo audit logs.',
    measurableOutcomes: [{ metric: 'admin_dashboard_sections', target: 6 }],
    learningObjectives: ['Cross-store analytics'],
    domainTags: ['admin', 'dashboard', 'analytics'],
    roleInTask: 'architect',
    autonomyLevel: 'led_others',
    problemCategory: 'new_capability',
    businessDomain: 'internal_tooling',
    estimatedUsersAffected: 12,
    estimatedBudget: 22000000,
    requiredSkills: ['postgresql', 'mongodb', 'leadership'],
  },
  {
    key: 'orga-review-dispute-detail',
    organization: 'orgA',
    project: 'orgAAnalytics',
    creator: 'orgAdmin',
    assignee: 'peerReviewer',
    title: 'Dựng màn review dispute detail cho system admin',
    description:
      'Tạo dữ liệu và UI để admin xem chi tiết flagged review, evidence, reviewer và reviewee trước khi resolve.',
    status: 'todo',
    taskStatus: 'todo',
    label: 'enhancement',
    priority: 'high',
    difficulty: 'medium',
    visibility: 'internal',
    dueDaysOffset: 11,
    assignmentEstimatedHours: 13,
    taskType: 'feature_development',
    acceptanceCriteria: [
      'Có detail page cho flagged review',
      'Có resolve action trực tiếp từ detail page',
    ],
    verificationMethod: 'manual_qa',
    expectedDeliverables: ['Flagged review detail view', 'Dispute checklist'],
    contextBackground: 'Task này chốt phần còn thiếu để admin xử lý tranh chấp review.',
    impactScope: 'organization',
    techStack: ['Svelte', 'MongoDB', 'PostgreSQL'],
    environment: 'staging',
    collaborationType: 'small_team',
    complexityNotes: 'Cần ghép flagged review, review session, skill review và evidence.',
    measurableOutcomes: [{ metric: 'review_detail_resolution_steps', target: 2 }],
    learningObjectives: ['Moderation UX'],
    domainTags: ['review', 'moderation', 'detail'],
    roleInTask: 'reviewer',
    autonomyLevel: 'autonomous',
    problemCategory: 'maintainability',
    businessDomain: 'internal_tooling',
    estimatedUsersAffected: 6,
    estimatedBudget: 9000000,
    requiredSkills: ['testing', 'communication', 'problem_solving'],
  },
  {
    key: 'orga-notification-center',
    organization: 'orgA',
    project: 'orgAPlatform',
    creator: 'orgAdmin',
    assignee: 'member',
    title: 'Hoàn thiện notification center với empty state và quick actions',
    description:
      'Bổ sung trạng thái trống, refresh, mark-as-read và hành vi dropdown rõ ràng cho user workspace.',
    status: 'in_progress',
    taskStatus: 'in_progress',
    label: 'enhancement',
    priority: 'high',
    difficulty: 'medium',
    visibility: 'internal',
    dueDaysOffset: 5,
    assignmentEstimatedHours: 12,
    assignmentActualHours: 4,
    taskType: 'feature_development',
    acceptanceCriteria: [
      'Icon notification click ra được dữ liệu seeded thật',
      'Có phân biệt unread/read rõ ràng',
    ],
    verificationMethod: 'manual_qa',
    expectedDeliverables: ['Notification dropdown polish', 'UI state checklist'],
    contextBackground: 'Task dùng để test issue notification icon không hiển thị gì.',
    impactScope: 'project',
    techStack: ['Svelte', 'MongoDB'],
    environment: 'development',
    collaborationType: 'pair_programming',
    complexityNotes: 'Phụ thuộc dữ liệu Mongo và route JSON trong workspace shell.',
    measurableOutcomes: [{ metric: 'notification_dropdown_errors', target: 0 }],
    learningObjectives: ['Async UI state'],
    domainTags: ['notification', 'workspace', 'ux'],
    roleInTask: 'contributor',
    autonomyLevel: 'autonomous',
    problemCategory: 'ux_improvement',
    businessDomain: 'saas',
    estimatedUsersAffected: 140,
    estimatedBudget: 11000000,
    requiredSkills: ['svelte', 'testing'],
  },
  {
    key: 'orgb-member-task-board',
    organization: 'orgB',
    project: 'orgBCurriculumOps',
    creator: 'orgBOwner',
    assignee: 'owner',
    title: 'Chuẩn bị board công việc cho member view của org B',
    description:
      'Tạo thêm task được assign cho Suar khi đang ở org B để task board không còn trống sau khi switch.',
    status: 'in_progress',
    taskStatus: 'in_progress',
    label: 'feature',
    priority: 'medium',
    difficulty: 'medium',
    visibility: 'internal',
    dueDaysOffset: 7,
    assignmentEstimatedHours: 10,
    assignmentActualHours: 3,
    taskType: 'technical_writing',
    acceptanceCriteria: [
      'Member view ở org B nhìn thấy task được giao',
      'Không lộ menu quản trị org',
    ],
    verificationMethod: 'documentation_review',
    expectedDeliverables: ['Org B task board demo content'],
    contextBackground:
      'Task này tồn tại để user test đúng trường hợp member ở org B vẫn có dữ liệu để thao tác.',
    impactScope: 'team',
    techStack: ['Documentation', 'Svelte'],
    environment: 'development',
    collaborationType: 'small_team',
    complexityNotes: 'Quan trọng ở mặt context chứ không phải logic domain sâu.',
    measurableOutcomes: [{ metric: 'org_b_visible_tasks_for_owner_account', target: 2 }],
    learningObjectives: ['Cross-org context testing'],
    domainTags: ['organization', 'member-view', 'tasks'],
    roleInTask: 'contributor',
    autonomyLevel: 'supervised',
    problemCategory: 'ux_improvement',
    businessDomain: 'edtech',
    estimatedUsersAffected: 15,
    estimatedBudget: 5000000,
    requiredSkills: ['communication'],
  },
  {
    key: 'orgb-content-calendar',
    organization: 'orgB',
    project: 'orgBCurriculumOps',
    creator: 'orgBOwner',
    assignee: 'orgBOwner',
    title: 'Lập content calendar cho handbook và onboarding của org B',
    description:
      'Task bổ sung để project detail và task list của org B có mật độ dữ liệu thực tế hơn.',
    status: 'todo',
    taskStatus: 'todo',
    label: 'documentation',
    priority: 'low',
    difficulty: 'easy',
    visibility: 'internal',
    dueDaysOffset: 15,
    assignmentEstimatedHours: 6,
    taskType: 'technical_writing',
    acceptanceCriteria: ['Có lịch nội dung 4 tuần', 'Có owner rõ cho từng bài'],
    verificationMethod: 'documentation_review',
    expectedDeliverables: ['Content calendar draft'],
    contextBackground: 'Task seed density cho org B.',
    impactScope: 'team',
    techStack: ['Documentation'],
    environment: 'development',
    collaborationType: 'solo',
    complexityNotes: 'Low complexity seed task.',
    measurableOutcomes: [{ metric: 'content_slots_seeded', target: 4 }],
    learningObjectives: ['Content operations'],
    domainTags: ['content', 'edtech'],
    roleInTask: 'lead',
    autonomyLevel: 'autonomous',
    problemCategory: 'automation',
    businessDomain: 'edtech',
    estimatedUsersAffected: 9,
    estimatedBudget: 3000000,
    requiredSkills: ['communication'],
  },
  {
    key: 'orgb-navigation-qa',
    organization: 'orgB',
    project: 'orgBKnowledgeBase',
    creator: 'orgBOwner',
    assignee: 'owner',
    title: 'Kiểm thử navigation sau khi quay lại từ admin mode',
    description:
      'Tạo task ở org B để tài khoản Suar có thêm một case member-only liên quan navigation và browser history.',
    status: 'done',
    taskStatus: 'done',
    label: 'documentation',
    priority: 'medium',
    difficulty: 'medium',
    visibility: 'internal',
    dueDaysOffset: -6,
    assignmentCompletedDaysAgo: 4,
    assignmentEstimatedHours: 8,
    assignmentActualHours: 8,
    taskType: 'qa_testing',
    acceptanceCriteria: [
      'Back button không nhảy sai context',
      'Session giữ đúng current organization',
    ],
    verificationMethod: 'manual_qa',
    expectedDeliverables: ['Navigation QA report'],
    contextBackground: 'Giúp profile/history của owner account có thêm dữ liệu ngoài org A.',
    impactScope: 'team',
    techStack: ['Svelte', 'Browser'],
    environment: 'staging',
    collaborationType: 'small_team',
    complexityNotes: 'Phụ thuộc browser history và session state.',
    measurableOutcomes: [{ metric: 'unexpected_redirects', target: 0 }],
    learningObjectives: ['History navigation'],
    domainTags: ['admin', 'navigation', 'session'],
    roleInTask: 'contributor',
    autonomyLevel: 'supervised',
    problemCategory: 'maintainability',
    businessDomain: 'edtech',
    estimatedUsersAffected: 10,
    estimatedBudget: 6000000,
    requiredSkills: ['testing', 'communication'],
  },
  {
    key: 'orgc-marketplace-ranking',
    organization: 'orgC',
    project: 'orgCMarketplaceLab',
    creator: 'peerReviewer',
    assignee: 'owner',
    title: 'So sánh package Pro và ProMax trong ranking của marketplace',
    description:
      'Task ở org C để seed thêm ngữ cảnh cross-org cho account owner và dữ liệu liên quan package management.',
    status: 'in_progress',
    taskStatus: 'in_progress',
    label: 'feature',
    priority: 'high',
    difficulty: 'hard',
    visibility: 'internal',
    dueDaysOffset: 9,
    assignmentEstimatedHours: 16,
    assignmentActualHours: 6,
    taskType: 'feature_development',
    acceptanceCriteria: [
      'Có bảng so sánh package Pro/ProMax',
      'Admin dashboard đọc được adoption theo package',
    ],
    verificationMethod: 'code_review',
    expectedDeliverables: ['Package comparison matrix', 'Adoption counters'],
    contextBackground: 'Task phục vụ trực tiếp cho admin package management page.',
    impactScope: 'organization',
    techStack: ['PostgreSQL', 'Svelte'],
    environment: 'staging',
    collaborationType: 'small_team',
    complexityNotes: 'Phụ thuộc user_subscriptions và admin analytics.',
    measurableOutcomes: [{ metric: 'package_segments_visible', target: 2 }],
    learningObjectives: ['Package analytics'],
    domainTags: ['subscription', 'marketplace', 'admin'],
    roleInTask: 'architect',
    autonomyLevel: 'autonomous',
    problemCategory: 'new_capability',
    businessDomain: 'saas',
    estimatedUsersAffected: 70,
    estimatedBudget: 16000000,
    requiredSkills: ['postgresql', 'typescript', 'problem_solving'],
  },
  {
    key: 'orgc-top-contributors',
    organization: 'orgC',
    project: 'orgCMarketplaceLab',
    creator: 'peerReviewer',
    assignee: 'orgAdmin',
    title: 'Seed top contributors leaderboard cho dashboard hệ thống',
    description:
      'Task tạo thêm scenario analytics để dashboard admin có ranking người dùng và tổ chức nổi bật.',
    status: 'todo',
    taskStatus: 'todo',
    label: 'enhancement',
    priority: 'medium',
    difficulty: 'medium',
    visibility: 'internal',
    dueDaysOffset: 12,
    assignmentEstimatedHours: 9,
    taskType: 'feature_development',
    acceptanceCriteria: ['Dashboard có top users', 'Dashboard có top organizations'],
    verificationMethod: 'manager_approval',
    expectedDeliverables: ['Leaderboard cards'],
    contextBackground: 'Bổ sung đủ data shapes cho system admin dashboard.',
    impactScope: 'organization',
    techStack: ['AdonisJS', 'Charts'],
    environment: 'development',
    collaborationType: 'small_team',
    complexityNotes: 'Cần aggregate qua projects, tasks và memberships.',
    measurableOutcomes: [{ metric: 'dashboard_leaderboards', target: 2 }],
    learningObjectives: ['Aggregation design'],
    domainTags: ['analytics', 'leaderboard', 'dashboard'],
    roleInTask: 'contributor',
    autonomyLevel: 'autonomous',
    problemCategory: 'automation',
    businessDomain: 'saas',
    estimatedUsersAffected: 20,
    estimatedBudget: 8000000,
    requiredSkills: ['typescript', 'testing'],
  },
  {
    key: 'orgd-talent-proof',
    organization: 'orgD',
    project: 'orgDTalentShowcase',
    creator: 'freelancerOne',
    assignee: 'freelancerOne',
    title: 'Xây landing page talent showcase cho external contributors',
    description:
      'Seed thêm một org do freelancer làm owner để admin thấy hệ thống có nhiều loại tổ chức và project hơn.',
    status: 'done',
    taskStatus: 'done',
    label: 'feature',
    priority: 'medium',
    difficulty: 'medium',
    visibility: 'internal',
    dueDaysOffset: -9,
    assignmentCompletedDaysAgo: 5,
    assignmentEstimatedHours: 14,
    assignmentActualHours: 13,
    taskType: 'feature_development',
