/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  admin: {
    auditLogs: {
      ListAuditLogs: () => import('#controllers/admin/audit_logs/list_audit_logs_controller'),
    },
    Dashboard: () => import('#controllers/admin/dashboard_controller'),
    organizations: {
      ListOrganizations: () => import('#controllers/admin/organizations/list_organizations_controller'),
      ShowOrganization: () => import('#controllers/admin/organizations/show_organization_controller'),
    },
    packages: {
      ListPackages: () => import('#controllers/admin/packages/list_packages_controller'),
      ShowQrCodes: () => import('#controllers/admin/packages/show_qr_codes_controller'),
      UpdatePackage: () => import('#controllers/admin/packages/update_package_controller'),
    },
    permissions: {
      ShowPermissions: () => import('#controllers/admin/permissions/show_permissions_controller'),
    },
    reviews: {
      ListFlaggedReviews: () => import('#controllers/admin/reviews/list_flagged_reviews_controller'),
      ResolveFlaggedReview: () => import('#controllers/admin/reviews/resolve_flagged_review_controller'),
      ShowFlaggedReview: () => import('#controllers/admin/reviews/show_flagged_review_controller'),
    },
    ToggleAdminMode: () => import('#controllers/admin/toggle_admin_mode_controller'),
    users: {
      ListUsers: () => import('#controllers/admin/users/list_users_controller'),
      ShowUser: () => import('#controllers/admin/users/show_user_controller'),
      SuspendUser: () => import('#controllers/admin/users/suspend_user_controller'),
      UpdateUserRole: () => import('#controllers/admin/users/update_user_role_controller'),
    },
  },
  audit: {
    mappers: {
      AuditLogResponseMapper: () => import('#controllers/audit/mappers/audit_log_response_mapper'),
    },
  },
  auth: {
    Logout: () => import('#controllers/auth/logout_controller'),
    mappers: {
      request: {
        AuthRequestMapper: () => import('#controllers/auth/mappers/request/auth_request_mapper'),
        SocialAuthRequestMapper: () => import('#controllers/auth/mappers/request/social_auth_request_mapper'),
      },
      response: {
        AuthResponseMapper: () => import('#controllers/auth/mappers/response/auth_response_mapper'),
        SocialAuthResponseMapper: () => import('#controllers/auth/mappers/response/social_auth_response_mapper'),
      },
    },
    SocialAuth: () => import('#controllers/auth/social_auth_controller'),
  },
  authorization: {
    RequireSystemUserAdminAccess: () => import('#controllers/authorization/require_system_user_admin_access'),
  },
  errors: {
    Error: () => import('#controllers/errors/error_controller'),
  },
  HealthChecks: () => import('#controllers/health_checks_controller'),
  http: {
    DebugOrganizationInfoApi: () => import('#controllers/http/debug_organization_info_api_controller'),
    Dev: () => import('#controllers/http/dev_controller'),
    GetMeApi: () => import('#controllers/http/get_me_api_controller'),
    GetOrganizationMembersApi: () => import('#controllers/http/get_organization_members_api_controller'),
    GetUsersInOrganizationApi: () => import('#controllers/http/get_users_in_organization_api_controller'),
    RedisClearCache: () => import('#controllers/http/redis_clear_cache_controller'),
    RedisFlushCache: () => import('#controllers/http/redis_flush_cache_controller'),
    RedisGetCache: () => import('#controllers/http/redis_get_cache_controller'),
    RedisListKeys: () => import('#controllers/http/redis_list_keys_controller'),
    RedisSetCache: () => import('#controllers/http/redis_set_cache_controller'),
    RedisTestConnection: () => import('#controllers/http/redis_test_connection_controller'),
  },
  notifications: {
    DeleteNotification: () => import('#controllers/notifications/delete_notification_controller'),
    LatestNotifications: () => import('#controllers/notifications/latest_notifications_controller'),
    ListNotifications: () => import('#controllers/notifications/list_notifications_controller'),
    MarkNotificationRead: () => import('#controllers/notifications/mark_notification_read_controller'),
  },
  organizations: {
    AddDirectMember: () => import('#controllers/organizations/add_direct_member_controller'),
    AddMember: () => import('#controllers/organizations/add_member_controller'),
    AddUsers: () => import('#controllers/organizations/add_users_controller'),
    AllOrganizations: () => import('#controllers/organizations/all_organizations_controller'),
    ApiListOrganizations: () => import('#controllers/organizations/api_list_organizations_controller'),
    CreateOrganization: () => import('#controllers/organizations/create_organization_controller'),
    current: {
      access: {
        mappers: {
          request: {
            UpdateRolesRequestMapper: () => import('#controllers/organizations/current/access/mappers/request/update_roles_request_mapper'),
          },
          response: {
            UpdateRolesResponseMapper: () => import('#controllers/organizations/current/access/mappers/response/update_roles_response_mapper'),
          },
        },
        ShowDepartments: () => import('#controllers/organizations/current/access/show_departments_controller'),
        ShowPermissions: () => import('#controllers/organizations/current/access/show_permissions_controller'),
        ShowRoles: () => import('#controllers/organizations/current/access/show_roles_controller'),
        UpdateRoles: () => import('#controllers/organizations/current/access/update_roles_controller'),
      },
      Dashboard: () => import('#controllers/organizations/current/dashboard_controller'),
      invitations: {
        ApproveJoinRequest: () => import('#controllers/organizations/current/invitations/approve_join_request_controller'),
        ListInvitations: () => import('#controllers/organizations/current/invitations/list_invitations_controller'),
        ListJoinRequests: () => import('#controllers/organizations/current/invitations/list_join_requests_controller'),
        mappers: {
          request: {
            ListInvitationsRequestMapper: () => import('#controllers/organizations/current/invitations/mappers/request/list_invitations_request_mapper'),
          },
          response: {
            ListInvitationsResponseMapper: () => import('#controllers/organizations/current/invitations/mappers/response/list_invitations_response_mapper'),
          },
        },
      },
      mappers: {
        request: {
          CurrentOrganizationMutationRequestMapper: () => import('#controllers/organizations/current/mappers/request/current_organization_mutation_request_mapper'),
        },
        response: {
          CurrentOrganizationMutationResponseMapper: () => import('#controllers/organizations/current/mappers/response/current_organization_mutation_response_mapper'),
          Shared: () => import('#controllers/organizations/current/mappers/response/shared'),
        },
      },
      members: {
        InviteMember: () => import('#controllers/organizations/current/members/invite_member_controller'),
        ListMembers: () => import('#controllers/organizations/current/members/list_members_controller'),
        mappers: {
          request: {
            ListMembersRequestMapper: () => import('#controllers/organizations/current/members/mappers/request/list_members_request_mapper'),
          },
          response: {
            ListMembersResponseMapper: () => import('#controllers/organizations/current/members/mappers/response/list_members_response_mapper'),
          },
        },
        RemoveMember: () => import('#controllers/organizations/current/members/remove_member_controller'),
        UpdateMemberRole: () => import('#controllers/organizations/current/members/update_member_role_controller'),
      },
      projects: {
        CreateProject: () => import('#controllers/organizations/current/projects/create_project_controller'),
        ListProjects: () => import('#controllers/organizations/current/projects/list_projects_controller'),
        mappers: {
          request: {
            CurrentProjectRequestMapper: () => import('#controllers/organizations/current/projects/mappers/request/current_project_request_mapper'),
          },
          response: {
            CurrentProjectResponseMapper: () => import('#controllers/organizations/current/projects/mappers/response/current_project_response_mapper'),
          },
        },
      },
      settings: {
        ShowSettings: () => import('#controllers/organizations/current/settings/show_settings_controller'),
        UpdateSettings: () => import('#controllers/organizations/current/settings/update_settings_controller'),
      },
      tasks: {
        ListTasks: () => import('#controllers/organizations/current/tasks/list_tasks_controller'),
        mappers: {
          request: {
            CurrentTaskRequestMapper: () => import('#controllers/organizations/current/tasks/mappers/request/current_task_request_mapper'),
          },
        },
      },
      workflow: {
        CreateTaskStatus: () => import('#controllers/organizations/current/workflow/create_task_status_controller'),
        ListTaskStatuses: () => import('#controllers/organizations/current/workflow/list_task_statuses_controller'),
        mappers: {
          request: {
            CurrentTaskStatusRequestMapper: () => import('#controllers/organizations/current/workflow/mappers/request/current_task_status_request_mapper'),
          },
          response: {
            CurrentTaskStatusResponseMapper: () => import('#controllers/organizations/current/workflow/mappers/response/current_task_status_response_mapper'),
          },
        },
      },
    },
    InviteMember: () => import('#controllers/organizations/invite_member_controller'),
    JoinOrganization: () => import('#controllers/organizations/join_organization_controller'),
    ListMembers: () => import('#controllers/organizations/list_members_controller'),
    ListOrganizations: () => import('#controllers/organizations/list_organizations_controller'),
    mappers: {
      request: {
        JoinOrganizationRequestMapper: () => import('#controllers/organizations/mappers/request/join_organization_request_mapper'),
        OrganizationRequestMapper: () => import('#controllers/organizations/mappers/request/organization_request_mapper'),
      },
      response: {
        JoinOrganizationResponseMapper: () => import('#controllers/organizations/mappers/response/join_organization_response_mapper'),
        OrganizationMutationApiMapper: () => import('#controllers/organizations/mappers/response/organization_mutation_api_mapper'),
        OrganizationPagePropsMapper: () => import('#controllers/organizations/mappers/response/organization_page_props_mapper'),
        OrganizationResponseMapper: () => import('#controllers/organizations/mappers/response/organization_response_mapper'),
      },
    },
    PendingRequests: () => import('#controllers/organizations/pending_requests_controller'),
    ProcessJoinRequest: () => import('#controllers/organizations/process_join_request_controller'),
    RemoveMember: () => import('#controllers/organizations/remove_member_controller'),
    ShowOrganization: () => import('#controllers/organizations/show_organization_controller'),
    SwitchAndRedirect: () => import('#controllers/organizations/switch_and_redirect_controller'),
    SwitchOrganization: () => import('#controllers/organizations/switch_organization_controller'),
    UpdateMemberRole: () => import('#controllers/organizations/update_member_role_controller'),
  },
  projects: {
    AddProjectMember: () => import('#controllers/projects/add_project_member_controller'),
    CreateProject: () => import('#controllers/projects/create_project_controller'),
    DeleteProjectApi: () => import('#controllers/projects/delete_project_api_controller'),
    DeleteProject: () => import('#controllers/projects/delete_project_controller'),
    GetProjectDetailApi: () => import('#controllers/projects/get_project_detail_api_controller'),
    ListProjects: () => import('#controllers/projects/list_projects_controller'),
    mappers: {
      request: {
        ProjectRequestMapper: () => import('#controllers/projects/mappers/request/project_request_mapper'),
        Shared: () => import('#controllers/projects/mappers/request/shared'),
      },
      response: {
        ProjectResponseMapper: () => import('#controllers/projects/mappers/response/project_response_mapper'),
        Shared: () => import('#controllers/projects/mappers/response/shared'),
      },
    },
    ShowProject: () => import('#controllers/projects/show_project_controller'),
    StoreProject: () => import('#controllers/projects/store_project_controller'),
    UpdateProjectApi: () => import('#controllers/projects/update_project_api_controller'),
  },
  reviews: {
    AddReviewEvidence: () => import('#controllers/reviews/add_review_evidence_controller'),
    ConfirmReview: () => import('#controllers/reviews/confirm_review_controller'),
    CreateReviewSession: () => import('#controllers/reviews/create_review_session_controller'),
    GetReviewEvidences: () => import('#controllers/reviews/get_review_evidences_controller'),
    GetTaskSelfAssessment: () => import('#controllers/reviews/get_task_self_assessment_controller'),
    ListFlaggedReviews: () => import('#controllers/reviews/list_flagged_reviews_controller'),
    ListPendingReviews: () => import('#controllers/reviews/list_pending_reviews_controller'),
    mappers: {
      request: {
        ReviewRequestMapper: () => import('#controllers/reviews/mappers/request/review_request_mapper'),
        Shared: () => import('#controllers/reviews/mappers/request/shared'),
      },
      response: {
        ReviewResponseMapper: () => import('#controllers/reviews/mappers/response/review_response_mapper'),
        Shared: () => import('#controllers/reviews/mappers/response/shared'),
      },
    },
    MyReviews: () => import('#controllers/reviews/my_reviews_controller'),
    ResolveFlaggedReview: () => import('#controllers/reviews/resolve_flagged_review_controller'),
    ShowReview: () => import('#controllers/reviews/show_review_controller'),
    SubmitReverseReview: () => import('#controllers/reviews/submit_reverse_review_controller'),
    SubmitReview: () => import('#controllers/reviews/submit_review_controller'),
    UpsertTaskSelfAssessment: () => import('#controllers/reviews/upsert_task_self_assessment_controller'),
    UserReviews: () => import('#controllers/reviews/user_reviews_controller'),
  },
  settings: {
    mappers: {
      request: {
        SettingsRequestMapper: () => import('#controllers/settings/mappers/request/settings_request_mapper'),
      },
      response: {
        SettingsResponseMapper: () => import('#controllers/settings/mappers/response/settings_response_mapper'),
      },
    },
    ShowSettings: () => import('#controllers/settings/show_settings_controller'),
    UpdateAccountSettings: () => import('#controllers/settings/update_account_settings_controller'),
    UpdateAppearanceSettings: () => import('#controllers/settings/update_appearance_settings_controller'),
    UpdateDisplaySettings: () => import('#controllers/settings/update_display_settings_controller'),
    UpdateNotificationSettings: () => import('#controllers/settings/update_notification_settings_controller'),
    UpdateProfileSettings: () => import('#controllers/settings/update_profile_settings_controller'),
    UpdateSettings: () => import('#controllers/settings/update_settings_controller'),
  },
  tasks: {
    ApplyForTaskApi: () => import('#controllers/tasks/apply_for_task_api_controller'),
    ApplyForTask: () => import('#controllers/tasks/apply_for_task_controller'),
    BatchUpdateTaskStatus: () => import('#controllers/tasks/batch_update_task_status_controller'),
    CheckCreatePermission: () => import('#controllers/tasks/check_create_permission_controller'),
    CreateTask: () => import('#controllers/tasks/create_task_controller'),
    CreateTaskStatus: () => import('#controllers/tasks/create_task_status_controller'),
    DeleteTask: () => import('#controllers/tasks/delete_task_controller'),
    DeleteTaskStatus: () => import('#controllers/tasks/delete_task_status_controller'),
    EditTask: () => import('#controllers/tasks/edit_task_controller'),
    GetTaskAuditLogs: () => import('#controllers/tasks/get_task_audit_logs_controller'),
    ListPublicTasksApi: () => import('#controllers/tasks/list_public_tasks_api_controller'),
    ListPublicTasks: () => import('#controllers/tasks/list_public_tasks_controller'),
    ListTaskApplications: () => import('#controllers/tasks/list_task_applications_controller'),
    ListTaskStatuses: () => import('#controllers/tasks/list_task_statuses_controller'),
    ListTasks: () => import('#controllers/tasks/list_tasks_controller'),
    ListTasksGrouped: () => import('#controllers/tasks/list_tasks_grouped_controller'),
    ListTasksTimeline: () => import('#controllers/tasks/list_tasks_timeline_controller'),
    ListWorkflow: () => import('#controllers/tasks/list_workflow_controller'),
    mappers: {
      request: {
        Shared: () => import('#controllers/tasks/mappers/request/shared'),
        TaskApplicationRequestMapper: () => import('#controllers/tasks/mappers/request/task_application_request_mapper'),
        TaskRequestMapper: () => import('#controllers/tasks/mappers/request/task_request_mapper'),
        TaskStatusRequestMapper: () => import('#controllers/tasks/mappers/request/task_status_request_mapper'),
      },
      response: {
        PublicTaskResponseMapper: () => import('#controllers/tasks/mappers/response/public_task_response_mapper'),
        Shared: () => import('#controllers/tasks/mappers/response/shared'),
        TaskApplicationResponseMapper: () => import('#controllers/tasks/mappers/response/task_application_response_mapper'),
        TaskResponseMapper: () => import('#controllers/tasks/mappers/response/task_response_mapper'),
        TaskStatusResponseMapper: () => import('#controllers/tasks/mappers/response/task_status_response_mapper'),
      },
    },
    MyApplications: () => import('#controllers/tasks/my_applications_controller'),
    PatchTaskStatusBoardPoc: () => import('#controllers/tasks/patch_task_status_board_poc_controller'),
    ProcessApplication: () => import('#controllers/tasks/process_application_controller'),
    ShowTask: () => import('#controllers/tasks/show_task_controller'),
    ShowTaskStatusBoard: () => import('#controllers/tasks/show_task_status_board_controller'),
    UpdateTaskSortOrder: () => import('#controllers/tasks/update_task_sort_order_controller'),
    UpdateTaskStatus: () => import('#controllers/tasks/update_task_status_controller'),
    UpdateTaskStatusDefinition: () => import('#controllers/tasks/update_task_status_definition_controller'),
    UpdateTaskTime: () => import('#controllers/tasks/update_task_time_controller'),
    UpdateWorkflow: () => import('#controllers/tasks/update_workflow_controller'),
    WithdrawApplication: () => import('#controllers/tasks/withdraw_application_controller'),
  },
  users: {
    AddProfileSkill: () => import('#controllers/users/add_profile_skill_controller'),
    ApproveUser: () => import('#controllers/users/approve_user_controller'),
    CreateUser: () => import('#controllers/users/create_user_controller'),
    DeleteUser: () => import('#controllers/users/delete_user_controller'),
    EditProfile: () => import('#controllers/users/edit_profile_controller'),
    EditUser: () => import('#controllers/users/edit_user_controller'),
    GetCurrentProfileSnapshot: () => import('#controllers/users/get_current_profile_snapshot_controller'),
    GetProfileSnapshotHistory: () => import('#controllers/users/get_profile_snapshot_history_controller'),
    GetPublicProfileSnapshot: () => import('#controllers/users/get_public_profile_snapshot_controller'),
    ListUsers: () => import('#controllers/users/list_users_controller'),
    mappers: {
      request: {
        Shared: () => import('#controllers/users/mappers/request/shared'),
        UserRequestMapper: () => import('#controllers/users/mappers/request/user_request_mapper'),
      },
      response: {
        Shared: () => import('#controllers/users/mappers/response/shared'),
        UserResponseMapper: () => import('#controllers/users/mappers/response/user_response_mapper'),
      },
    },
    PendingApprovalCountApi: () => import('#controllers/users/pending_approval_count_api_controller'),
    PendingApprovalUsersApi: () => import('#controllers/users/pending_approval_users_api_controller'),
    PendingApprovalUsers: () => import('#controllers/users/pending_approval_users_controller'),
    PublishProfileSnapshot: () => import('#controllers/users/publish_profile_snapshot_controller'),
    RemoveProfileSkill: () => import('#controllers/users/remove_profile_skill_controller'),
    RotateProfileSnapshotShareLink: () => import('#controllers/users/rotate_profile_snapshot_share_link_controller'),
    ShowProfile: () => import('#controllers/users/show_profile_controller'),
    ShowUser: () => import('#controllers/users/show_user_controller'),
    StoreUser: () => import('#controllers/users/store_user_controller'),
    SystemUsersApi: () => import('#controllers/users/system_users_api_controller'),
    UpdateProfileDetails: () => import('#controllers/users/update_profile_details_controller'),
    UpdateProfileSkill: () => import('#controllers/users/update_profile_skill_controller'),
    UpdateProfileSnapshotAccess: () => import('#controllers/users/update_profile_snapshot_access_controller'),
    UpdateUser: () => import('#controllers/users/update_user_controller'),
    UpdateUserRole: () => import('#controllers/users/update_user_role_controller'),
    ViewUserProfile: () => import('#controllers/users/view_user_profile_controller'),
  },
}
