/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const listeners = {
  ActivityListener: () => import('#listeners/activity_listener'),
  AuditLogListener: () => import('#listeners/audit_log_listener'),
  CacheInvalidationListener: () => import('#listeners/cache_invalidation_listener'),
  CleanupListener: () => import('#listeners/cleanup_listener'),
  NotificationListener: () => import('#listeners/notification_listener'),
  ReviewListener: () => import('#listeners/review_listener'),
  TriggerListeners: () => import('#listeners/trigger_listeners'),
}
