/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AiDisputeEvaluationSchema extends BaseModel {
  static $columns = ['caseFileId', 'completedAt', 'confidenceScore', 'createdAt', 'disputeId', 'errorMessage', 'externalRunId', 'id', 'provider', 'recommendation', 'requestPayload', 'responsePayload', 'status', 'summary'] as const
  $columns = AiDisputeEvaluationSchema.$columns
  @column()
  declare caseFileId: string
  @column.dateTime()
  declare completedAt: DateTime | null
  @column()
  declare confidenceScore: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare disputeId: string
  @column()
  declare errorMessage: string | null
  @column()
  declare externalRunId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare provider: string
  @column()
  declare recommendation: string | null
  @column()
  declare requestPayload: any
  @column()
  declare responsePayload: any
  @column()
  declare status: string
  @column()
  declare summary: string | null
}

export class AiDisputeFeedbackSchema extends BaseModel {
  static $columns = ['adminId', 'adminNotes', 'aiCorrectPoints', 'aiEvaluationId', 'aiMissedPoints', 'aiWasHelpful', 'createdAt', 'disputeId', 'feedbackType', 'finalDecision', 'finalRationale', 'id'] as const
  $columns = AiDisputeFeedbackSchema.$columns
  @column()
  declare adminId: string
  @column()
  declare adminNotes: string | null
  @column()
  declare aiCorrectPoints: any
  @column()
  declare aiEvaluationId: string
  @column()
  declare aiMissedPoints: any
  @column()
  declare aiWasHelpful: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare disputeId: string
  @column()
  declare feedbackType: string
  @column()
  declare finalDecision: string
  @column()
  declare finalRationale: string
  @column({ isPrimary: true })
  declare id: string
}

export class AuditEventSchema extends BaseModel {
  static $columns = ['action', 'createdAt', 'entityId', 'entityType', 'id', 'ipAddress', 'newValues', 'occurredAt', 'oldValues', 'userAgent', 'userId'] as const
  $columns = AuditEventSchema.$columns
  @column()
  declare action: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare entityId: string | null
  @column()
  declare entityType: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column()
  declare newValues: any | null
  @column.dateTime()
  declare occurredAt: DateTime
  @column()
  declare oldValues: any | null
  @column()
  declare userAgent: string | null
  @column()
  declare userId: string | null
}

export class ErrorEventSchema extends BaseModel {
  static $columns = ['actorOrgId', 'actorUserId', 'code', 'correlationId', 'createdAt', 'details', 'id', 'ipAddress', 'message', 'method', 'requestId', 'safeMessage', 'severity', 'status', 'url', 'userAgent'] as const
  $columns = ErrorEventSchema.$columns
  @column()
  declare actorOrgId: string | null
  @column()
  declare actorUserId: string | null
  @column()
  declare code: string
  @column()
  declare correlationId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare details: any | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column()
  declare message: string
  @column()
  declare method: string | null
  @column()
  declare requestId: string | null
  @column()
  declare safeMessage: string | null
  @column()
  declare severity: string
  @column()
  declare status: number
  @column()
  declare url: string | null
  @column()
  declare userAgent: string | null
}

export class FlaggedReviewSchema extends BaseModel {
  static $columns = ['createdAt', 'detectedAt', 'flagType', 'id', 'notes', 'reviewedAt', 'reviewedBy', 'severity', 'skillReviewId', 'status', 'updatedAt'] as const
  $columns = FlaggedReviewSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare detectedAt: DateTime | null
  @column()
  declare flagType: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare notes: string | null
  @column.dateTime()
  declare reviewedAt: DateTime | null
  @column()
  declare reviewedBy: string | null
  @column()
  declare severity: string
  @column()
  declare skillReviewId: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class NotificationSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isRead', 'message', 'metadata', 'readAt', 'relatedEntityId', 'relatedEntityType', 'title', 'type', 'updatedAt', 'userId'] as const
  $columns = NotificationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isRead: boolean
  @column()
  declare message: string
  @column()
  declare metadata: any | null
  @column.dateTime()
  declare readAt: DateTime | null
  @column()
  declare relatedEntityId: string | null
  @column()
  declare relatedEntityType: string | null
  @column()
  declare title: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class OrganizationUserSchema extends BaseModel {
  static $columns = ['createdAt', 'invitedBy', 'orgRole', 'organizationId', 'status', 'updatedAt', 'userId'] as const
  $columns = OrganizationUserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare invitedBy: string | null
  @column()
  declare orgRole: string
  @column({ isPrimary: true })
  declare organizationId: string
  @column()
  declare status: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class OrganizationSchema extends BaseModel {
  static $columns = ['createdAt', 'customRoles', 'deletedAt', 'description', 'id', 'logo', 'name', 'ownerId', 'partnerExpiresAt', 'partnerIsActive', 'partnerType', 'partnerVerificationProof', 'partnerVerifiedAt', 'partnerVerifiedBy', 'plan', 'slug', 'updatedAt', 'website'] as const
  $columns = OrganizationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customRoles: any | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare logo: string | null
  @column()
  declare name: string
  @column()
  declare ownerId: string
  @column.dateTime()
  declare partnerExpiresAt: DateTime | null
  @column()
  declare partnerIsActive: boolean
  @column()
  declare partnerType: string | null
  @column()
  declare partnerVerificationProof: string | null
  @column.dateTime()
  declare partnerVerifiedAt: DateTime | null
  @column()
  declare partnerVerifiedBy: string | null
  @column()
  declare plan: string | null
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare website: string | null
}

export class ProfessionalRoleTemplateSkillSchema extends BaseModel {
  static $columns = ['assessmentCeilingLevelId', 'createdAt', 'id', 'importance', 'isMandatory', 'minimumLevelId', 'roleTemplateId', 'skillId', 'sortOrder', 'targetLevelId', 'updatedAt', 'weight'] as const
  $columns = ProfessionalRoleTemplateSkillSchema.$columns
  @column()
  declare assessmentCeilingLevelId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare importance: string
  @column()
  declare isMandatory: boolean
  @column()
  declare minimumLevelId: string | null
  @column()
  declare roleTemplateId: string
  @column()
  declare skillId: string
  @column()
  declare sortOrder: number
  @column()
  declare targetLevelId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare weight: string
}

export class ProfessionalRoleTemplateSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'description', 'id', 'isActive', 'name', 'updatedAt'] as const
  $columns = ProfessionalRoleTemplateSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProficiencyLevelSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'displayName', 'genericDescription', 'id', 'normalizedValue', 'ordinal', 'scaleId', 'shortName', 'sortOrder', 'updatedAt'] as const
  $columns = ProficiencyLevelSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare displayName: string
  @column()
  declare genericDescription: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare normalizedValue: string
  @column()
  declare ordinal: number
  @column()
  declare scaleId: string
  @column()
  declare shortName: string | null
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProficiencyScaleSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'effectiveFrom', 'effectiveTo', 'id', 'isActive', 'name', 'updatedAt', 'version'] as const
  $columns = ProficiencyScaleSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare effectiveFrom: DateTime | null
  @column.dateTime()
  declare effectiveTo: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare version: number
}

export class ProjectAttachmentSchema extends BaseModel {
  static $columns = ['createdAt', 'fileName', 'filePath', 'fileSize', 'id', 'mimeType', 'projectId', 'updatedAt', 'uploadedBy'] as const
  $columns = ProjectAttachmentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fileName: string
  @column()
  declare filePath: string
  @column()
  declare fileSize: number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mimeType: string | null
  @column()
  declare projectId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare uploadedBy: string | null
}

export class ProjectMemberSchema extends BaseModel {
  static $columns = ['createdAt', 'projectId', 'projectRole', 'userId'] as const
  $columns = ProjectMemberSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare projectId: string
  @column()
  declare projectRole: string
  @column()
  declare userId: string
}

export class ProjectProfessionalRoleSkillSchema extends BaseModel {
  static $columns = ['assessmentCeilingLevelId', 'createdAt', 'id', 'importance', 'isMandatory', 'minimumLevelId', 'notes', 'projectProfessionalRoleId', 'projectSkillId', 'sortOrder', 'targetLevelId', 'updatedAt', 'weight'] as const
  $columns = ProjectProfessionalRoleSkillSchema.$columns
  @column()
  declare assessmentCeilingLevelId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare importance: string
  @column()
  declare isMandatory: boolean
  @column()
  declare minimumLevelId: string | null
  @column()
  declare notes: string | null
  @column()
  declare projectProfessionalRoleId: string
  @column()
  declare projectSkillId: string
  @column()
  declare sortOrder: number
  @column()
  declare targetLevelId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare weight: string
}

export class ProjectProfessionalRoleSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'createdBy', 'description', 'id', 'isActive', 'name', 'projectId', 'sourceTemplateId', 'updatedAt', 'version'] as const
  $columns = ProjectProfessionalRoleSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare projectId: string
  @column()
  declare sourceTemplateId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare version: number
}

export class ProjectSkillSchema extends BaseModel {
  static $columns = ['addedBy', 'createdAt', 'descriptionOverride', 'displayNameOverride', 'id', 'isActive', 'isSelectableForTasks', 'isVisibleInProject', 'projectId', 'rubricVersionId', 'skillId', 'updatedAt'] as const
  $columns = ProjectSkillSchema.$columns
  @column()
  declare addedBy: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descriptionOverride: string | null
  @column()
  declare displayNameOverride: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare isSelectableForTasks: boolean
  @column()
  declare isVisibleInProject: boolean
  @column()
  declare projectId: string
  @column()
  declare rubricVersionId: string | null
  @column()
  declare skillId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProjectSchema extends BaseModel {
  static $columns = ['allowFreelancer', 'approvalRequiredForMembers', 'budget', 'createdAt', 'creatorId', 'customRoles', 'deletedAt', 'description', 'endDate', 'id', 'managerId', 'name', 'organizationId', 'ownerId', 'startDate', 'status', 'tags', 'updatedAt', 'visibility'] as const
  $columns = ProjectSchema.$columns
  @column()
  declare allowFreelancer: boolean
  @column()
  declare approvalRequiredForMembers: boolean
  @column()
  declare budget: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare creatorId: string
  @column()
  declare customRoles: any | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column.dateTime()
  declare endDate: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare managerId: string | null
  @column()
  declare name: string
  @column()
  declare organizationId: string
  @column()
  declare ownerId: string | null
  @column.dateTime()
  declare startDate: DateTime | null
  @column()
  declare status: string
  @column()
  declare tags: any | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare visibility: string
}

export class RecruiterBookmarkSchema extends BaseModel {
  static $columns = ['createdAt', 'folder', 'id', 'notes', 'rating', 'recruiterUserId', 'talentUserId', 'updatedAt'] as const
  $columns = RecruiterBookmarkSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare folder: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare notes: string | null
  @column()
  declare rating: number | null
  @column()
  declare recruiterUserId: string
  @column()
  declare talentUserId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class RememberMeTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'hash', 'id', 'tokenableId', 'updatedAt'] as const
  $columns = RememberMeTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ReverseReviewSchema extends BaseModel {
  static $columns = ['comment', 'createdAt', 'id', 'isAnonymous', 'rating', 'reviewSessionId', 'reviewerId', 'targetId', 'targetType'] as const
  $columns = ReverseReviewSchema.$columns
  @column()
  declare comment: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isAnonymous: boolean
  @column()
  declare rating: number
  @column()
  declare reviewSessionId: string
  @column()
  declare reviewerId: string
  @column()
  declare targetId: string
  @column()
  declare targetType: string
}

export class ReviewDisputeCaseFileSchema extends BaseModel {
  static $columns = ['acceptanceCriteriaSnapshot', 'assignmentSnapshot', 'caseVersion', 'completenessScore', 'createdAt', 'createdBy', 'disputeClaimSnapshot', 'disputeId', 'evidencesSnapshot', 'id', 'missingData', 'requiredSkillsSnapshot', 'reviewSnapshot', 'revieweeProfileContextSnapshot', 'reviewerContextSnapshot', 'selfAssessmentSnapshot', 'skillReviewsSnapshot', 'submissionSnapshot', 'taskCommentsSnapshot', 'taskHistorySnapshot', 'taskSnapshot'] as const
  $columns = ReviewDisputeCaseFileSchema.$columns
  @column()
  declare acceptanceCriteriaSnapshot: any
  @column()
  declare assignmentSnapshot: any
  @column()
  declare caseVersion: number
  @column()
  declare completenessScore: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string | null
  @column()
  declare disputeClaimSnapshot: any
  @column()
  declare disputeId: string
  @column()
  declare evidencesSnapshot: any
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare missingData: any
  @column()
  declare requiredSkillsSnapshot: any
  @column()
  declare reviewSnapshot: any
  @column()
  declare revieweeProfileContextSnapshot: any
  @column()
  declare reviewerContextSnapshot: any
  @column()
  declare selfAssessmentSnapshot: any
  @column()
  declare skillReviewsSnapshot: any
  @column()
  declare submissionSnapshot: any
  @column()
  declare taskCommentsSnapshot: any
  @column()
  declare taskHistorySnapshot: any
  @column()
  declare taskSnapshot: any
}

export class ReviewDisputeCommentSchema extends BaseModel {
  static $columns = ['authorId', 'body', 'createdAt', 'deletedAt', 'disputeId', 'id', 'updatedAt', 'visibility'] as const
  $columns = ReviewDisputeCommentSchema.$columns
  @column()
  declare authorId: string
  @column()
  declare body: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare disputeId: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare visibility: string
}

export class ReviewDisputeEvidenceSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'disputeId', 'evidenceType', 'id', 'title', 'uploadedBy', 'url'] as const
  $columns = ReviewDisputeEvidenceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare disputeId: string
  @column()
  declare evidenceType: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare title: string | null
  @column()
  declare uploadedBy: string
  @column()
  declare url: string
}

export class ReviewDisputeSchema extends BaseModel {
  static $columns = ['createdAt', 'disputeReason', 'disputedDimensions', 'disputedSkillReviews', 'finalDecision', 'finalRationale', 'id', 'openedBy', 'profileUpdateAction', 'requestedOutcome', 'resolvedAt', 'resolvedBy', 'reviewSessionId', 'revieweeId', 'reviewerCredibilityAction', 'status', 'taskAssignmentId', 'taskId', 'updatedAt'] as const
  $columns = ReviewDisputeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare disputeReason: string
  @column()
  declare disputedDimensions: any
  @column()
  declare disputedSkillReviews: any
  @column()
  declare finalDecision: string | null
  @column()
  declare finalRationale: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare openedBy: string
  @column()
  declare profileUpdateAction: string | null
  @column()
  declare requestedOutcome: string
  @column.dateTime()
  declare resolvedAt: DateTime | null
  @column()
  declare resolvedBy: string | null
  @column()
  declare reviewSessionId: string
  @column()
  declare revieweeId: string
  @column()
  declare reviewerCredibilityAction: string | null
  @column()
  declare status: string
  @column()
  declare taskAssignmentId: string
  @column()
  declare taskId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ReviewEvidenceSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'evidenceType', 'id', 'reviewSessionId', 'title', 'updatedAt', 'uploadedBy', 'url'] as const
  $columns = ReviewEvidenceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare evidenceType: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare reviewSessionId: string
  @column()
  declare title: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare uploadedBy: string | null
  @column()
  declare url: string | null
}

export class ReviewSessionSchema extends BaseModel {
  static $columns = ['areasForImprovement', 'codeQualityScore', 'communicationQuality', 'completedAt', 'confirmations', 'createdAt', 'deadline', 'deliveryTimeliness', 'id', 'managerReviewCompleted', 'overallQualityScore', 'peerReviewsCount', 'proactivenessScore', 'requiredPeerReviews', 'requirementAdherence', 'revieweeId', 'status', 'strengthsObserved', 'taskAssignmentId', 'updatedAt', 'wouldWorkWithAgain'] as const
  $columns = ReviewSessionSchema.$columns
  @column()
  declare areasForImprovement: string | null
  @column()
  declare codeQualityScore: number | null
  @column()
  declare communicationQuality: number | null
  @column.dateTime()
  declare completedAt: DateTime | null
  @column()
  declare confirmations: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deadline: DateTime | null
  @column()
  declare deliveryTimeliness: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare managerReviewCompleted: boolean
  @column()
  declare overallQualityScore: number | null
  @column()
  declare peerReviewsCount: number
  @column()
  declare proactivenessScore: number | null
  @column()
  declare requiredPeerReviews: number
  @column()
  declare requirementAdherence: number | null
  @column()
  declare revieweeId: string
  @column()
  declare status: string
  @column()
  declare strengthsObserved: string | null
  @column()
  declare taskAssignmentId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare wouldWorkWithAgain: boolean | null
}

export class SkillAliasSchema extends BaseModel {
  static $columns = ['alias', 'createdAt', 'id', 'isPrimary', 'locale', 'normalizedAlias', 'skillId', 'source', 'updatedAt'] as const
  $columns = SkillAliasSchema.$columns
  @column()
  declare alias: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isPrimary: boolean
  @column()
  declare locale: string
  @column()
  declare normalizedAlias: string
  @column()
  declare skillId: string
  @column()
  declare source: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SkillReviewEvidenceLinkSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'relevanceType', 'reviewEvidenceId', 'reviewerNote', 'skillReviewId'] as const
  $columns = SkillReviewEvidenceLinkSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare relevanceType: string
  @column()
  declare reviewEvidenceId: string
  @column()
  declare reviewerNote: string | null
  @column()
  declare skillReviewId: string
}

export class SkillReviewSchema extends BaseModel {
  static $columns = ['assignedLevelCode', 'comment', 'confidence', 'createdAt', 'id', 'isFraud', 'observableBehaviors', 'observedLevelId', 'proficiencyLevelId', 'rationale', 'reviewSessionId', 'reviewStatus', 'reviewerId', 'reviewerType', 'rubricVersionId', 'skillId', 'submittedAt', 'supersededBy', 'updatedAt'] as const
  $columns = SkillReviewSchema.$columns
  @column()
  declare assignedLevelCode: string
  @column()
  declare comment: string | null
  @column()
  declare confidence: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isFraud: boolean
  @column()
  declare observableBehaviors: any | null
  @column()
  declare observedLevelId: string | null
  @column()
  declare proficiencyLevelId: string | null
  @column()
  declare rationale: string | null
  @column()
  declare reviewSessionId: string
  @column()
  declare reviewStatus: string
  @column()
  declare reviewerId: string
  @column()
  declare reviewerType: string
  @column()
  declare rubricVersionId: string | null
  @column()
  declare skillId: string
  @column.dateTime()
  declare submittedAt: DateTime | null
  @column()
  declare supersededBy: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SkillRubricLevelSchema extends BaseModel {
  static $columns = ['complexityExpectations', 'createdAt', 'evidenceGuidance', 'id', 'impactScopeExpectations', 'independenceExpectations', 'knowledgeExpectations', 'negativeExamples', 'observableBehaviors', 'positiveExamples', 'proficiencyLevelId', 'rubricVersionId', 'summary', 'updatedAt'] as const
  $columns = SkillRubricLevelSchema.$columns
  @column()
  declare complexityExpectations: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare evidenceGuidance: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare impactScopeExpectations: string | null
  @column()
  declare independenceExpectations: string | null
  @column()
  declare knowledgeExpectations: any | null
  @column()
  declare negativeExamples: any | null
  @column()
  declare observableBehaviors: any | null
  @column()
  declare positiveExamples: any | null
  @column()
  declare proficiencyLevelId: string
  @column()
  declare rubricVersionId: string
  @column()
  declare summary: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SkillRubricVersionSchema extends BaseModel {
  static $columns = ['changeSummary', 'createdAt', 'createdBy', 'effectiveFrom', 'effectiveTo', 'id', 'skillId', 'status', 'updatedAt', 'version'] as const
  $columns = SkillRubricVersionSchema.$columns
  @column()
  declare changeSummary: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string | null
  @column.dateTime()
  declare effectiveFrom: DateTime | null
  @column.dateTime()
  declare effectiveTo: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare skillId: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare version: number
}

export class SkillSchema extends BaseModel {
  static $columns = ['categoryCode', 'createdAt', 'description', 'displayType', 'iconUrl', 'id', 'isActive', 'skillCode', 'skillName', 'sortOrder', 'updatedAt'] as const
  $columns = SkillSchema.$columns
  @column()
  declare categoryCode: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare displayType: string
  @column()
  declare iconUrl: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare skillCode: string
  @column()
  declare skillName: string
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TaskApplicationSchema extends BaseModel {
  static $columns = ['applicantId', 'applicationSource', 'applicationStatus', 'appliedAt', 'expectedRate', 'id', 'message', 'portfolioLinks', 'rejectionReason', 'reviewedAt', 'reviewedBy', 'taskId'] as const
  $columns = TaskApplicationSchema.$columns
  @column()
  declare applicantId: string
  @column()
  declare applicationSource: string
  @column()
  declare applicationStatus: string
  @column.dateTime()
  declare appliedAt: DateTime | null
  @column()
  declare expectedRate: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare message: string | null
  @column()
  declare portfolioLinks: any | null
  @column()
  declare rejectionReason: string | null
  @column.dateTime()
  declare reviewedAt: DateTime | null
  @column()
  declare reviewedBy: string | null
  @column()
  declare taskId: string
}

export class TaskAssignmentSnapshotSchema extends BaseModel {
  static $columns = ['acceptanceCriteriaSnapshot', 'createdAt', 'id', 'requiredSkillsSnapshot', 'snapshotReason', 'taskAssignmentId', 'taskId', 'taskSnapshot', 'workflowSnapshot'] as const
  $columns = TaskAssignmentSnapshotSchema.$columns
  @column()
  declare acceptanceCriteriaSnapshot: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare requiredSkillsSnapshot: any
  @column()
  declare snapshotReason: string
  @column()
  declare taskAssignmentId: string
  @column()
  declare taskId: string
  @column()
  declare taskSnapshot: any
  @column()
  declare workflowSnapshot: any
}

export class TaskAssignmentSchema extends BaseModel {
  static $columns = ['actualHours', 'assignedAt', 'assignedBy', 'assigneeId', 'assignmentStatus', 'assignmentType', 'completedAt', 'completionNotes', 'estimatedHours', 'id', 'progressPercentage', 'taskId', 'verifiedAt', 'verifiedBy'] as const
  $columns = TaskAssignmentSchema.$columns
  @column()
  declare actualHours: string | null
  @column.dateTime()
  declare assignedAt: DateTime | null
  @column()
  declare assignedBy: string
  @column()
  declare assigneeId: string
  @column()
  declare assignmentStatus: string
  @column()
  declare assignmentType: string
  @column.dateTime()
  declare completedAt: DateTime | null
  @column()
  declare completionNotes: string | null
  @column()
  declare estimatedHours: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare progressPercentage: number
  @column()
  declare taskId: string
  @column.dateTime()
  declare verifiedAt: DateTime | null
  @column()
  declare verifiedBy: string | null
}

export class TaskAttachmentSchema extends BaseModel {
  static $columns = ['attachmentType', 'createdAt', 'deletedAt', 'fileName', 'filePath', 'fileSize', 'id', 'mimeType', 'taskId', 'uploadedBy'] as const
  $columns = TaskAttachmentSchema.$columns
  @column()
  declare attachmentType: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare fileName: string
  @column()
  declare filePath: string
  @column()
  declare fileSize: number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mimeType: string | null
  @column()
  declare taskId: string
  @column()
  declare uploadedBy: string
}

export class TaskCommentSchema extends BaseModel {
  static $columns = ['authorId', 'body', 'commentType', 'createdAt', 'deletedAt', 'id', 'parentCommentId', 'taskId', 'updatedAt', 'visibility'] as const
  $columns = TaskCommentSchema.$columns
  @column()
  declare authorId: string
  @column()
  declare body: string
  @column()
  declare commentType: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare parentCommentId: string | null
  @column()
  declare taskId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare visibility: string
}

export class TaskRequiredSkillSchema extends BaseModel {
  static $columns = ['assessmentCeilingLevelId', 'createdAt', 'id', 'importance', 'isMandatory', 'minimumLevelId', 'proficiencyLevelId', 'projectSkillId', 'requiredLevelCode', 'requirementNotes', 'requirementSource', 'rubricVersionId', 'skillId', 'sourceProjectProfessionalRoleId', 'sourceRoleSkillId', 'targetLevelId', 'taskId', 'weight'] as const
  $columns = TaskRequiredSkillSchema.$columns
  @column()
  declare assessmentCeilingLevelId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare importance: string
  @column()
  declare isMandatory: boolean
  @column()
  declare minimumLevelId: string | null
  @column()
  declare proficiencyLevelId: string | null
  @column()
  declare projectSkillId: string | null
  @column()
  declare requiredLevelCode: string
  @column()
  declare requirementNotes: string | null
  @column()
  declare requirementSource: string
  @column()
  declare rubricVersionId: string | null
  @column()
  declare skillId: string
  @column()
  declare sourceProjectProfessionalRoleId: string | null
  @column()
  declare sourceRoleSkillId: string | null
  @column()
  declare targetLevelId: string | null
  @column()
  declare taskId: string
  @column()
  declare weight: string
}

export class TaskRequirementVersionItemSchema extends BaseModel {
  static $columns = ['assessmentCeilingLevelId', 'createdAt', 'id', 'importance', 'isMandatory', 'minimumLevelId', 'projectSkillId', 'requiredLevelCode', 'requirementNotes', 'requirementSource', 'requirementVersionId', 'rubricVersionId', 'skillId', 'targetLevelId', 'weight'] as const
  $columns = TaskRequirementVersionItemSchema.$columns
  @column()
  declare assessmentCeilingLevelId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare importance: string
  @column()
  declare isMandatory: boolean
  @column()
  declare minimumLevelId: string | null
  @column()
  declare projectSkillId: string | null
  @column()
  declare requiredLevelCode: string | null
  @column()
  declare requirementNotes: string | null
  @column()
  declare requirementSource: string
  @column()
  declare requirementVersionId: string
  @column()
  declare rubricVersionId: string | null
  @column()
  declare skillId: string
  @column()
  declare targetLevelId: string | null
  @column()
  declare weight: string
}

export class TaskRequirementVersionSchema extends BaseModel {
  static $columns = ['createdAt', 'createdBy', 'id', 'professionalRoleSnapshot', 'reason', 'taskId', 'versionNumber'] as const
  $columns = TaskRequirementVersionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare professionalRoleSnapshot: any | null
  @column()
  declare reason: string
  @column()
  declare taskId: string
  @column()
  declare versionNumber: number
}

export class TaskSelfAssessmentSchema extends BaseModel {
  static $columns = ['blockersEncountered', 'confidenceLevel', 'createdAt', 'difficultyFelt', 'id', 'overallSatisfaction', 'skillsFeltLacking', 'skillsFeltStrong', 'submittedAt', 'taskAssignmentId', 'updatedAt', 'userId', 'whatWentWell', 'whatWouldDoDifferent'] as const
  $columns = TaskSelfAssessmentSchema.$columns
  @column()
  declare blockersEncountered: any
  @column()
  declare confidenceLevel: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare difficultyFelt: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare overallSatisfaction: number | null
  @column()
  declare skillsFeltLacking: any
  @column()
  declare skillsFeltStrong: any
  @column.dateTime()
  declare submittedAt: DateTime
  @column()
  declare taskAssignmentId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
  @column()
  declare whatWentWell: string | null
  @column()
  declare whatWouldDoDifferent: string | null
}

export class TaskStatusSchema extends BaseModel {
  static $columns = ['category', 'color', 'createdAt', 'deletedAt', 'description', 'icon', 'id', 'isDefault', 'isSystem', 'name', 'organizationId', 'slug', 'sortOrder', 'updatedAt'] as const
  $columns = TaskStatusSchema.$columns
  @column()
  declare category: any
  @column()
  declare color: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare icon: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isDefault: boolean
  @column()
  declare isSystem: boolean
  @column()
  declare name: string
  @column()
  declare organizationId: string
  @column()
  declare slug: string
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TaskSubmissionEvidenceSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'evidenceType', 'id', 'submissionId', 'title', 'uploadedBy', 'url'] as const
  $columns = TaskSubmissionEvidenceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare evidenceType: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare submissionId: string
  @column()
  declare title: string | null
  @column()
  declare uploadedBy: string
  @column()
  declare url: string
}

export class TaskSubmissionSchema extends BaseModel {
  static $columns = ['createdAt', 'demoUrl', 'id', 'implementationNotes', 'knownLimitations', 'lockedAt', 'pullRequestUrl', 'repositoryUrl', 'status', 'submittedAt', 'submittedBy', 'summary', 'taskAssignmentId', 'taskId', 'testNotes', 'updatedAt'] as const
  $columns = TaskSubmissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare demoUrl: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare implementationNotes: string | null
  @column()
  declare knownLimitations: string | null
  @column.dateTime()
  declare lockedAt: DateTime | null
  @column()
  declare pullRequestUrl: string | null
  @column()
  declare repositoryUrl: string | null
  @column()
  declare status: string
  @column.dateTime()
  declare submittedAt: DateTime | null
  @column()
  declare submittedBy: string
  @column()
  declare summary: string
  @column()
  declare taskAssignmentId: string
  @column()
  declare taskId: string
  @column()
  declare testNotes: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TaskVersionSchema extends BaseModel {
  static $columns = ['assignedTo', 'changedAt', 'changedBy', 'description', 'difficulty', 'id', 'label', 'priority', 'status', 'taskId', 'title'] as const
  $columns = TaskVersionSchema.$columns
  @column()
  declare assignedTo: string | null
  @column.dateTime()
  declare changedAt: DateTime
  @column()
  declare changedBy: string
  @column()
  declare description: string | null
  @column()
  declare difficulty: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare label: string
  @column()
  declare priority: string
  @column()
  declare status: string
  @column()
  declare taskId: string
  @column()
  declare title: string
}

export class TaskWorkflowTransitionSchema extends BaseModel {
  static $columns = ['conditions', 'createdAt', 'fromStatusId', 'id', 'organizationId', 'toStatusId'] as const
  $columns = TaskWorkflowTransitionSchema.$columns
  @column()
  declare conditions: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fromStatusId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare organizationId: string
  @column()
  declare toStatusId: string
}

export class TaskSchema extends BaseModel {
  static $columns = ['acceptanceCriteria', 'actualTime', 'applicationDeadline', 'assignedTo', 'autonomyLevel', 'businessDomain', 'collaborationType', 'complexityNotes', 'contextBackground', 'createdAt', 'creatorId', 'deletedAt', 'description', 'difficulty', 'domainTags', 'dueDate', 'environment', 'estimatedBudget', 'estimatedTime', 'estimatedUsersAffected', 'expectedDeliverables', 'externalApplicationsCount', 'id', 'impactScope', 'label', 'learningObjectives', 'measurableOutcomes', 'organizationId', 'parentTaskId', 'priority', 'problemCategory', 'projectId', 'roleInTask', 'sortOrder', 'status', 'taskStatusId', 'taskType', 'taskVisibility', 'techStack', 'title', 'updatedAt', 'updatedBy', 'verificationMethod'] as const
  $columns = TaskSchema.$columns
  @column()
  declare acceptanceCriteria: string
  @column()
  declare actualTime: string | null
  @column.dateTime()
  declare applicationDeadline: DateTime | null
  @column()
  declare assignedTo: string | null
  @column()
  declare autonomyLevel: string | null
  @column()
  declare businessDomain: string | null
  @column()
  declare collaborationType: string | null
  @column()
  declare complexityNotes: string | null
  @column()
  declare contextBackground: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare creatorId: string
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string
  @column()
  declare difficulty: string | null
  @column()
  declare domainTags: any
  @column.dateTime()
  declare dueDate: DateTime
  @column()
  declare environment: string | null
  @column()
  declare estimatedBudget: string | null
  @column()
  declare estimatedTime: string | null
  @column()
  declare estimatedUsersAffected: number | null
  @column()
  declare expectedDeliverables: any
  @column()
  declare externalApplicationsCount: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare impactScope: string | null
  @column()
  declare label: string
  @column()
  declare learningObjectives: any
  @column()
  declare measurableOutcomes: any
  @column()
  declare organizationId: string
  @column()
  declare parentTaskId: string | null
  @column()
  declare priority: string
  @column()
  declare problemCategory: string | null
  @column()
  declare projectId: string
  @column()
  declare roleInTask: string | null
  @column()
  declare sortOrder: number
  @column()
  declare status: string
  @column()
  declare taskStatusId: string
  @column()
  declare taskType: string
  @column()
  declare taskVisibility: string
  @column()
  declare techStack: any
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare updatedBy: string | null
  @column()
  declare verificationMethod: string
}

export class UserActivityEventSchema extends BaseModel {
  static $columns = ['actionData', 'actionType', 'createdAt', 'id', 'ipAddress', 'relatedEntityId', 'relatedEntityType', 'userAgent', 'userId'] as const
  $columns = UserActivityEventSchema.$columns
  @column()
  declare actionData: any | null
  @column()
  declare actionType: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column()
  declare relatedEntityId: string | null
  @column()
  declare relatedEntityType: string | null
  @column()
  declare userAgent: string | null
  @column()
  declare userId: string
}

export class UserDomainExpertiseSchema extends BaseModel {
  static $columns = ['calculatedAt', 'createdAt', 'domainFrequency', 'id', 'problemCategoryFrequency', 'techStackFrequency', 'topSkills', 'updatedAt', 'userId'] as const
  $columns = UserDomainExpertiseSchema.$columns
  @column.dateTime()
  declare calculatedAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare domainFrequency: any
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare problemCategoryFrequency: any
  @column()
  declare techStackFrequency: any
  @column()
  declare topSkills: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class UserOauthProviderSchema extends BaseModel {
  static $columns = ['accessToken', 'createdAt', 'email', 'id', 'provider', 'providerId', 'refreshToken', 'updatedAt', 'userId'] as const
  $columns = UserOauthProviderSchema.$columns
  @column()
  declare accessToken: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare provider: string
  @column()
  declare providerId: string
  @column()
  declare refreshToken: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class UserPerformanceStatSchema extends BaseModel {
  static $columns = ['avgDaysEarlyOrLate', 'avgQualityScore', 'calculatedAt', 'createdAt', 'currentOnTimeStreak', 'id', 'longestOnTimeStreak', 'onTimeDeliveryRate', 'performanceScore', 'periodEnd', 'periodStart', 'selfAssessmentAccuracy', 'tasksAsLead', 'tasksAsSoleContributor', 'tasksByDifficulty', 'tasksByDomain', 'tasksByType', 'tasksMentoringOthers', 'totalHoursWorked', 'totalTasksCompleted', 'updatedAt', 'userId'] as const
  $columns = UserPerformanceStatSchema.$columns
  @column()
  declare avgDaysEarlyOrLate: string | null
  @column()
  declare avgQualityScore: string | null
  @column.dateTime()
  declare calculatedAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currentOnTimeStreak: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare longestOnTimeStreak: number
  @column()
  declare onTimeDeliveryRate: string | null
  @column()
  declare performanceScore: string | null
  @column.dateTime()
  declare periodEnd: DateTime | null
  @column.dateTime()
  declare periodStart: DateTime | null
  @column()
  declare selfAssessmentAccuracy: string | null
  @column()
  declare tasksAsLead: number
  @column()
  declare tasksAsSoleContributor: number
  @column()
  declare tasksByDifficulty: any
  @column()
  declare tasksByDomain: any
  @column()
  declare tasksByType: any
  @column()
  declare tasksMentoringOthers: number
  @column()
  declare totalHoursWorked: string
  @column()
  declare totalTasksCompleted: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class UserProfileSnapshotSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isCurrent', 'isPublic', 'performanceMetrics', 'scoringVersion', 'shareableSlug', 'shareableToken', 'skillsVerified', 'snapshotName', 'summary', 'trustMetrics', 'updatedAt', 'userId', 'version', 'workHighlights'] as const
  $columns = UserProfileSnapshotSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isCurrent: boolean
  @column()
  declare isPublic: boolean
  @column()
  declare performanceMetrics: any
  @column()
  declare scoringVersion: string
  @column()
  declare shareableSlug: string | null
  @column()
  declare shareableToken: string | null
  @column()
  declare skillsVerified: any
  @column()
  declare snapshotName: string | null
  @column()
  declare summary: any
  @column()
  declare trustMetrics: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
  @column()
  declare version: number
  @column()
  declare workHighlights: any
}

export class UserSkillSchema extends BaseModel {
  static $columns = ['avgPercentage', 'avgScore', 'createdAt', 'id', 'lastCalculatedAt', 'lastReviewedAt', 'levelCode', 'proficiencyLevelId', 'skillId', 'source', 'totalReviews', 'updatedAt', 'userId'] as const
  $columns = UserSkillSchema.$columns
  @column()
  declare avgPercentage: string | null
  @column()
  declare avgScore: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastCalculatedAt: DateTime | null
  @column.dateTime()
  declare lastReviewedAt: DateTime | null
  @column()
  declare levelCode: string
  @column()
  declare proficiencyLevelId: string | null
  @column()
  declare skillId: string
  @column()
  declare source: string | null
  @column()
  declare totalReviews: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class UserSubscriptionSchema extends BaseModel {
  static $columns = ['autoRenew', 'createdAt', 'expiresAt', 'id', 'plan', 'startedAt', 'status', 'updatedAt', 'userId'] as const
  $columns = UserSubscriptionSchema.$columns
  @column()
  declare autoRenew: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare plan: string
  @column.dateTime()
  declare startedAt: DateTime
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class UserWorkHistorySchema extends BaseModel {
  static $columns = ['actualHours', 'autonomyLevel', 'businessDomain', 'collaborationType', 'completedAt', 'createdAt', 'daysEarlyOrLate', 'difficulty', 'domainTags', 'estimatedBusinessValue', 'estimatedHours', 'evidenceLinks', 'id', 'isFeatured', 'isPublic', 'knowledgeArtifacts', 'measurableOutcomes', 'organizationId', 'overallQualityScore', 'problemCategory', 'projectId', 'roleInTask', 'skillScores', 'taskAssignmentId', 'taskId', 'taskTitle', 'taskType', 'techStack', 'updatedAt', 'userId', 'wasOnTime'] as const
  $columns = UserWorkHistorySchema.$columns
  @column()
  declare actualHours: string | null
  @column()
  declare autonomyLevel: string | null
  @column()
  declare businessDomain: string | null
  @column()
  declare collaborationType: string | null
  @column.dateTime()
  declare completedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare daysEarlyOrLate: number | null
  @column()
  declare difficulty: string | null
  @column()
  declare domainTags: any
  @column()
  declare estimatedBusinessValue: string | null
  @column()
  declare estimatedHours: string | null
  @column()
  declare evidenceLinks: any
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isFeatured: boolean
  @column()
  declare isPublic: boolean
  @column()
  declare knowledgeArtifacts: any
  @column()
  declare measurableOutcomes: any
  @column()
  declare organizationId: string | null
  @column()
  declare overallQualityScore: string | null
  @column()
  declare problemCategory: string | null
  @column()
  declare projectId: string | null
  @column()
  declare roleInTask: string | null
  @column()
  declare skillScores: any
  @column()
  declare taskAssignmentId: string
  @column()
  declare taskId: string
  @column()
  declare taskTitle: string
  @column()
  declare taskType: string | null
  @column()
  declare techStack: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
  @column()
  declare wasOnTime: boolean | null
}

export class UserSchema extends BaseModel {
  static $columns = ['address', 'authMethod', 'avatarUrl', 'bio', 'createdAt', 'credibilityData', 'currentOrganizationId', 'deletedAt', 'email', 'freelancerCompletedTasksCount', 'freelancerRating', 'id', 'isFreelancer', 'isVerifiedBadge', 'language', 'phone', 'profileSettings', 'rankingPriority', 'status', 'systemRole', 'timezone', 'trustData', 'updatedAt', 'userSetting', 'username'] as const
  $columns = UserSchema.$columns
  @column()
  declare address: string | null
  @column()
  declare authMethod: string | null
  @column()
  declare avatarUrl: string | null
  @column()
  declare bio: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare credibilityData: any | null
  @column()
  declare currentOrganizationId: string | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string | null
  @column()
  declare freelancerCompletedTasksCount: number | null
  @column()
  declare freelancerRating: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isFreelancer: boolean | null
  @column()
  declare isVerifiedBadge: boolean | null
  @column()
  declare language: string | null
  @column()
  declare phone: string | null
  @column()
  declare profileSettings: any | null
  @column()
  declare rankingPriority: number | null
  @column()
  declare status: string
  @column()
  declare systemRole: string
  @column()
  declare timezone: string | null
  @column()
  declare trustData: any | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userSetting: any | null
  @column()
  declare username: string
}
