/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class FlaggedReviewSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'detectedAt',
    'flagType',
    'id',
    'notes',
    'reviewedAt',
    'reviewedBy',
    'severity',
    'skillReviewId',
    'status',
    'updatedAt',
  ] as const
  $columns = FlaggedReviewSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare detectedAt: DateTime | null
  @column()
  declare flagType: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare notes: string | null
  @column.dateTime()
  declare reviewedAt: DateTime | null
  @column()
  declare reviewedBy: string | null
  @column()
  declare severity: string
  @column()
  declare skillReviewId: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OrganizationUserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'invitedBy',
    'orgRole',
    'organizationId',
    'status',
    'updatedAt',
    'userId',
  ] as const
  $columns = OrganizationUserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare invitedBy: string | null
  @column()
  declare orgRole: string
  @column({ isPrimary: true })
  declare organizationId: string
  @column()
  declare status: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class OrganizationSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'customRoles',
    'deletedAt',
    'description',
    'id',
    'logo',
    'name',
    'ownerId',
    'partnerExpiresAt',
    'partnerIsActive',
    'partnerType',
    'partnerVerificationProof',
    'partnerVerifiedAt',
    'partnerVerifiedBy',
    'plan',
    'slug',
    'updatedAt',
    'website',
  ] as const
  $columns = OrganizationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customRoles: any | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare logo: string | null
  @column()
  declare name: string
  @column()
  declare ownerId: string
  @column.dateTime()
  declare partnerExpiresAt: DateTime | null
  @column()
  declare partnerIsActive: boolean
  @column()
  declare partnerType: string | null
  @column()
  declare partnerVerificationProof: string | null
  @column.dateTime()
  declare partnerVerifiedAt: DateTime | null
  @column()
  declare partnerVerifiedBy: string | null
  @column()
  declare plan: string | null
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare website: string | null
}

export class ProjectAttachmentSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'fileName',
    'filePath',
    'fileSize',
    'id',
    'mimeType',
    'projectId',
    'updatedAt',
    'uploadedBy',
  ] as const
  $columns = ProjectAttachmentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fileName: string
  @column()
  declare filePath: string
  @column()
  declare fileSize: number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mimeType: string | null
  @column()
  declare projectId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare uploadedBy: string | null
}

export class ProjectMemberSchema extends BaseModel {
  static $columns = ['createdAt', 'projectId', 'projectRole', 'userId'] as const
  $columns = ProjectMemberSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare projectId: string
  @column()
  declare projectRole: string
  @column()
  declare userId: string
}

export class ProjectSchema extends BaseModel {
  static $columns = [
    'allowFreelancer',
    'approvalRequiredForMembers',
    'budget',
    'createdAt',
    'creatorId',
    'customRoles',
    'deletedAt',
    'description',
    'endDate',
    'id',
    'managerId',
    'name',
    'organizationId',
    'ownerId',
    'startDate',
    'status',
    'tags',
    'updatedAt',
    'visibility',
  ] as const
  $columns = ProjectSchema.$columns
  @column()
  declare allowFreelancer: boolean
  @column()
  declare approvalRequiredForMembers: boolean
  @column()
  declare budget: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare creatorId: string
  @column()
  declare customRoles: any | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column.dateTime()
  declare endDate: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare managerId: string | null
  @column()
  declare name: string
  @column()
  declare organizationId: string
  @column()
  declare ownerId: string | null
  @column.dateTime()
  declare startDate: DateTime | null
  @column()
  declare status: string
  @column()
  declare tags: any | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare visibility: string
}

export class RecruiterBookmarkSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'folder',
    'id',
    'notes',
    'rating',
    'recruiterUserId',
    'talentUserId',
    'updatedAt',
  ] as const
  $columns = RecruiterBookmarkSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare folder: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare notes: string | null
  @column()
  declare rating: number | null
  @column()
  declare recruiterUserId: string
  @column()
  declare talentUserId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class RememberMeTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'hash', 'id', 'tokenableId', 'updatedAt'] as const
  $columns = RememberMeTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ReverseReviewSchema extends BaseModel {
  static $columns = [
    'comment',
    'createdAt',
    'id',
    'isAnonymous',
    'rating',
    'reviewSessionId',
    'reviewerId',
    'targetId',
    'targetType',
  ] as const
  $columns = ReverseReviewSchema.$columns
  @column()
  declare comment: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isAnonymous: boolean
  @column()
  declare rating: number
  @column()
  declare reviewSessionId: string
  @column()
  declare reviewerId: string
  @column()
  declare targetId: string
  @column()
  declare targetType: string
}

export class ReviewEvidenceSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'description',
    'evidenceType',
    'id',
    'reviewSessionId',
    'title',
    'updatedAt',
    'uploadedBy',
    'url',
  ] as const
  $columns = ReviewEvidenceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare evidenceType: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare reviewSessionId: string
  @column()
  declare title: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare uploadedBy: string | null
  @column()
  declare url: string | null
}

export class ReviewSessionSchema extends BaseModel {
  static $columns = [
    'areasForImprovement',
    'codeQualityScore',
    'communicationQuality',
    'completedAt',
    'confirmations',
    'createdAt',
    'deadline',
    'deliveryTimeliness',
    'id',
    'managerReviewCompleted',
    'overallQualityScore',
    'peerReviewsCount',
    'proactivenessScore',
    'requiredPeerReviews',
    'requirementAdherence',
    'revieweeId',
    'status',
    'strengthsObserved',
    'taskAssignmentId',
    'updatedAt',
    'wouldWorkWithAgain',
  ] as const
  $columns = ReviewSessionSchema.$columns
  @column()
  declare areasForImprovement: string | null
  @column()
  declare codeQualityScore: number | null
  @column()
  declare communicationQuality: number | null
  @column.dateTime()
  declare completedAt: DateTime | null
  @column()
  declare confirmations: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deadline: DateTime | null
  @column()
  declare deliveryTimeliness: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare managerReviewCompleted: boolean
  @column()
  declare overallQualityScore: number | null
  @column()
  declare peerReviewsCount: number
  @column()
  declare proactivenessScore: number | null
  @column()
  declare requiredPeerReviews: number
  @column()
  declare requirementAdherence: number | null
  @column()
  declare revieweeId: string
  @column()
  declare status: string
  @column()
  declare strengthsObserved: string | null
  @column()
  declare taskAssignmentId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare wouldWorkWithAgain: boolean | null
}

export class SkillReviewSchema extends BaseModel {
  static $columns = [
    'assignedLevelCode',
    'comment',
    'createdAt',
    'id',
    'reviewSessionId',
    'reviewerId',
    'reviewerType',
    'skillId',
    'updatedAt',
  ] as const
  $columns = SkillReviewSchema.$columns
  @column()
  declare assignedLevelCode: string
  @column()
  declare comment: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare reviewSessionId: string
  @column()
  declare reviewerId: string
  @column()
  declare reviewerType: string
  @column()
  declare skillId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SkillSchema extends BaseModel {
  static $columns = [
    'categoryCode',
    'createdAt',
    'description',
    'displayType',
    'iconUrl',
    'id',
    'isActive',
    'skillCode',
    'skillName',
    'sortOrder',
    'updatedAt',
  ] as const
  $columns = SkillSchema.$columns
  @column()
  declare categoryCode: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare displayType: string
  @column()
  declare iconUrl: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare skillCode: string
  @column()
  declare skillName: string
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TaskApplicationSchema extends BaseModel {
  static $columns = [
    'applicantId',
    'applicationSource',
    'applicationStatus',
    'appliedAt',
    'expectedRate',
    'id',
    'message',
    'portfolioLinks',
    'rejectionReason',
    'reviewedAt',
    'reviewedBy',
    'taskId',
  ] as const
  $columns = TaskApplicationSchema.$columns
  @column()
  declare applicantId: string
  @column()
  declare applicationSource: string
  @column()
  declare applicationStatus: string
  @column.dateTime()
  declare appliedAt: DateTime | null
  @column()
  declare expectedRate: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare message: string | null
  @column()
  declare portfolioLinks: any | null
  @column()
  declare rejectionReason: string | null
  @column.dateTime()
  declare reviewedAt: DateTime | null
  @column()
  declare reviewedBy: string | null
  @column()
  declare taskId: string
}

export class TaskAssignmentSchema extends BaseModel {
  static $columns = [
    'actualHours',
    'assignedAt',
    'assignedBy',
    'assigneeId',
    'assignmentStatus',
    'assignmentType',
    'completedAt',
    'completionNotes',
    'estimatedHours',
    'id',
    'progressPercentage',
    'taskId',
    'verifiedAt',
    'verifiedBy',
  ] as const
  $columns = TaskAssignmentSchema.$columns
  @column()
  declare actualHours: string | null
  @column.dateTime()
  declare assignedAt: DateTime | null
  @column()
  declare assignedBy: string
  @column()
  declare assigneeId: string
  @column()
  declare assignmentStatus: string
  @column()
  declare assignmentType: string
  @column.dateTime()
  declare completedAt: DateTime | null
  @column()
  declare completionNotes: string | null
  @column()
  declare estimatedHours: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare progressPercentage: number
  @column()
  declare taskId: string
  @column.dateTime()
  declare verifiedAt: DateTime | null
  @column()
  declare verifiedBy: string | null
}

export class TaskRequiredSkillSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'id',
    'isMandatory',
    'requiredLevelCode',
    'skillId',
    'taskId',
  ] as const
  $columns = TaskRequiredSkillSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isMandatory: boolean
  @column()
  declare requiredLevelCode: string
  @column()
  declare skillId: string
  @column()
  declare taskId: string
}

export class TaskSelfAssessmentSchema extends BaseModel {
  static $columns = [
    'blockersEncountered',
    'confidenceLevel',
    'createdAt',
    'difficultyFelt',
    'id',
    'overallSatisfaction',
    'skillsFeltLacking',
    'skillsFeltStrong',
    'submittedAt',
    'taskAssignmentId',
    'updatedAt',
    'userId',
    'whatWentWell',
    'whatWouldDoDifferent',
  ] as const
  $columns = TaskSelfAssessmentSchema.$columns
  @column()
  declare blockersEncountered: any
  @column()
  declare confidenceLevel: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare difficultyFelt: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare overallSatisfaction: number | null
  @column()
  declare skillsFeltLacking: any
  @column()
  declare skillsFeltStrong: any
  @column.dateTime()
  declare submittedAt: DateTime
  @column()
  declare taskAssignmentId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
  @column()
  declare whatWentWell: string | null
  @column()
  declare whatWouldDoDifferent: string | null
}

export class TaskStatusSchema extends BaseModel {
  static $columns = [
    'category',
    'color',
    'createdAt',
    'deletedAt',
    'description',
    'icon',
    'id',
    'isDefault',
    'isSystem',
    'name',
    'organizationId',
    'slug',
    'sortOrder',
    'updatedAt',
  ] as const
  $columns = TaskStatusSchema.$columns
  @column()
  declare category: any
  @column()
  declare color: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare icon: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isDefault: boolean
  @column()
  declare isSystem: boolean
  @column()
  declare name: string
  @column()
  declare organizationId: string
  @column()
  declare slug: string
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TaskVersionSchema extends BaseModel {
  static $columns = [
    'assignedTo',
    'changedAt',
    'changedBy',
    'description',
    'difficulty',
    'id',
    'label',
    'priority',
    'status',
    'taskId',
    'title',
  ] as const
  $columns = TaskVersionSchema.$columns
  @column()
  declare assignedTo: string | null
  @column.dateTime()
  declare changedAt: DateTime
  @column()
  declare changedBy: string
  @column()
  declare description: string | null
  @column()
  declare difficulty: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare label: string
  @column()
  declare priority: string
  @column()
  declare status: string
  @column()
  declare taskId: string
  @column()
  declare title: string
}

export class TaskWorkflowTransitionSchema extends BaseModel {
  static $columns = [
    'conditions',
    'createdAt',
    'fromStatusId',
    'id',
    'organizationId',
    'toStatusId',
  ] as const
  $columns = TaskWorkflowTransitionSchema.$columns
  @column()
  declare conditions: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fromStatusId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare organizationId: string
  @column()
  declare toStatusId: string
}

export class TaskSchema extends BaseModel {
  static $columns = [
    'acceptanceCriteria',
    'actualTime',
    'applicationDeadline',
    'assignedTo',
    'autonomyLevel',
    'businessDomain',
    'collaborationType',
    'complexityNotes',
    'contextBackground',
    'createdAt',
    'creatorId',
    'deletedAt',
    'description',
    'difficulty',
    'domainTags',
    'dueDate',
    'environment',
    'estimatedBudget',
    'estimatedTime',
    'estimatedUsersAffected',
    'expectedDeliverables',
    'externalApplicationsCount',
    'id',
    'impactScope',
    'label',
    'learningObjectives',
    'measurableOutcomes',
    'organizationId',
    'parentTaskId',
    'priority',
    'problemCategory',
    'projectId',
    'roleInTask',
    'sortOrder',
    'status',
    'taskStatusId',
    'taskType',
    'taskVisibility',
    'techStack',
    'title',
    'updatedAt',
    'updatedBy',
    'verificationMethod',
  ] as const
  $columns = TaskSchema.$columns
  @column()
  declare acceptanceCriteria: string
  @column()
  declare actualTime: string | null
  @column.dateTime()
  declare applicationDeadline: DateTime | null
  @column()
  declare assignedTo: string | null
  @column()
  declare autonomyLevel: string | null
  @column()
  declare businessDomain: string | null
  @column()
  declare collaborationType: string | null
  @column()
  declare complexityNotes: string | null
  @column()
  declare contextBackground: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare creatorId: string
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string
  @column()
  declare difficulty: string | null
  @column()
  declare domainTags: any
  @column.dateTime()
  declare dueDate: DateTime
  @column()
  declare environment: string | null
  @column()
  declare estimatedBudget: string | null
  @column()
  declare estimatedTime: string | null
  @column()
  declare estimatedUsersAffected: number | null
  @column()
  declare expectedDeliverables: any
  @column()
  declare externalApplicationsCount: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare impactScope: string | null
  @column()
  declare label: string
  @column()
  declare learningObjectives: any
  @column()
  declare measurableOutcomes: any
  @column()
  declare organizationId: string
  @column()
  declare parentTaskId: string | null
  @column()
  declare priority: string
  @column()
  declare problemCategory: string | null
  @column()
  declare projectId: string | null
  @column()
  declare roleInTask: string | null
  @column()
  declare sortOrder: number
  @column()
  declare status: string
  @column()
  declare taskStatusId: string
  @column()
  declare taskType: string
  @column()
  declare taskVisibility: string
  @column()
  declare techStack: any
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare updatedBy: string | null
  @column()
  declare verificationMethod: string
}

export class UserDomainExpertiseSchema extends BaseModel {
  static $columns = [
    'calculatedAt',
    'createdAt',
    'domainFrequency',
    'id',
    'problemCategoryFrequency',
    'techStackFrequency',
    'topSkills',
    'updatedAt',
    'userId',
  ] as const
  $columns = UserDomainExpertiseSchema.$columns
  @column.dateTime()
  declare calculatedAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare domainFrequency: any
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare problemCategoryFrequency: any
  @column()
  declare techStackFrequency: any
  @column()
  declare topSkills: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class UserOauthProviderSchema extends BaseModel {
  static $columns = [
    'accessToken',
    'createdAt',
    'email',
    'id',
    'provider',
    'providerId',
    'refreshToken',
    'updatedAt',
    'userId',
  ] as const
  $columns = UserOauthProviderSchema.$columns
  @column()
  declare accessToken: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare provider: string
  @column()
  declare providerId: string
  @column()
  declare refreshToken: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class UserPerformanceStatSchema extends BaseModel {
  static $columns = [
    'avgDaysEarlyOrLate',
    'avgQualityScore',
    'calculatedAt',
    'createdAt',
    'currentOnTimeStreak',
    'id',
    'longestOnTimeStreak',
    'onTimeDeliveryRate',
    'performanceScore',
    'periodEnd',
    'periodStart',
    'selfAssessmentAccuracy',
    'tasksAsLead',
    'tasksAsSoleContributor',
    'tasksByDifficulty',
    'tasksByDomain',
    'tasksByType',
    'tasksMentoringOthers',
    'totalHoursWorked',
    'totalTasksCompleted',
    'updatedAt',
    'userId',
  ] as const
  $columns = UserPerformanceStatSchema.$columns
  @column()
  declare avgDaysEarlyOrLate: string | null
  @column()
  declare avgQualityScore: string | null
  @column.dateTime()
  declare calculatedAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currentOnTimeStreak: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare longestOnTimeStreak: number
  @column()
  declare onTimeDeliveryRate: string | null
  @column()
  declare performanceScore: string | null
  @column.dateTime()
  declare periodEnd: DateTime | null
  @column.dateTime()
  declare periodStart: DateTime | null
  @column()
  declare selfAssessmentAccuracy: string | null
  @column()
  declare tasksAsLead: number
  @column()
  declare tasksAsSoleContributor: number
  @column()
  declare tasksByDifficulty: any
  @column()
  declare tasksByDomain: any
  @column()
  declare tasksByType: any
  @column()
  declare tasksMentoringOthers: number
  @column()
  declare totalHoursWorked: string
  @column()
  declare totalTasksCompleted: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class UserProfileSnapshotSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'id',
    'isCurrent',
    'isPublic',
    'performanceMetrics',
    'scoringVersion',
    'shareableSlug',
    'shareableToken',
    'skillsVerified',
    'snapshotName',
    'summary',
    'trustMetrics',
    'updatedAt',
    'userId',
    'version',
    'workHighlights',
  ] as const
  $columns = UserProfileSnapshotSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isCurrent: boolean
  @column()
  declare isPublic: boolean
  @column()
  declare performanceMetrics: any
  @column()
  declare scoringVersion: string
  @column()
  declare shareableSlug: string | null
  @column()
  declare shareableToken: string | null
  @column()
  declare skillsVerified: any
  @column()
  declare snapshotName: string | null
  @column()
  declare summary: any
  @column()
  declare trustMetrics: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
  @column()
  declare version: number
  @column()
  declare workHighlights: any
}

export class UserSkillSchema extends BaseModel {
  static $columns = [
    'avgPercentage',
    'avgScore',
    'createdAt',
    'id',
    'lastCalculatedAt',
    'lastReviewedAt',
    'levelCode',
    'skillId',
    'source',
    'totalReviews',
    'updatedAt',
    'userId',
  ] as const
  $columns = UserSkillSchema.$columns
  @column()
  declare avgPercentage: string | null
  @column()
  declare avgScore: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastCalculatedAt: DateTime | null
  @column.dateTime()
  declare lastReviewedAt: DateTime | null
  @column()
  declare levelCode: string
  @column()
  declare skillId: string
  @column()
  declare source: string | null
  @column()
  declare totalReviews: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class UserSubscriptionSchema extends BaseModel {
  static $columns = [
    'autoRenew',
    'createdAt',
    'expiresAt',
    'id',
    'plan',
    'startedAt',
    'status',
    'updatedAt',
    'userId',
  ] as const
  $columns = UserSubscriptionSchema.$columns
  @column()
  declare autoRenew: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare plan: string
  @column.dateTime()
  declare startedAt: DateTime
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class UserWorkHistorySchema extends BaseModel {
  static $columns = [
    'actualHours',
    'autonomyLevel',
    'businessDomain',
    'collaborationType',
    'completedAt',
    'createdAt',
    'daysEarlyOrLate',
    'difficulty',
    'domainTags',
    'estimatedBusinessValue',
    'estimatedHours',
    'evidenceLinks',
    'id',
    'isFeatured',
    'isPublic',
    'knowledgeArtifacts',
    'measurableOutcomes',
    'organizationId',
    'overallQualityScore',
    'problemCategory',
    'projectId',
    'roleInTask',
    'skillScores',
    'taskAssignmentId',
    'taskId',
    'taskTitle',
    'taskType',
    'techStack',
    'updatedAt',
    'userId',
    'wasOnTime',
  ] as const
  $columns = UserWorkHistorySchema.$columns
  @column()
  declare actualHours: string | null
  @column()
  declare autonomyLevel: string | null
  @column()
  declare businessDomain: string | null
  @column()
  declare collaborationType: string | null
  @column.dateTime()
  declare completedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare daysEarlyOrLate: number | null
  @column()
  declare difficulty: string | null
  @column()
  declare domainTags: any
  @column()
  declare estimatedBusinessValue: string | null
  @column()
  declare estimatedHours: string | null
  @column()
  declare evidenceLinks: any
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isFeatured: boolean
  @column()
  declare isPublic: boolean
  @column()
  declare knowledgeArtifacts: any
  @column()
  declare measurableOutcomes: any
  @column()
  declare organizationId: string | null
  @column()
  declare overallQualityScore: string | null
  @column()
  declare problemCategory: string | null
  @column()
  declare projectId: string | null
  @column()
  declare roleInTask: string | null
  @column()
  declare skillScores: any
  @column()
  declare taskAssignmentId: string
  @column()
  declare taskId: string
  @column()
  declare taskTitle: string
  @column()
  declare taskType: string | null
  @column()
  declare techStack: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
  @column()
  declare wasOnTime: boolean | null
}

export class UserSchema extends BaseModel {
  static $columns = [
    'address',
    'authMethod',
    'avatarUrl',
    'bio',
    'createdAt',
    'credibilityData',
    'currentOrganizationId',
    'deletedAt',
    'email',
    'freelancerCompletedTasksCount',
    'freelancerRating',
    'id',
    'isFreelancer',
    'isVerifiedBadge',
    'language',
    'phone',
    'profileSettings',
    'rankingPriority',
    'status',
    'systemRole',
    'timezone',
    'trustData',
    'updatedAt',
    'username',
  ] as const
  $columns = UserSchema.$columns
  @column()
  declare address: string | null
  @column()
  declare authMethod: string | null
  @column()
  declare avatarUrl: string | null
  @column()
  declare bio: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare credibilityData: any | null
  @column()
  declare currentOrganizationId: string | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string | null
  @column()
  declare freelancerCompletedTasksCount: number | null
  @column()
  declare freelancerRating: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isFreelancer: boolean | null
  @column()
  declare isVerifiedBadge: boolean | null
  @column()
  declare language: string | null
  @column()
  declare phone: string | null
  @column()
  declare profileSettings: any | null
  @column()
  declare rankingPriority: number | null
  @column()
  declare status: string
  @column()
  declare systemRole: string
  @column()
  declare timezone: string | null
  @column()
  declare trustData: any | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare username: string
}
