import { writeFile, mkdir, readdir } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join, relative } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '../..')

async function globFiles(dir, pattern, results = []) {
  const fullDir = join(root, dir)
  let entries
  try {
    entries = await readdir(fullDir, { withFileTypes: true })
  } catch {
    return results
  }
  for (const entry of entries) {
    const fullPath = join(fullDir, entry.name)
    if (entry.isDirectory()) {
      await globFiles(relative(root, fullPath), pattern, results)
    } else if (entry.isFile() && pattern.test(entry.name)) {
      results.push(relative(root, fullPath))
    }
  }
  return results
}

const collectMany = async (entries) => {
  const results = []

  for (const [dir, pattern] of entries) {
    await globFiles(dir, pattern, results)
  }

  return results.sort()
}

const MODULE_SUITE_PATTERNS = {
  component: /inertia\/apps\/[^/]+\/tests\/(?:modules|shared)\/.+\.(test|spec)\.ts$/,
  e2e: /inertia\/apps\/[^/]+\/tests\/e2e\/.+\.spec\.ts$/,
  unit: /app\/modules\/[^/]+\/tests\/unit\/.+\.spec\.ts$/,
  backendUnit: /app\/modules\/[^/]+\/tests\/backend\/unit\/.+\.spec\.ts$/,
  integration: /app\/modules\/[^/]+\/tests\/integration\/.+\.spec\.ts$/,
  backendIntegration: /app\/modules\/[^/]+\/tests\/backend\/integration\/.+\.spec\.ts$/,
  contract: /app\/modules\/[^/]+\/tests\/contract\/.+\.spec\.ts$/,
  backendContract: /app\/modules\/[^/]+\/tests\/backend\/contract\/.+\.spec\.ts$/,
}

const inventory = {
  vitestIncluded: await collectMany([
    ['inertia/apps', /\.(test|spec)\.ts$/],
  ]),
  wrapperFixtures: await globFiles('inertia/apps', /\.fixture\.svelte$/),
  playwrightSpecs: await collectMany([
    ['inertia/apps', /\.spec\.ts$/],
  ]),
  japaUnitSpecs: await collectMany([
    ['app/modules', /\.spec\.ts$/],
  ]),
  japaIntegrationSpecs: await collectMany([
    ['app/modules', /\.spec\.ts$/],
  ]),
  contractSpecs: await collectMany([
    ['app/modules', /\.spec\.ts$/],
  ]),
}

inventory.vitestIncluded = inventory.vitestIncluded.filter((file) => {
  return MODULE_SUITE_PATTERNS.component.test(file)
})

inventory.playwrightSpecs = inventory.playwrightSpecs.filter((file) => {
  return MODULE_SUITE_PATTERNS.e2e.test(file)
})

inventory.japaUnitSpecs = inventory.japaUnitSpecs.filter((file) => {
  return (
    MODULE_SUITE_PATTERNS.unit.test(file) ||
    MODULE_SUITE_PATTERNS.backendUnit.test(file)
  )
})

inventory.japaIntegrationSpecs = inventory.japaIntegrationSpecs.filter((file) => {
  return (
    MODULE_SUITE_PATTERNS.integration.test(file) ||
    MODULE_SUITE_PATTERNS.backendIntegration.test(file)
  )
})

inventory.contractSpecs = inventory.contractSpecs.filter((file) => {
  return (
    MODULE_SUITE_PATTERNS.contract.test(file) ||
    MODULE_SUITE_PATTERNS.backendContract.test(file)
  )
})

inventory.counts = {
  componentRunnable: inventory.vitestIncluded.length,
  wrapperFixtures: inventory.wrapperFixtures.length,
  e2eFiles: inventory.playwrightSpecs.length,
  unitFiles: inventory.japaUnitSpecs.length,
  integrationFiles: inventory.japaIntegrationSpecs.length,
  contractFiles: inventory.contractSpecs.length,
  totalTestFiles:
    inventory.vitestIncluded.length +
    inventory.playwrightSpecs.length +
    inventory.japaUnitSpecs.length +
    inventory.japaIntegrationSpecs.length +
    inventory.contractSpecs.length,
}

const outJson = join(root, 'docs/test/generated/runnable_inventory.json')
const outMd = join(root, 'docs/test/generated/runnable_inventory.md')

await mkdir(dirname(outJson), { recursive: true })
await writeFile(outJson, JSON.stringify(inventory, null, 2))
await writeFile(outMd, `# Runnable Test Inventory\n\n> Generated by \`scripts/tests/collect_test_inventory.mjs\`.\n> Do not edit manually.\n\n## Counts\n\n| Suite | Files |\n|---|---|\n| Component (Vitest runnable) | ${inventory.counts.componentRunnable} |\n| Wrapper fixtures (non-runnable) | ${inventory.counts.wrapperFixtures} |\n| E2E (Playwright specs) | ${inventory.counts.e2eFiles} |\n| Unit (Japa specs) | ${inventory.counts.unitFiles} |\n| Integration (Japa specs) | ${inventory.counts.integrationFiles} |\n| Contract | ${inventory.counts.contractFiles} |\n| **Total test files** | **${inventory.counts.totalTestFiles}** |\n\n## Component runnable files\n\n${inventory.vitestIncluded.map(f => `- ${f}`).join('\n')}\n\n## E2E files\n\n${inventory.playwrightSpecs.map(f => `- ${f}`).join('\n')}\n\n## Wrapper fixtures (non-runnable)\n\n${inventory.wrapperFixtures.map(f => `- ${f}`).join('\n')}\n
`)

console.log('Inventory written to')
console.log('  ', outJson)
console.log('  ', outMd)
console.log('Counts:', JSON.stringify(inventory.counts, null, 2))
