#!/usr/bin/env sh
set -eu

REQUESTED_ELASTICSEARCH_TEST_ENABLED="${ELASTICSEARCH_TEST_ENABLED:-}"
REQUESTED_ELASTICSEARCH_TEST_NODE="${ELASTICSEARCH_TEST_NODE:-}"
REQUESTED_ELASTICSEARCH_TEST_USERNAME="${ELASTICSEARCH_TEST_USERNAME:-}"
REQUESTED_ELASTICSEARCH_TEST_PASSWORD="${ELASTICSEARCH_TEST_PASSWORD:-}"
REQUESTED_ELASTICSEARCH_TEST_INDEX_PREFIX="${ELASTICSEARCH_TEST_INDEX_PREFIX:-}"

# Load environment variables from .env file
if [ -f .env ]; then
  set -a
  . ./.env
  set +a
fi

restore_requested() {
  key="$1"
  value="$2"
  if [ -n "$value" ]; then
    export "$key=$value"
  fi
}

restore_requested ELASTICSEARCH_TEST_ENABLED "$REQUESTED_ELASTICSEARCH_TEST_ENABLED"
restore_requested ELASTICSEARCH_TEST_NODE "$REQUESTED_ELASTICSEARCH_TEST_NODE"
restore_requested ELASTICSEARCH_TEST_USERNAME "$REQUESTED_ELASTICSEARCH_TEST_USERNAME"
restore_requested ELASTICSEARCH_TEST_PASSWORD "$REQUESTED_ELASTICSEARCH_TEST_PASSWORD"
restore_requested ELASTICSEARCH_TEST_INDEX_PREFIX "$REQUESTED_ELASTICSEARCH_TEST_INDEX_PREFIX"

: "${PG_TEST_DATABASE:?PG_TEST_DATABASE is required}"
: "${ELASTICSEARCH_TEST_NODE:?ELASTICSEARCH_TEST_NODE is required}"
: "${ELASTICSEARCH_TEST_INDEX_PREFIX:?ELASTICSEARCH_TEST_INDEX_PREFIX is required}"

export SUAR_TEST_BASELINE_ELASTICSEARCH_NODE_CAPTURED=true
if [ -n "${ELASTICSEARCH_NODE:-}" ]; then
  export SUAR_TEST_BASELINE_ELASTICSEARCH_NODE="$ELASTICSEARCH_NODE"
else
  unset SUAR_TEST_BASELINE_ELASTICSEARCH_NODE
fi

export NODE_ENV=test
export ELASTICSEARCH_TEST_ENABLED="${ELASTICSEARCH_TEST_ENABLED:-true}"
export ELASTICSEARCH_ENABLED="$ELASTICSEARCH_TEST_ENABLED"
export ELASTICSEARCH_NODE="$ELASTICSEARCH_TEST_NODE"
export ELASTICSEARCH_USERNAME="${ELASTICSEARCH_TEST_USERNAME:-}"
export ELASTICSEARCH_PASSWORD="${ELASTICSEARCH_TEST_PASSWORD:-}"
export ELASTICSEARCH_INDEX_PREFIX="$ELASTICSEARCH_TEST_INDEX_PREFIX"

node --import=@poppinss/ts-exec --input-type=module -e \
  "const guard = await import('./tests/helpers/test_datastore_guard.ts'); guard.applyTestDatastoreOverrides(); await guard.assertSafeTestDatastores();"

pnpm run db:test:migrate
pnpm exec vite build

PG_DATABASE="$PG_TEST_DATABASE" \
PG_TEST_DATABASE="$PG_TEST_DATABASE" \
node --import=@poppinss/ts-exec bin/test.ts integration
