import {
  Activity,
  Boxes,
  Building,
  Building2,
  Briefcase,
  ChartNoAxesColumnIncreasing,
  ClipboardCheck,
  FileText,
  Flag,
  FolderKanban,
  GitBranch,
  Globe,
  LayoutDashboard,
  Mail,
  Package2,
  Palette,
  Settings,
  Settings2,
  Shield,
  SquareCheckBig,
  Star,
  Store,
  User,
  UserCircle,
  UserRoundPlus,
  Users,
} from 'lucide-svelte'
export type LucideIconComponent = typeof Boxes

export const lucideIconMap = {
  Activity,
  Boxes,
  Building,
  Building2,
  Briefcase,
  ChartNoAxesColumnIncreasing,
  ClipboardCheck,
  FileText,
  Flag,
  FolderKanban,
  GitBranch,
  Globe,
  LayoutDashboard,
  Mail,
  Package2,
  Palette,
  Settings,
  Settings2,
  Shield,
  SquareCheckBig,
  Star,
  Store,
  User,
  UserCircle,
  UserRoundPlus,
  Users,
} satisfies Record<string, LucideIconComponent>

export type LucideIconName = keyof typeof lucideIconMap
