export const FRONTEND_PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_PER_PAGE: 20,
  ORGANIZATIONS_ITEMS_PER_PAGE: 10,
  ALL_ORGANIZATIONS_ITEMS_PER_PAGE: 12,
  REQUIRE_ORGANIZATION_ITEMS_PER_PAGE: 6,
} as const
